### ISSUE TITLE
TimeZones

### ISSUE THREAD

**Issue by shuklaalok7** [ical4j/ical4j#10]
This is more sort of a question. I could not find a method to get or create `VTimeZone` object if I have `offset` from GMT (Greenwich Mean Time), i.e `"GMT-8:00"` or `"GMT+3:30"` etc.

**Comment by benfortuna** [comment]
The timezone definitions don't currently support offset-based ids, however it would be possible to add them to the tz.alias list:

https://github.com/ical4j/ical4j/blob/ical4j-1.x-maintenance/src/main/resources/net/fortuna/ical4j/model/tz.alias

It would however be a bit arbitrary which actual timezone it would map to, so may be better to use the city-based ids if at all possible.
