### ISSUE TITLE
Update to java 8

### ISSUE THREAD

**Issue by artheus** [ical4j/ical4j#104]
My personal opinion is that building and targeting JDK 1.6 is a limitation in producing a good java library. 

Java SE 6 was made in 2006 and SE 8 in 2014. There are huge differences in the language itself, there is also a ton of security fixes between 6 and 8.

I am willing to help on this. if this is something you are interested in doing.

**Comment by benfortuna** [comment]
Whilst I think most organisations now use a minimum of Java 7 in production, I actually have some weekly stats from the tzurl.org site that give a rough indication of the JVM in use (see below).

The concern is that Java 6 still seems to be in use quite a bit, so as far as language changes go if we can keep the syntax compatible with Java 6 that is preferred. Happy to use Java 8 for compilation, etc. but if possible with target=1.6. Perhaps we could also look at producing different release distributions if really necessary.


|#reqs	|#pages	|browser
|-----------|-----------|---------
|4225117	|4225117	|Java/1.8.0_60
|49197	|49197	|Dalvik/2.1.0 (Linux; U; Android 6.0; Le X620 Build/HEXCNFN5801708221S)
|32361	|32361	|Java/1.6.0_24
|19837	|19837	|Dalvik/2.1.0 (Linux; U; Android 6.0; FEVER Build/MRA58K)
|14422	|14422	|Dalvik/2.1.0 (Linux; U; Android 5.0.2; Letv X500 Build/DBXCNOP5501304131S)
|14357	|14357	|AppEngine-Google; (+http://code.google.com/appengine; appid: s~setmoreappointments)
|11072	|11072	|Dalvik/2.1.0 (Linux; U; Android 5.0.2; Letv X501 Build/DBXCNOP5501304131S)
|9821	|9821	|Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-G920F Build/MMB29K)
|9392	|9392	|Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-G935F Build/MMB29K)
|8839	|8839	|Java/1.8.0_92
|8138	|8138	|Dalvik/2.1.0 (Linux; U; Android 6.0.1; Le X820 Build/FEXCNFN5801708261S)
|7023	|7023	|Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5 Build/MOB31E)
|6999	|6999	|Dalvik/2.1.0 (Linux; U; Android 5.0.2; x600 Build/ABXCNOP5501304131S)
|5985	|5985	|Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-G925F Build/MMB29K)
|5719	|5719	|Java/1.7.0_111

**Comment by artheus** [comment]
Ok. Is this tracking libraries/applications using ical4j or is it global generic data? I would like to see the difference.

Different builds for different jvms sounds nice and all. But honestly I think that requires one to be limited to what syntax to use. I would suggest saying in the README.md that Java6/7 users can depend on older versions, and Java 8 the latest. I have seen many people to exactly that.

**Comment by artheus** [comment]
I would also like to show a list of public support for java versions

http://www.oracle.com/technetwork/java/eol-135779.html

But when you look at statistics graphs I would agree with keeping jdk7 but scrap jdk6!

https://plumbr.eu/blog/java/java-version-statistics-2015-edition

*Disclaimer! I have not researched the reliability of the last link though.*

**Comment by benfortuna** [comment]
Ok, I think minimum Java 7 is fair enough. Will look to making the transition shortly, but first will try to make a final release of master (2.0) and then remove support for Java 6.

**Comment by artheus** [comment]
Okay! Great!
I would love to help on that! As you might have seen I have made a branch
named artheus/tojava8 on my fork and sent a pull-request.
Sorrily that pull-request got huuge due to me auto-formatting the code and
committing. I can redo that by copying out the nice parts of that commit,
which should be compatible with 1.7 source as I do not think I used java 8
features like lambdas pr anything.

I can rebase that onto the 2.0 release when that is done.

If you want to, please include me in the 2.0 releasing aswell.

**Comment by woai110120130** [comment]
hi , Dalvik/2.1.0 (Linux; U; Android 5.0.2; Letv X500 Build/DBXCNOP5501304131S) is I Development，　

Where did you get the data

**Comment by benfortuna** [comment]
It is from the timezone update HTTP requests documented here:

https://github.com/ical4j/ical4j/wiki/Timezones#tzurl

I've removed references to non-JVM environments above as it wasn't really relevant to the issue.

**Comment by codylerum** [comment]
👍 for moving to Java 8 minimum for a 3.0 release and let the community maintain 2.0 if they are intersted in keeping Java 7 as it is EOL

**Comment by benfortuna** [comment]
FYI pr #233 addresses update to java8 feature support
