### ISSUE TITLE
Unneeded redundancy and messy file tree

### ISSUE THREAD

**Issue by artheus** [ical4j/ical4j#108]
Many files like eg. .cvsignore and .hgignore seems redundant as this project is versioned by git etc.

Why are there tests in both Groovy and java? Why are the sample ics files in an etc directory and not in the test resources directory.

many of the files in /etc seems completely unnecessary or redundant. Why are there so many files there? Eg. RFC files can be linked to an online rfc in the README.md

Several files are also related to an individual workspace, showing windows directory URI's etc.

A clean-up of the project directory and file tree is needed!

**Comment by artheus** [comment]
There are also binary .jar files in the lib directory. They should be removed from versioning.

**Comment by benfortuna** [comment]
#114

**Comment by brainlag** [comment]
And why are there 3 build system in the tree? AFAIK you don't need a pom file if you use gradle. Also there is stuff to build it with ant including checked in JARs. Nobody needs that.

**Comment by benfortuna** [comment]
Merged PR #114
