### ISSUE TITLE
TimeZoneRegistry.getTimeZone() method returns null for IST time zone

### ISSUE THREAD

**Issue by vdegtyarev** [ical4j/ical4j#11]
TimeZoneRegistry.getTimeZone() method returns null for Indian Standart Time (IST) id - GMT+5:30.

**Comment by benfortuna** [comment]
By default the ical4j timezone ids don't include local identifiers as they can be ambiguous (i.e. PDT can mean different timezones in different parts of the world). If you plan to use it in a specific locality you can define your own id aliases by creating a tz.alias file in the root of your resources directory. See here for an example:

https://github.com/ical4j/ical4j/blob/ical4j-1.x-maintenance/src/test/resources/tz.alias
