### ISSUE TITLE
Unexpected dates with EXDATE

### ISSUE THREAD

**Issue by artheus** [ical4j/ical4j#110]
I am now trying to add a simple EXDATE Property to my VEVENT component, this I am doing in a test for a project I am working on.

I wrote this test code:
```java
      // RECURRENCE
      Recur recurrence = new Recur();

      recurrence.setFrequency(Recur.WEEKLY);
      recurrence.getDayList().add(WeekDay.MO);
      recurrence.getDayList().add(WeekDay.TU);
      recurrence.getDayList().add(WeekDay.WE);
      recurrence.getDayList().add(WeekDay.TH);
      recurrence.getDayList().add(WeekDay.FR);
      recurrence.setWeekStartDay(WeekDay.MO.getDay());

      RRule rRule = new RRule(recurrence);

      VEvent workdays = new VEvent();

      DateList excludedDays = new DateList();

      java.util.Calendar exCal = java.util.Calendar.getInstance();
      exCal.set(2016, 6, 8, 0, 0, 0);

      // EXDATE
      excludedDays.add(new DateTime(exCal.getTimeInMillis()));

      ExDate exDate = new ExDate(excludedDays);

      workdays.getProperties().add(rRule);
      workdays.getProperties().add(exDate);

      java.util.Calendar cal = java.util.Calendar.getInstance();
      cal.set(2016, 5, 1, 9, 0, 0);

      workdays.getProperties().add(new DtStart(new DateTime(cal.getTime())));
      workdays.getProperties().add(new Duration(new Dur(0,8,0,0)));

      // GET RECCURENCE SET AND PRINT
      workdays.calculateRecurrenceSet(new Period(
          new DateTime(cal.getTimeInMillis()),
          new Dur(15, 0, 0, 0)
      )).forEach(period -> {
        System.out.println(period.getStart().getDay()+"/"+period.getEnd());
      });

      schedule.getComponents().add(workdays);

      System.out.println(schedule);
```

So this code should be quite simple and self explaining. But I am getting the unexpected property `EXDATE:20160708T000000`
So the System.out output of running this test is:

```
3/20160601T170000
4/20160602T170000
5/20160603T170000
1/20160606T170000
2/20160607T170000
3/20160608T170000
4/20160609T170000
5/20160610T170000
1/20160613T170000
2/20160614T170000
3/20160615T170000
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20161014T054030Z
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=MO,TU,WE,TH,FR
EXDATE:20160708T000000
DTSTART:20160601T090000
DURATION:PT8H
END:VEVENT
END:VCALENDAR
```

There is some kind of offset here, I am Expecting `EXDATE:20160608T000000` and the list of dates should start from `20160501`.
The offset seems to be exactly one month forward.

What am I doing wrong? I have tried testing around with TimeZones etc, though it seems very weird with an offset of one month because of wrong TimeZone.

**Comment by artheus** [comment]
Just an jUnit test addition for reproduction of my issue

```java
java.util.Calendar cal = java.util.Calendar.getInstance();
cal.clear();
cal.set(java.util.Calendar.YEAR, 2016);
cal.set(java.util.Calendar.MONTH, Month.MAY.getValue());
cal.set(java.util.Calendar.DAY_OF_MONTH, 1);
cal.set(java.util.Calendar.HOUR_OF_DAY, 9);

assertEquals("20160501T090000", new DateTime(cal.getTimeInMillis()).toString());
```

This should be pretty straight forward and working. I have read through many of the tests for iCal4j and written this in that style.
When I run the tests for the iCal4j project I am getting the expected results, but there seems to be something I am not setting up properly maybe.

Output from test:
```
07:56:15.056 [main] INFO net.fortuna.ical4j.util.Configurator - ical4j.properties not found.

org.junit.ComparisonFailure: 
Expected :20160501T090000
Actual   :20160601T090000
```

I am taking that INFO log line as a hint to something. But this still seems to be quite weird behaviour for an out-of-the-box iCal4j. Not configuring, should it really have an offset in dates of 1 whole month?

**Comment by arnaudq** [comment]
Please read the javadoc for java.util.Calendar. Month are zero based (and you can used the static values i.e. Calendar.MAY).

**Comment by artheus** [comment]
Thank you @arnaudq 
I read about the java.time.Calendar class now. Seems dangerous!
I started using the ZonedDateTime etc instead from the same package, those seem so much more safe for use. And everything started to work properly.

So this was not at all an iCal4j issue.
Note! Do not use java.util.Calendar, ever!
