### ISSUE TITLE
Implement JSON calendar outputter

### ISSUE THREAD

**Issue by benfortuna** [ical4j/ical4j#112]
Potentially use the "jCal" format proposed in the following RFC:

https://tools.ietf.org/html/rfc7265

**Comment by benfortuna** [comment]
Another alternative is schema.org (supported by google, yahoo, etc.):

http://schema.org/docs/full.html

**Comment by artheus** [comment]
Google sponsored is good and all. But to me it seems to be a completely different calendar format. No?
jCal is iCal in json format. I don't really see the purpose of json-formatting iCal, though. Wouldn't that just give the format an unnessecary overhead in output filesize?

**Comment by benfortuna** [comment]
I think the purpose of schema.org is more to provide a common model for semantic web-style interoperation been sites, etc.

It wouldn't be a replacement for the standard iCalendar format, but rather provide an alternative to support web interactions.

**Comment by tdroxler** [comment]
Hello, sorry for resurrecting this, but is there any plan for this?

**Comment by benfortuna** [comment]
Yes, if there is a popular JSON format would be happy to add support for it. 

Features are mostly driven by demand, so whatever is the more useful format will probably get more attention.

**Comment by douglm** [comment]
There is an rfc which is in last call:

https://datatracker.ietf.org/doc/draft-ietf-calext-jscalendar/

An issue to be resolved is that this is not a fully iCalendar compatible 
representation - nor is it meant to be.

However, there's a good chance this will be the favored representation 
as we move forward. CalConnect has had many discussions about promoting 
an iCalendar 3 to allow for new constructs. I think this is going to be 
the favored approach.

**Comment by benfortuna** [comment]
See new project ica4j-json. Initial support targeting jCal and JSCalendar.

https://github.com/ical4j/ical4j-json

Please raise bugs/issues/requests in that repository.
