### ISSUE TITLE
Inconsistent text about required JVM

### ISSUE THREAD

**Issue by mernst** [ical4j/ical4j#120]
The main README, which is displayed at https://github.com/ical4j/ical4j, says both

> System Requirements
> Java 6 or later

and also

> Choosing Java 1.4 as the minimum required JVM was initially slightly arbitrary ...

Perhaps the latter text about dependences on Java 1.4 should be removed.

**Comment by benfortuna** [comment]
Removed old references to unsupported Java versions.
