### ISSUE TITLE
bndlib / groovy-all dependency

### ISSUE THREAD

**Issue by MikeN123** [ical4j/ical4j#122]
The bndlib and groovy-all dependencies are not required, but at the moment you have to exclude them manually. They should be marked as 'optional' in the generated `pom.xml`, I think?

**Comment by benfortuna** [comment]
Yes, I think there was a limitation on the game maven plugin as there is no concept of optional dependencies in grade. I'll investigate further as I think there is now a providedCompile scope that may help.

**Comment by nfalco79** [comment]
this could help to mark them as optional

https://guides.gradle.org/migrating-from-maven/#provided_scope_and_optional_dependencies
