### ISSUE TITLE
New properties: RFC 7986

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#141]
RFC 7986 defines new properties like `COLOR` and recommends UUIDs to be used as `UID`.

Maybe these new properties and changes could be integrated into ical4j. :)

**Comment by rfc2822** [comment]
Great, thank you! :)

**Comment by rfc2822** [comment]
Unfortunately, the properties are not usable with Android, because Android doesn't have `javax` packages, especially `javax.mail-api`… I wonder how ical4j will react when such a property is parsed on Android

**Comment by benfortuna** [comment]
Ok, I wasn't sure if the additional dependency would be workable. Let me see if there's an alternative way to parse email address, or possibly just use a string value.

**Comment by benfortuna** [comment]
Release 2.2.3 removes dependency on javamail by using string value for email address (will add validation later)

**Comment by rfc2822** [comment]
> Release 2.2.3 removes dependency on javamail by using string value for email address (will add validation later)

Thank you very much, seems to work now!

**Comment by rfc2822** [comment]
I have noticed that the new parameter names are not defined in the `Parameters` class, so that you can't do `prop.getParameter(Parameters.EMAIL)` (as opposed to `prop.getParameter(Parameters.CN)`, for instance).

I'll call it directly with `prop.getParameter("EMAIL")` by now, but can I send a PR for that? For which branch?

**Comment by benfortuna** [comment]
Yup, for PRs to the 2.x releases use the 2.x-maintenance branch.
