### ISSUE TITLE
Mac OSX Calendar Export leads to ParserException: Error at line 369:Illegal property [ACKNOWLEDGED]

### ISSUE THREAD

**Issue by TheOneAndOnlySepp** [ical4j/ical4j#148]
Exports of Calender from Mac OSX contain "ACKNOWLEDGED" Property which is not handled.

BEGIN:VALARM
X-WR-ALARMUID:723FE788-3DC2-4318-B921-53XXXXXXXXD7
UID:723FE788-3DC2-4318-B921-5369XXXXXX85D7
DESCRIPTION:Reminder
ACKNOWLEDGED:20160715T142324Z
TRIGGER:-PT1H
ACTION:DISPLAY
END:VALARM

**Comment by benfortuna** [comment]
The ACKNOWLEDGED property is supported in the ical4j-extensions library. If you add this library to your classpath it should resolve the parsing issue.

**Comment by TheOneAndOnlySepp** [comment]
Hi Ben, thanks for the fast response, this really solved this issue, but now i got:

net.fortuna.ical4j.data.ParserException: Error at line 7,007:Unsupported parameter name: TO-ALL-PROPOSED-NEW-TIME

**Comment by benfortuna** [comment]
Ok that one is not yet supported. You can workaround it by enabling the RELAXED_PARSING compatibility hint, but ideally we need to add support for that param.

https://github.com/ical4j/ical4j/wiki/Compatibility

**Comment by TheOneAndOnlySepp** [comment]
Perfect, at least it is working now, thanks!
