### ISSUE TITLE
When modifying time of a single event in a series it duplicates

### ISSUE THREAD

**Issue by retog** [ical4j/ical4j#150]
When modifying the start and/or the end time of a single occurrence of a recurring event the event will be returned twice when requesting events for the period containing the modified occurrence with:
```
Filter filter = new Filter(new Rule[]{new PeriodRule(period)}, Filter.MATCH_ALL);
Collection<VEvent> events = filter.filter(calendar.getComponents(Component.VEVENT));
```
So far I've only tried with Outlook/office365 ics files. The attached file results from the following steps:
- Created recurring event
- changed the description of one event, this doesn't cause duplication
- Move the event to another time -> This duplicates the event in iCal4j

[calendar-with-modified-occurence-ics.txt](https://github.com/ical4j/ical4j/files/1083053/calendar-with-modified-occurence-ics.txt)

**Comment by retog** [comment]
I've just tried the same with Google Calendar: After changing the time of a single occurence the event is returned twice on that day by iCal4j.

**Comment by benfortuna** [comment]
Can you provide an example of the code that changes the event time? It may be possible that a new event is created but I think you would still need to explicitly add it to your calendar object. In any case the UID property should be unique so we may need to add some deduplication.

**Comment by retog** [comment]
Thanks @benfortuna.  I do not modify the event time programmatically but in Outlook or in Google Calendar. I then use the code quoted in my first comment to read the events with iCal4j.

**Comment by benfortuna** [comment]
Ok so I think this is related to an open issue here: #42 

I'll put this one in the priority list to implement, but for now you will need to somehow identify the duplicate events by checking the UID property (possibly use a Set to de-dup events).

**Comment by benfortuna** [comment]
You should now be able to work with files containing modified recurrences by using the component grouping functionality:

http://ical4j.github.io/docs/ical4j/api/3.0.0/net/fortuna/ical4j/model/ComponentGroup.html

This will group all components with the same UID/recurrence ID and allow you to work with specific revisions.

Closing the ticket, feel free to reopen if still an issue.
