### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by peterdivvito** [ical4j/ical4j#154]
Similar to  commit 84db479a9d0f3e1c4ef7e22d45c959c9d3f92992, the use of singleton factories that use a single ServiceLoader instance is not thread safe as documented in the ServiceLoader javadocs 
"Instances of this class are not safe for use by multiple concurrent threads."

- PropertyFactoryImpl
- ParameterFactoryImpl

**Comment by peterdivvito** [comment]
I have created a pull request #155 to resolve this issue

**Comment by benfortuna** [comment]
Apologies for the delay. I've included the alternate fix in the latest release 2.1.0: https://bintray.com/ical4j/maven/ical4j#files/org%2Fmnode%2Fical4j%2Fical4j%2F2.1.0

Let me know if you see any issues.

**Comment by peterdivvito** [comment]
Awesome. Thanks Ben

**Comment by stellingsimon** [comment]
I think this issue can be closed. I could reproduce the issue with older versions of `ical4j`, but no longer after upgrading to `2.1.1`.
