### ISSUE TITLE
UidGenerator.generateUid() is slow

### ISSUE THREAD

**Issue by amanteaux** [ical4j/ical4j#157]
This method can take up to 5 seconds to generate an Uid.

Actually, what takes all this time is `InetAddressHostInfo.getHostName()`.

Since the host name of the server running the JVM will not likely change at runtime, would it be possible to cache this value?

**Comment by amanteaux** [comment]
Would it be ok if I make a pull request for this?

I am started to really need this feature :)

**Comment by benfortuna** [comment]
Yup of course. My time has been a bit limited but definitely if you submit some code I can merge it in.

**Comment by amanteaux** [comment]
Thanks!
