### ISSUE TITLE
Europe/Moscow timezone is outdated

### ISSUE THREAD

**Issue by agalanin** [ical4j/ical4j#168]
Since 26 October 2014 Moscow is back to UTC+3 time zone. But Moscow.ics still contain +0400 as the last entry. So i think that time/zone database must be re-generated.

See also https://github.com/benfortuna/tzurl/issues/11.

**Comment by solomax** [comment]
Moscow is in GMT+4 as well as all Russia in (+1) time zome (summer time if I'm not mistaken)
I'm in Novosibirsk and it is GMT+7, MSK+4

**Comment by agalanin** [comment]
I found "RDATE:20141026T020000" section in one of the first sections of a generated file.
