### ISSUE TITLE
SLF4J Error in Depending Projects

### ISSUE THREAD

**Issue by HeroCC** [ical4j/ical4j#173]
Hello! I'm currently using iCal4J in one of my projects, but it has one annoying quirk: every time I run an application requiring it I get an annoying SLF4J error, such as below:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

I've looked at [that link](https://www.slf4j.org/codes.html#StaticLoggerBinder) and it says if you are a library you should:
> not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose.

I can live with the error for now, but it is getting quite annoying. 

To reproduce, add the line `compile 'org.mnode.ical4j:ical4j:2.0.2'` to the gradle dependencies block and start using ICal4J, the error should print to the console.

**Comment by benfortuna** [comment]
Those instructions are specific to libraries such as ical4j, to allow end
users to choose their preferred logging implementation. As an end user of
ical4j you should include a dependency on a specific slf4j implementation.

**Comment by HeroCC** [comment]
I don't really want to use SLF4J, I'm fine with the built in java logging mechanisms. Can I suppress the message without another dependency?

**Comment by benfortuna** [comment]
To use the built-in java logging you'll need to add the `slf4j-jdk14` dependency: https://www.slf4j.org/manual.html#swapping

As the ical4j library is compiled with slf4j it is a mandatory dependency.

You can get the slf4j dependency here: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22slf4j-jdk14%22

**Comment by HeroCC** [comment]
OK, I ended using the slf4j-nop binding as it was the smallest and I didn't really care about the ical4j logs. For anybody in the future, add `compile 'org.slf4j:slf4j-nop:1.7.25'` to your gradle dependencies and it should suppress the error.
