### ISSUE TITLE
Calculate occurrences issue. Expected event on 31th only, but it isn't.

### ISSUE THREAD

**Issue by SergiiVlasiuk** [ical4j/ical4j#174]
Trying to calculate occurrences for recurring event got issue with invalid dates. For example:
event dateTime start `20170831T071500Z`, event dateTime end `20170831T073000Z` pattern is `"FREQ=MONTHLY;COUNT=5"`. In occurrences I can have dates like `20170930T071500Z`. 30th is actual occurrence but expected Septembers` occurrence should be missed.

Test code example:

`
	void testCalculateRecurrenceSetOn31th() {
		VEvent event = new ContentBuilder().vevent {
			dtstart('20100831T061500Z', parameters: parameters() {
				value('DATETIME')})
			dtend('20100831T064500Z', parameters: parameters() {
				value('DATETIME')})
			rrule('FREQ=MONTHLY;UNTIL=20101231')
		}

		def dates = event.calculateRecurrenceSet(new Period('20100831T000000/20110131T000000'))

		def expected = new PeriodList(true)
		expected.add new Period('20100831T061500Z/PT30M')
		expected.add new Period('20101031T061500Z/PT30M')
		expected.add new Period('20101231T061500Z/PT30M')

		println dates
		assert dates == expected

		/*
		Assertion failed:

		assert dates == expected
		|     |  |
		|     |  [20100831T061500Z/PT30M, 20101031T061500Z/PT30M, 20101231T061500Z/PT30M]
		|     false
		[20100831T061500Z/PT30M, 20100930T061500Z/PT30M, 20101030T061500Z/PT30M, 20101130T061500Z/PT30M, 20101230T061500Z/PT30M]
		*/
	}
`

**Comment by SergiiVlasiuk** [comment]
It seems issue is in `Recur.java` in method

    public final DateList getDates(final Date seed, final Date periodStart,
                                   final Date periodEnd, final Value value,
                                   final int maxCount) {

all candidates are calculated using 

            increment(cal);

where `cal` is `java.util.Calendar`. If pattern has monthly strategy with period `1` `cal` will get shifted end month day, if one was specified as `31` in start/end Day. After first increment the issues repeats in month after next (if you have calculated `20100930T061500Z/PT30M` adding one month to the current `java.util.Calendar` object you'll get next mistake `20101030T061500Z/PT30M` accept of `20101031T061500Z/PT30M`) if calculation will handle `February` we'll get occurrences shifted on 29th or 28th for example and so on...

Acceptance is to ignore dates that are not mapped on pattern (that does not contain 31th month day)

---
 `Recur.java`:

    private void increment(final Calendar cal) {
        // initialise interval..
        final int calInterval = (getInterval() >= 1) ? getInterval() : 1;
        cal.add(calIncField, calInterval);
    }

**Comment by SergiiVlasiuk** [comment]
The ugly solution of this issue is to use (instead of the `increment(cal);`)

    private Calendar smartIncrement(final Calendar cal) {
        // initialise interval..
        Calendar result = null;
        final int calInterval = (getInterval() >= 1) ? getInterval() : 1;
        int multiplier = 1;
        if (calIncField == 2 || calIncField == 1) {
            Calendar seededCal;
            do {
                seededCal = (Calendar) cal.clone();
                seededCal.add(calIncField, calInterval * multiplier);
                multiplier++;
            } while (seededCal.get(Calendar.DAY_OF_MONTH) != cal.get(Calendar.DAY_OF_MONTH) || multiplier > 10);
            if (multiplier <= 10) {
                result = (Calendar) seededCal.clone();
            }
        } else {
            result = (Calendar) cal.clone();
            result.add(calIncField, calInterval);
        }
        return result;
    }

It helps me but this solution is not good for current library structure.

**Comment by benfortuna** [comment]
Thanks for the patch. I've included this fix in the latest release 2.1.0: https://bintray.com/ical4j/maven/ical4j#files/org%2Fmnode%2Fical4j%2Fical4j%2F2.1.0

Let me know if you see any issues.

**Comment by SergiiVlasiuk** [comment]
I've just used it.
I have not expected for so fast reaction.
Thanks a lot!

**Comment by benfortuna** [comment]
Fix applied. Closing issue.
