### ISSUE TITLE
Make JCache optional

### ISSUE THREAD

**Issue by malkusch** [ical4j/ical4j#195]
After upgrading to 2.1.1 my application fails with this error:

    Caused by: javax.cache.CacheException: No CachingProviders have been configured
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:381) ~[cache-api-1.0.0.jar:na]
	at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:351) ~[cache-api-1.0.0.jar:na]
	at javax.cache.Caching.getCachingProvider(Caching.java:142) ~[cache-api-1.0.0.jar:na]
	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:285) ~[ical4j-2.1.1.jar:na]
	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:83) ~[ical4j-2.1.1.jar:na]
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125) ~[ical4j-2.1.1.jar:na]
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116) ~[ical4j-2.1.1.jar:na]
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48) ~[ical4j-2.1.1.jar:na]
	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105) ~[ical4j-2.1.1.jar:na]

I understand that this was introduced with #192 and adding a JCache provider on the class path fixes that issue. However I would've prefered a smooth upgrade where adding a cache provider is optional.

**Comment by benfortuna** [comment]
My apologies, I did consider the inconvenience of the added dependency and how to avoid it. In the end the decision to require jcache was the result of enabling timezone caching by default.

If it does present a major inconvenience I will see if we can make it an optional dependency in conjunction with disabling timezone caching/updating.

**Comment by malkusch** [comment]
I didn't feel it as a *major* inconvenience, however unexpected for a minor version change. Also I might feel users might exist who do not know how to fix that. But I guess if nobody else complains, it's not an issue at all. You might close this then.

**Comment by benfortuna** [comment]
I've just applied an update to allow optional inclusion of a jcache provider. You just need to add the following line to your `ical4j.properties` configuration:

`net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache`

This just configures to use a Map-based cache rather than jcache. You can also provide your own implementation of `TimeZoneCache` if you prefer.

**Comment by malkusch** [comment]
Thank you very much.

**Comment by bbottema** [comment]
> You just need to add the following line to your ical4j.properties configuration:
> 
> `net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache`

To do this without properties file:

`System.setProperty("net.fortuna.ical4j.timezone.cache.impl", MapTimeZoneCache.class.getName());`

**Comment by w0yne** [comment]
> You just need to add the following line to your ical4j.properties configuration:
> `net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache`

For Android projects, please put the configuration file to `app/main/resources/ical4j.properties`.

**Comment by t033y** [comment]
I added 
`System.setProperty("net.fortuna.ical4j.timezone.cache.impl", MapTimeZoneCache.class.getName());`
to the code and have following error right now:
`java.util.ServiceConfigurationError: net.fortuna.ical4j.validate.CalendarValidatorFactory: Provider net.fortuna.ical4j.validate.DefaultCalendarValidatorFactory not a subtype`

How can I fix it?

**Comment by crudolf** [comment]
Is there an alternative to add a system property when using 

TimeZoneRegistry registry = TimeZoneRegistryFactory.getInstance().createRegistry();

Is it possible to use it without cache? I think it would be smart to have a default value that works out of the box?

**Comment by bubbatls** [comment]
With the build 3.0.7
It cannot be launch without the cache-api jar, it causes
ClassNotFoundException: javax.cache.configuration.Configuration
Event with the good property setted.

As 
net.fortuna.ical4j.util.MapTimeZoneCache
does the job well for most users, why not using it by default? instead of forcing user to integrate a huge lib and a huge implemntation lib or a huge lib which will not be used and a ical.properties

**Comment by benfortuna** [comment]
Ok sure, I'll have a look at changing the default.

**Comment by AndreKR** [comment]
I'm also getting the "No CachingProviders have been configured" exception and I can't figure out from this issue what exactly I need to change in my Android app to make it work. I have no idea what "adding a JCache provider on the class path" means.

**Comment by AndreKR** [comment]
> For Android projects, please put the configuration file to `app/main/resources/ical4j.properties`.

I believe that should be `app/src/main/resources/ical4j.properties`.
