### ISSUE TITLE
ICS (With Timezone) Generated with ICal4J does not import into Google Calendar

### ISSUE THREAD

**Issue by kmandeville** [ical4j/ical4j#196]
I have some code that I've inherited that uses ical4j 2.0.0. It adds VTimezone to the ICS set up and this Timezone is adding in RRULE as well as RDATE values to the ICS file (A lot of them). I believe it is this RRULE that is failing importing into google calendar. I don't know why there is an RRULE in the ICS as the event is not a recurring event. 

If I remove the RRULE line(s), then it imports into Google Calendar fine as far as I can tell. 

Any ideas? 

[DoesntImportIntoGoogleCalendar.txt](https://github.com/ical4j/ical4j/files/1408679/DoesntImportIntoGoogleCalendar.txt)

**Comment by benfortuna** [comment]
Hi Kevin,

The recurrence rules are part of the timezone definitions, to indicate switches between standard and daylight-saving time. Your event actually starts around line 160.

You can probably consider modifying the code so it doesn't include the timezone definitions in your output, as Google should probably have its own definition for timezone 'American/Denver'.

Technically the timezone should be included in the file to avoid ambiguity in timezones, but in practice most of the time these definitions are left out and the CUA your are importing to (i.e. google) is left to determine the timezone rules.

**Comment by kmandeville** [comment]
Thanks, I will give this approach a shot. We have other code that is generating ICS files for other things (we're moving away from those) and those files work fine and none of them include the timezone. 

Thanks!
