### ISSUE TITLE
Blocker: NullPointerException in net.fortuna.ical4j.model.TimeZoneRegistryImpl

### ISSUE THREAD

**Issue by mjoaquim12** [ical4j/ical4j#203]
NPE when upgrading from 2.1.1 -> 2.1.3

If custom 'tz.alias' is not provided causes the crash. Earlier version handled all exceptions. New version handles IOException.

**Comment by malkusch** [comment]
Upgrade to 2.1.4. See also #201.

**Comment by mjoaquim12** [comment]
Works after upgrade. Thanks all.
