### ISSUE TITLE
Tzurl.org is down

### ISSUE THREAD

**Issue by ykushch** [ical4j/ical4j#227]
Happens again 😢 Is it possible to fix it again? Guess that we'll need to do a PR 🙂 

It seems that smth is wrong with tzurl.org. curl returns 404.
http://tzurl.org/zoneinfo-outlook - this returns 404 as well. Could you please take a look at it?

https://github.com/ical4j/ical4j/issues/220

**Comment by benfortuna** [comment]
Yeah I think my hosting provider is having issues with the traffic load as they keep disabling the site.

Currently looking to host in cloud infrastructure, cloudfront is the right solution but maybe to expensive. Will advise shortly

**Comment by benfortuna** [comment]
FYI I've split the load across multiple servers to hopefully reduce the load on the hosting. Required some tuning but hopefully is running ok now. Let me know of any issues.
