### ISSUE TITLE
Wrong start date and end date parsed by Windows Outlook 

### ISSUE THREAD

**Issue by nishthaGupta** [ical4j/ical4j#228]
Here's the scenario:
You create an ical object with start date, say, 26th April, 01:00 AM and end date, say, 30th April, 02:00 AM. Now you want this to be a recurring event, recurring every weekday.

DTSTART: 20180425T193000Z
DTEND: 20180425T203000Z
RRULE: RRULE:FREQ=DAILY;UNTIL=20180429T203000Z;BYDAY=MO,TU,WE,TH,FR

Problem is that windows outlook while parsing it in the mail headers, shows it something like this, one date before the actual dates i.e from 25/04/2018 to 29/04/2018 from 01:00 AM to 02:00 AM instead of 26/04/2018 to 30/04/2018 from 01:00 AM to 02:00 AM.

<img width="497" alt="2018-04-18" src="https://user-images.githubusercontent.com/13084151/38918054-35f6d3b4-430a-11e8-8c7e-d9b6b7358553.png">

Similar scenario, in case of a single day event:
DTSTART: 20180425T193000Z
DTEND: 20180425T203000Z
with no RRULE, shows the date in the email headers correctly, i.e. 26/04/2018 from 01:00 AM to 02:00 AM.

**This problem exists only when the start time is in the range of 12:00 AM to 05:00 AM.**

I really don't understand what difference does an RRULE make here.
It works on iMac Outlook perfectly though. Problem is just for windows outlook.

Can someone please suggest what am I missing here?

**Comment by stellingsimon** [comment]
@nishtaGupta: the dates and times you provide in prose, in the iCal excerpt and the screeshot are all completely different from each other, which looks more like a problem in your description than the software (I am just an interested user, not the maintainer). Could you please provide

 1. the full iCal file, 
 2. a screenshot of how this is rendered in Outlook

This way, we might be able to help you spot the cause.

**Comment by nishthaGupta** [comment]
Here are the timings I want to create my ical object for:
Timings: (multi day recurring)
Apr 26, 2018(01:00 AM)-Apr 30, 2018(02:00 AM)

Here is my ical object:

BEGIN:VCALENDAR
PRODID:-//Events Calendar//iCal4j 1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTAMP:20180418T053206Z
DTSTART:20180425T193000Z
DTEND:20180425T203000Z
SUMMARY:Session: Test Outlook module
RRULE:FREQ=DAILY;UNTIL=20180429T203000Z;BYDAY=MO,TU,WE,TH,FR
SEQUENCE:-683863973
UID:session_959350_689704_27756
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=FALSE:MAILTO:nishgupt@adobe.com
LOCATION:XYZ
ORGANIZER:MAILTO:admin@captivateprime.com
DESCRIPTION:Some desc
END:VEVENT
END:VCALENDAR

Here is the screenshot of email I received:
<img width="579" alt="2018-04-18" src="https://user-images.githubusercontent.com/13084151/38913539-e4466bd0-42f8-11e8-8e3c-be5db84a7759.png">

**Comment by douglm** [comment]
Certainly the views look inconsistent but perhaps that's because you 
have the time in UTC.

The actual displayed time will vary depending on the timezone you (or 
the application) are in.

I'd suggest as a first step specifying the timezone in the dtstart and dtend

**Comment by nishthaGupta** [comment]
My receiving timezone is IST.

As per the RFC document, if dtstart and dtend are in UTC, the receiver email box should adjust the date time objects according to their timezones, (UTC+05:30) in this case, and display it.

Specifying timezones with dtstart and dtend are not necessary.

**Comment by stellingsimon** [comment]
@nishthaGupta if your client is in IST, the displayed date seems to be correct. [Check out this timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20180425T193000&p1=tz_ist&p2=1440) which arrives at the same converted value for `20160425T1930Z`. 

If you want the event to start at 19:30 in IST, you have to either specify the IST timezone or remove the `Z` from `DTSTART` and `DTEND` to make the timestamps relative to the client's local timezone.

Either way, this does not seem to be related to the ical4j library, since it's about Outlooks understanding of the iCal format.

**Comment by nishthaGupta** [comment]
For multi-day sessions, having VTIMEZONE is a must in the ical object, Z doesnt work.
The catch here is, standard VTIMEZONE object from ical registry doesnt work well with Outlook. So we need to create VTIMEZONE object from **zoneinfo-outlook** registry.

import net.fortuna.ical4j.zoneinfo.outlook.OutlookTimeZoneRegistryFactory;

final TimeZoneRegistry registry = new OutlookTimeZoneRegistryFactory().createRegistry();

And just include this object in your ical object. It would work well across all email clients.(Gmail, Apple mail as well).
