### ISSUE TITLE
Parsing results in wrong time when VTIMEZONE does only contain DAYLIGHT (and no STANDARD)

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#230]
(Occurs on Android 8 Java and OpenJDK 11)

If this file is parsed:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:20180325T030000
TZNAME:CEST
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:only-dst@example.com 
DTSTAMP:20180329T084939Z
DTSTART;TZID=Europe/Berlin:20180403T090000
DTEND;TZID=Europe/Berlin:20180403T101500
SUMMARY:Sample Event
CREATED:20180329T084939Z
LAST-MODIFIED:20180329T084939Z
END:VEVENT
END:VCALENDAR
```

with this code:

        javaClass.classLoader.getResourceAsStream("dst-only-vtimezone.ics").use {
            val ical = CalendarBuilder().build(it)
            val vTZ = ical.getComponent(VTimeZone.VTIMEZONE) as VTimeZone

            assertEquals("Europe/Berlin", vTZ.timeZoneId.value)
            assertEquals(vTZ.observances.first(), vTZ.getApplicableObservance(Date("20180403")))

            val vEvent = ical.getComponent(VEvent.VEVENT) as VEvent
            val start = vEvent.startDate
            assertEquals(vTZ, start.timeZone.vTimeZone)
            assertEquals(1522738800000L, start.date.time)
        }

the test fails. `start.date` is always `20180402T230000` (`start.date.time = 1522702800000L`) instead of `20180403T090000` (`start.date.time = 1522738800000L`).

When the `VTIMEZONE` is edited so there's a `STANDARD` component, it works (even if it does not apply, I have set it to 2020 here):

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:20180325T030000
TZNAME:CEST
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:20200325T030000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:only-dst@example.com 
DTSTAMP:20180329T084939Z
DTSTART;TZID=Europe/Berlin:20180403T090000
DTEND;TZID=Europe/Berlin:20180403T101500
SUMMARY:Sample Event
CREATED:20180329T084939Z
LAST-MODIFIED:20180329T084939Z
END:VEVENT
END:VCALENDAR
```

results in dtStart = 20180403T090000 Europe/Berlin (UNIX time 1522702800000), as expected.

**Comment by rfc2822** [comment]
Is there any way I can help in debugging that? It seems that Google Calendar now generates such `VTIMEZONE`s without `STANDARD` by default, so this happens quite often.

**Comment by rfc2822** [comment]
RFC 5545:

       timezonec  = "BEGIN" ":" "VTIMEZONE" CRLF
       …
                    ; One of 'standardc' or 'daylightc' MUST occur   // ← "or"
                    ; and each MAY occur more than once.
                    ;
                    standardc / daylightc /

And:

      The "VTIMEZONE" calendar component MUST include the "TZID"
      property and at least one definition of a "STANDARD" or "DAYLIGHT"
      sub-component.  The "STANDARD" or "DAYLIGHT" sub-component MUST
      include the "DTSTART", "TZOFFSETFROM", and "TZOFFSETTO"
      properties.

So, it seems to be valid.

**Comment by benfortuna** [comment]
Just released ical4j 2.2.5 with a potential fix for this. Appreciate any feedback/confirmation of this fix. Many thanks.

**Comment by rfc2822** [comment]
Thank you very much! Will test it very soon :)

**Comment by rfc2822** [comment]
Seems to work as expected! Thanks again

**Comment by kevinstier** [comment]
I'm experiencing the same issue with ical4j 3.0.7

**Comment by benfortuna** [comment]
Apologies I thought I had also released in 3.x branch. Will make a release including the fix shortly.

**Comment by jamie88xia** [comment]
@benfortuna I think I'm experiencing this issue again on `3.2.11`
