### ISSUE TITLE
Moscow time zone changed

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#24]
Recently, the Moscow time zone has changed which is not yet reflected in iCal4j (causing https://github.com/bitfireAT/davdroid/issues/379). I think it would be wise to re-import all time zones again?

**Comment by benfortuna** [comment]
I have just updated the tzdata sourced from the tzurl.org site to tzdata2014j. That should fix the immediate problem for clients that enable tz definition updates from the tzurl.org site (which is default behaviour).
