### ISSUE TITLE
Migrate custom date objects and logic to Java 8's Date / Time API

### ISSUE THREAD

**Issue by geofflittle** [ical4j/ical4j#242]
Rather than using the custom-rolled `DateTime`, `Period`, `Dur`, etc. objects, migrate to using Java 8's Date / Time API (`Instant`, `Period`, `Duration`, etc.).

**Comment by benfortuna** [comment]
Duplicates #62

**Comment by benfortuna** [comment]
Dur has been replaced with Duration/Period. ical4j Period has different meaning to Java Period so still required.

**Comment by benfortuna** [comment]
Reference for mapping legacy code: https://docs.oracle.com/javase/tutorial/datetime/iso/legacy.html

**Comment by benfortuna** [comment]
Migration to new date/time API will be an extensive project and will likely see a number of alpha releases prior to completion (propose to use 3.1.x release versioning before final release of 4.x).

Points to note as part of migration:

* Properties that support dates can typically switch between DATE/DATE-TIME values via changing the Value parameter. To support this we require a class to encapsulate a Temporal (date) value and a format flag to indicate the external representation. Propose `TemporalAdapter` to support parsing/formatting Temporal values
* Some properties require UTC-based DATE-TIME values. For these we use generics to enforce `Instant` as the Temporal type such that local/zone-based values aren't permitted.
* For classes supporting data types/logic (e.g. `Recur`) we should use generics where possible to support applicable Temporal types (i.e. `Instant` = UTC time, `OffsetDateTime` = zone-based time without DST rules, etc., `ZonedDateTime` = DST rules, `LocalDate` = date-only values)

**Comment by jodastephen** [comment]
If you have any specific classes you'd like to break out and see added to ThreeTen-Extra, I'm happy to consider each idea on its merit. For example, a `DateOptionalTime` class might be a possible addition.

Also wanted to note the classes `ZoneOffsetTransition` and `ZoneOffsetTransitionRule` which provide the underlying rules for time zones (in case you hadn't spotted them).

**Comment by jodastephen** [comment]
For `ZoneId`, the Javadoc indicates the approach you should take: "The recommended format for region IDs from groups other than TZDB is 'group~region'". ie. you should create IDs of the form "iCal~encodedId". And yes, this does require the iCal time-zone identifier to be encoded so it matches the regex `[A-Za-z][A-Za-z0-9~/._+-]+`. I'm sure its possible to devise a suitable encoding scheme, such as using +XX to represent any ASCII value, eg +20 to represent  a space.

    "Canberra, Melbourne, Sydney" -> "iCal~Canberra+2C+20Melbourne+2C+20Sydney"

Note that you will also need an instance of `ZoneRulesProvider` to make the IDs available for lookup. Thus, another option is to have a bi-directional hashmap of iCal name to Java name, allowing the Java name to be more friendly and still providing a mechanism to get the iCal name back again during the lifetime of the JVM.

    "Canberra, Melbourne, Sydney" -> "iCal~Canberra_Melbourne_Sydney"

**Comment by benfortuna** [comment]
Hi Stephen, thanks for the prompt follow up.

As you suggest an encoding scheme is probably the right approach. So the overall solution would be something like this:

* ical4j bundles VTIMEZONE definitions generated from the IANA tzdb data. These are used to produce ZoneRules for well-known tz ids that are provided via a custom ZoneRulesProvider
* ical4j also includes an alias file generated from IANA tzdb data, that maps older zone ids to current ids. These aliases are used with `ZoneId.of(zoneId, aliases)`
* additional timezone definitions may be included in parsed icalendar files, in which case the id will be encoded (to replace spaces and forward slash prefix) and registered with the ZoneRulesProvider 

Once the implementation is complete I'll see if we can provide any further suggestions for threeten-extra (note that we already make use of the `Interval` class to calculate date ranges).

https://github.com/ical4j/ical4j/tree/feature/jsr-310-localdate

**Comment by benfortuna** [comment]
v4 now in beta.
