### ISSUE TITLE
ical4j 3.0.0 doesn't work on Android <7.0 because of java.util.Optional usage

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#246]
ical4j 3.0.0 uses Java 8 [java.util.Optional](https://developer.android.com/reference/java/util/Optional), which is under Android available since API level 24 (= Android 7.0).

I just wanted to note that ical4j 3.0.0 is therefore not usable on Android versions below 7.0.

On Android, [Java 8 language features like Lambda can be used with lower SDK versions](https://developer.android.com/studio/write/java8-support), but Java 8 APIs like Optional require Android 7.0.

So while this may be intentional, I suggest to

* clarify whether ical4j requires only Android 8 language features (makes it usable on Android < 7.0) or also Android 8 APIs (would require Android 7.0+),
* use something like Guava's Optional instead

**Comment by benfortuna** [comment]
The issue of Android compatibility for release 3.0.0 was also raised in issue #209.

I suspect this issue may go beyond the use of java.util.Optional, as there are also other Java 8 features such as lambda expressions in v3.0.0.

I understand the challenges involved when third-party libraries change the minimum Java requirements, so for now I'll be making efforts to maintain the 2.x branch alongside 3.x.

One reason for moving to Java 8 was to fully support the new date/time API, and those changes I don't plan to backport to 2.x, but happy to accept contributions along similar lines.

**Comment by rfc2822** [comment]
I see, thanks for the information!

So I'd appreciate if you could maintain 2.x, too, but I understand that it can't be done forever.

As soon as we (DAVdroid) have to switch to ical4j 3.x, we will need to raise the minimum API level to 26 (Android 7) – at some day, this will be reasonable. At the moment, we have about 7 % Android 4/5 and 16 % Android 6 …
