### ISSUE TITLE
ical4j.properties in Android Studio/Gradle

### ISSUE THREAD

**Issue by gbero** [ical4j/ical4j#25]
Hi,

I'm not able to make ical4j find my ical4j.properties.

I've tried to put it at several places : 

* src/main/
* src/main/java/
* src/main/java/com/blabla/myapp/

but always end up with "I/Configurator﹕ ical4j.properties not found."

Has anyone succeed in doing this ?

Thanks in advance,

**Comment by benfortuna** [comment]
Did you try in src/main/resources ? It may depend on your build tool but that is a common standard.

**Comment by gbero** [comment]
Unfortunately still not working. I also tried src/main/assets

Maybe Proguard is removing the properties file ?

2015-01-05 12:30 GMT+00:00 Ben Fortuna <notifications@github.com>:

**Comment by rfc2822** [comment]
I have now just put

```
static {
		CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_UNFOLDING, true);
		CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_PARSING, true);
		CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_OUTLOOK_COMPATIBILITY, true);
	}
```

into my parsing class so that I'm not dependent of file configuration anymore.

**Comment by gbero** [comment]
Thanks, I'll do it like that :+1:

**Comment by nguyenmike** [comment]
thanks.
it 's worked.
