### ISSUE TITLE
Problem on Parsing vCards with empty addresses

### ISSUE THREAD

**Issue by SteveW94** [ical4j/ical4j#252]
Hi,

ical4j-vcard refuse to parse vCards with empty address blocks like this one.

ADR;TYPE=WORK:;;;;;;;

But outlook exports it just this way, and it seems to fit the vCard specs.
Is there some way, to get sth. like this parsed?

Thanks :)

**Comment by benfortuna** [comment]
Hi Steve,

I've just released a fix that should hopefully resolve the issue. 

Release 1.0.2 should be available shortly.

Let me know if you see any further issues. Thanks.

**Comment by SteveW94** [comment]
Hi,

thanks for the fast fix!
I figured out, that the "RELAXED_PARSING" flag also does the job in the 1.0.1 release.

I also would've two Questions...this may be the wrong spot for this, but maybe you could help here too, as it might not be worth a new Issue.
I developed my stuff based on the 2.0.0 Release of ical4j and the 0.9.4.3 Version of the Connector and would like to upgrade to the latest versions of both.
During this I encountered two Problems:

1. The 3.0.0 Release of ical4j seems to change the way UIDs are generated. I couldn't figure out what will be the correct replacement for sth like this:

                UidGenerator ug = new UidGenerator("1");
		event.getProperties().add(ug.generateUid());

2. The way the Connector works seems also changed. I searched for a new documentation but found none. The following line I use runs into a "NoSuchMethodException" in the newest Release.

CardDavStore store = new CardDavStore("Steves Store", url, new GenericCardDavPathResolver());

Did the way of creating the store change?


I would be very grateful for some help here.

Thanks :)

**Comment by benfortuna** [comment]
Apologies for delayed response.

1. The uid generator has changed name to FixedUidGenerator. Brief post about it here:

http://ical4j.github.io/2017/11/17/generating-uids.html

2. I need to review connector code as it may have been broken with recent changes. Please raise a new issue in the connector repo for tracking.

**Comment by benfortuna** [comment]
Closing issue as fixed. Feel free to reopen if still a concern.
