### ISSUE TITLE
XProperty as Duration

### ISSUE THREAD

**Issue by gbero** [ical4j/ical4j#26]
Hi,

I'd like to parse a duration field i.e : "PT30M" stored in a XProperty but : 

> java.lang.ClassCastException: net.fortuna.ical4j.model.property.XProperty cannot be cast to net.fortuna.ical4j.model.property.Duration 

which makes sense because they both extends from Property...

**Comment by benfortuna** [comment]
The solution is to write your own custom property class and inject it into the service loader via META-INF/services/net.fortuna.ical4j.model.PropertyFactory. For example:

https://github.com/ical4j/ical4j-extensions/blob/master/src/main/resources/META-INF/services/net.fortuna.ical4j.model.PropertyFactory

For your property implementation you could start by copying (or extending) the [Duration](https://github.com/ical4j/ical4j/blob/master/src/main/java/net/fortuna/ical4j/model/property/Duration.java) class, and essentially just define a new factory implementation.

If the property is a "standard" custom property you could also consider forking the ical4j-extensions repository and create a pull request back to the main repo.

regards,
ben

**Comment by gbero** [comment]
Thanks for your answer!
