### ISSUE TITLE
Infinite loop parsing malformed ical

### ISSUE THREAD

**Issue by jbflanigan** [ical4j/ical4j#261]
**Describe the bug**
When invalid input is passed into CalendarBuilder() it is possible to enter an infinite loop. This is problematic because the loop consumes 100% CPU and causes loss of service for other applications running on the same host.

**To Reproduce**
Run the following unit test and observe that it spins indefinitely. The problem is created by the stray CRLF on the last line. Removing these characters avoids the problem, however that is impractical for production servers which receive input from arbitrary hosts - the parser should avoid this looping condition.

```
    @Test(expectedExceptions = ParserException.class)
    public void testLoopingIcsParse() throws Exception {
        String badIcs =
                "BEGIN:VCALENDAR\r\n" +
                "BEGIN:VEVENT\r\n" +
                "DTSTART:20180915T130000\r\n" +
                "DTEND:20180918T120000\r\n" +
                "LOCATION:somewhere\r\n" +
                "SUMMARY:Reservation 1234\r\n";

        new CalendarBuilder().build(new ByteArrayInputStream(badIcs.getBytes("utf-8")));
    }
```

**Expected behavior**
A ParserException should be thrown since the input is invalid. A loop should be avoided and the CPU should not reach 100% utilization.

**Environment (please complete the following information):**
 Reproduced on Linux and Mac with Java 8. Reproduces across all ical4j releases including 2.0.2, 2.0.5, 2.1.5, 3.0.1.

**Comment by benfortuna** [comment]
Fix in this PR: #267

**Comment by jbflanigan** [comment]
@benfortuna - would it be possible to make a maintenance release for the 2.2.x branch which includes this fix? 

I'm attempting to upgrade to 3.0.5 (which is where I believe this fix appears - I don't think it made it into 2.2.3), but I'm running into a bunch of new issues with recurrence rules and timezones that are blocking me. I'm going to report the issues as I narrow them down to reproducible test cases, but in the meantime it would be awesome if we could get this fix into our product. Thanks!

**Comment by benfortuna** [comment]
Fix applied to 2.x branch, will be included in next release.
