### ISSUE TITLE
Microsoft Time Zone Index not supported

### ISSUE THREAD

**Issue by rotzbouw** [ical4j/ical4j#262]
An .ics file containing timezone information such as

> BEGIN:VTIMEZONE
> TZID:W. Europe Standard Time
> BEGIN:STANDARD
> DTSTART:16010101T030000
> TZOFFSETFROM:+0200
> TZOFFSETTO:+0100
> RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
> END:STANDARD
> BEGIN:DAYLIGHT
> DTSTART:16010101T020000
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0200
> RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
> END:DAYLIGHT
> END:VTIMEZONE

will throw 

> java.time.DateTimeException: Invalid ID for region-based ZoneId, invalid format: W. Europe Standard Time

due to "W. Europe Standard Time" not being recognised when calling toZoneId() on an ical4j TimeZone object.

**Expected behavior**
I would expect ical4j to include the Microsoft mapping of time zones (cf. https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11) or https://support.microsoft.com/en-gb/help/973627/microsoft-time-zone-index-values)

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version 8 (OpenJDK)

**Comment by benfortuna** [comment]
I think we can add these mapping to the alias configuration.

I'll let you know how I go.

**Comment by benfortuna** [comment]
In fact on review of your requirement I think there already is support for MS timezones, but you need to transform the calendar to standard timezone IDs first. e.g.

```
RuleManager.applyTo(event.getProperty(Property.TZID));
```

Hopefully after that you will be able to successfully call `toZoneId()`

**Comment by alecalanis** [comment]
any update here? :)

**Comment by benfortuna** [comment]
I've just added the MS timezones to the map of aliases used to translate to known TZ identifiers. This will be available in the next release on both current streams (v3 and v4).

Note also if you find some aliases are still not recognized you can define your own `tz.alias` file in the classpath that will also be loaded into the aliases map.

**Comment by benfortuna** [comment]
implemented properly in v4
