### ISSUE TITLE
DST related issues

### ISSUE THREAD

**Issue by hangsu-ma** [ical4j/ical4j#268]
**Describe the bug**
I am using ical4j for a while now, it's a great lib and works perfectly for me.
Until I am caught up by a wrong date couple days ago, did some digging in the code, and looks like DST is wrong for "Europe/Dublin" timezone, (maybe it's also happening on other timezones as well.)
See details in code example below, i am using JDK SimpleTimeZone to compare

**To Reproduce**

According to [Google](
https://www.google.ie/search?rlz=1C1CHBF_enIE723IE723&q=ireland+daylight+saving&spell=1&sa=X&ved=0ahUKEwj_zdL0mK_eAhUPa1AKHdmCA_gQBQgpKAA&biw=1745&bih=991)

> Daylight saving time 2018 in Republic of Ireland began at 01:00 on
Sunday, 25 March
and ended at 02:00 on
Sunday, 28 October
All times are in Ireland Time.

This means 20181016T040000 is DST
and 20181116T040000 is STANDARD
which match the JDK result below, but ical4j is the other way around and causing the offset to be wrong as well, which can cause an exception during parsing and swallowed, then a wrong date is returned. (this is what got me):

        `TimeZone ical4jtz = new CalendarBuilder().getRegistry().getTimeZone("Europe/Dublin")
        TimeZone jdktz = TimeZone.getTimeZone("Europe/Dublin")

        println "2018-10-16 ms: "+ new DateTime("20181016T040000").getTime()

        println "ical4j offset "+ical4jtz.getOffset(1539658800000)
        println "ical4j isDaylight: " + ical4jtz.inDaylightTime(new Date(1539658800000))
        println "ical4j rawoffset " + ical4jtz.getRawOffset()
        println ical4jtz.getDSTSavings()

        println "jdk offset "+jdktz.getOffset(1539658800000)
        println "jdk isDaylight: " + jdktz.inDaylightTime(new Date(1539658800000))
        println "jdk rawoffset " + jdktz.getRawOffset()
        println jdktz.getDSTSavings()

        println "2018-11-16 ms: "+ new DateTime("20181116T040000").getTime()

        println "ical4j offset " + ical4jtz.getOffset(1542340800000)
        println "ical4j isDaylight: " + ical4jtz.inDaylightTime(new Date(1542340800000))
        println "ical4j rawoffset " + ical4jtz.getRawOffset()
        println ical4jtz.getDSTSavings()

        println "jdk offset "+jdktz.getOffset(1542340800000)
        println "jdk isDaylight: " + jdktz.inDaylightTime(new Date(1542340800000))
        println "jdk rawoffset " + jdktz.getRawOffset()
        println jdktz.getDSTSavings()

        println "parsing result is wrong: " + new DateTime("20181116T040000",ical4jtz)

        DateFormat format = new SimpleDateFormat("yyyyMMdd'T'HHmmss")
        format.setLenient(false)
        format.setTimeZone(ical4jtz)
        format.parse("20181116T040000")`

Test Result is:
>2018-10-16 ms: 1539658800000
ical4j offset 3600000
ical4j isDaylight: false
ical4j rawoffset 3600000
3600000
jdk offset 3600000
jdk isDaylight: true
jdk rawoffset 0
3600000
2018-11-16 ms: 1542340800000
ical4j offset 3600000
ical4j isDaylight: true
ical4j rawoffset 3600000
3600000
jdk offset 0
jdk isDaylight: false
jdk rawoffset 0
3600000
parsing result is wrong: 20181115T230000
Exception in thread "main" java.text.ParseException: Unparseable date: "20181116T040000"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at java_text_DateFormat$parse$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

**Additional context**
tested in both 3.0.1 and 2.X
I dug into code and the problem seems to be in the observances loaded by TimeZoneLoader from Dublin.ics, if you can point me to some documentation especially the onset stuff, i might be able to dug further.

**Comment by benfortuna** [comment]
I think this is related to the known issue with negative offsets recently introduced for specifying the Dublin timezone rules: #237

Basically the issue is that the issues of timezone data (https://www.iana.org/time-zones) recently changed the Europe/Dublin definition such that daylight savings transitions from GMT+1 to GMT.

This has causes some issues with Java 8 that I think are yet to be resolved.

In the meantime if you can use the older timezone definitions (prior to this change) it could be a temporary workaround..

**Comment by hangsu-ma** [comment]
Hi Ben 
Thanks for looking into this. 
I were actually on JDK 10. I thought the time zone data is loaded from the zoneinfo ics files included in the jar file. Can you let me know how to change the time zone data?

**Comment by benfortuna** [comment]
Timezone definitions are loaded from the zoninfo data, but we use the Java date class to calculate offsets.

I think Java 10 may have the same issue, will try to find a reference.

There is a possible workaround to use a backwards-compatible version of zoneinfo, which I am investigating.

Longer term I hope migration to the new date/time API might also fix a lot of things.

**Comment by karthikvelusamy** [comment]
Hi Ben, If we are in ical4j 1.0.6 and setting the property "net.fortuna.ical4j.timezone.update.enabled=false" will help not to take latest zoneinfo? will that resolve this issue until the new zoneinfo with the fix is released?

**Comment by benfortuna** [comment]
Yes it should, but then I'm not sure how old the included zoneinfo data with 1.0.6 is.

I've actually just published a new zoneinfo dataset on tzurl.org, which I am hoping will fix this problem. If you could try again (with update.enabled=true) would be much appreciated to confirm if it is fixed or not. Many thanks.

**Comment by karthikvelusamy** [comment]
Hi Ben, looks like new ZoneInfo fixed the issue. we are able to test and looks good
