### ISSUE TITLE
Support for X-WR-TIMEZONE?

### ISSUE THREAD

**Issue by davidgubler** [ical4j/ical4j#27]
Hi all,

We're using ical4j (currently 1.0.5.2) to read any sorts of feeds from all over the internet. A problem we found is with feeds that have dates in local time, but no proper VTIMEZONE definition. Those feeds typically use the X-WR-TIMEZONE header to specifiy which time zone must be used to interpret the local times.

There is an article explaining the situation here: http://blog.jonudell.net/2011/10/17/x-wr-timezone-considered-harmful/

Now I do not entirely understand the code of ical4j, but as far as I can tell it does not care about the X-WR-TIMEZONE header at all, but falls back to the machine's local time zone (java.util.TimeZone.getDefault()) instead. This is consistent with what our experiments with real feed data showed us.

Now since the library runs on a server and our users use all sorts of time zones in the feeds and to view the feed data, the fall-back to the server's time zone is just plain wrong in our case. I imagine that interpreting the X-WR-TIMEZONE header as an Olson DB name and trying to convert it to a java.util.TimeZone should not be too difficult to do. 

Am I right? If yes, is support for X-WR-TIMEZONE planned? If not, consider this to be a feature request :)

Thank you!

**Comment by benfortuna** [comment]
Hi David,

I think we should be able support this property (most likely via the ical4j-extensions project). The difficulty lies in creating a mechanism whereby ical4j uses a different default timezone to the JVM. The easiest solution would be to just set the default JVM timezone from this property, but that may have unintended effects, especially when handling multiple iCalendar objects concurrently.

This problem may be simplified by the jsr-310 implementation, but that is still a while off.

**Comment by davidgubler** [comment]
Thanks for your response. Indeed, changing the JVM's default time zone is not an option for us, because we do handle feeds in parallel.

**Comment by magneticflux-** [comment]
@benfortuna Is this feature included in the ical4j-extensions project? I need it to parse a set of ical files that all use the same timezone. If there is no support, is there a workaround for this instead?

**Comment by benfortuna** [comment]
Hi Mitchell, I think the extension project will be able to parse this property but we still don't have the code to use the value as the default timezone. As mentioned we probably will support this when we move to the new date/time API.

Add a workaround I think you'll need to write some code that can extract the default timezone from the property and update each of the enclosed events, etc. to use it. Not ideal and possibly flawed as I haven't tried it myself, but as it is ical4j only supports the default JVM timezone or that specified in an event, etc.

**Comment by magneticflux-** [comment]
@benfortuna Thanks, I appreciate the prompt response. I'll try that and update if it works or not.
