### ISSUE TITLE
iCal4j unable to import iCalendar ics file to Google Calendar

### ISSUE THREAD

**Issue by JordySwinnenPXL** [ical4j/ical4j#271]
I am attempting to dynamically generate iCalendar events for users to import into their personal agenda's. Unfortunately when i try to import the generated file in Google Calendar i get an error message similair to "0/0 appointments imported, cannot process ics/csv file" (translated).

Formatting example generated iCalendar file:

```
    BEGIN:VCALENDAR
    PRODID:-//Google Inc//Google Calendar 70.9054//EN
    CALSCALE:GREGORIAN
    VERSION:2.0
    METHOD:REQUEST
    BEGIN:VEVENT
    DTSTAMP:20181116T132417Z
    DTSTART:20181216T150000
    SUMMARY:introduction interview
    UID:e6e9e9ff-dec1-49d6-ac9d-4fd385362ee4
    STATUS:CONFIRMED
    TRANSP:OPAQUE
    SEQUENCE:0
    ORGANIZER;CN=Organiser Name:mailto:organiser@gmail.be
    ATTENDEE;ROLE=REQ-PARTICIPANT;CN=Attendee Name;CUTYPE=INDIVIDUAL;RSVP=TRU
     E;X-NUM_GUESTS=0;PARTSTAT=NEEDS-ACTION:mailto:attendee@hotmail.com
    END:VEVENT
    END:VCALENDAR
```

[My iCal4j iCalendar file builder code](https://gist.github.com/JordySwinnenPXL/28dff5c8576a74e330575d6c9c3cc4fb)

I already tried validators such as [this one](https://icalendar.org/validator.html), but my file seems to be valid.

Apologies if this may be the wrong place to ask.

**Comment by fatkudu** [comment]
Noticed that there is no DTEND, or DURATION (1 or the other is normally present, DTEND more usual)
Specifying one of those might move things forward for you.
