### ISSUE TITLE
Replace Dur with TemporalAmount

### ISSUE THREAD

**Issue by benfortuna** [ical4j/ical4j#273]
Start using new date/time API. Dur can be replaced by Duration/Period with some caveats:

* Icalendar doesn't support years/months representation and Java doesn't support weeks. Need to provide output translation
* TemporalAmount doesn't implement comparable so require a comparator

**Comment by benfortuna** [comment]
Period cannot be converted to Duration so unable to provide unified TemporalAmount comparator

**Comment by benfortuna** [comment]
Unified comparator implemented to be "good enough" by ordering date-based TemporalAmount before time-based

**Comment by benfortuna** [comment]
Adapter implemented to manage consistent use of date-based vs time-based units

**Comment by benfortuna** [comment]
Provide TemporalAmountFactory for backwards compatibility with Dur

**Comment by kaefxx** [comment]
> * Icalendar doesn't support years/months representation and Java doesn't support weeks. Need to provide output translation
How should be number of weeks properly extracted from TemporalAmount and then modified?

**Comment by bannmann** [comment]
For the record, there is also [PeriodDuration](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/PeriodDuration.html) from the author of the Java 8 date/time API. Using it may simplify ical4j.
