### ISSUE TITLE
can't use ical4j within a Java module

### ISSUE THREAD

**Issue by pinhead84** [ical4j/ical4j#279]
I can't use ical4j (neither 2.2.0 nor 3.0.1) within a Java module (introduced with Java 9). The library is loaded within my applications `module-info.java` like this:

```java
module my.app {
    requires ical4j;
}
```

But the Java compiler is not able to find the module by this name and shows something like:

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project My-App: Compilation failure
> [ERROR] .../module-info.java:[19,14] **module not found: ical4j**

It seems, that your outdated version of Groovy is the root of the problem (see [this issue](https://issues.apache.org/jira/browse/GROOVY-8480) on their bug tracker).

After updating to the latest version of Groovy and moving 

`src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule`

to

`src/main/resources/META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule`

the problem seems to be fixed and the Java compiler does not complain anymore about an unknown module name. I would provide a pull request to fix this issue, if you like.

**Comment by benfortuna** [comment]
Thanks for the feedback, if you can provide a PR that would be very much appreciated.

**Comment by benfortuna** [comment]
Fix included in release ical4j-3.0.3
