### ISSUE TITLE
Recur.java setters?

### ISSUE THREAD

**Issue by eddnav** [ical4j/ical4j#30]
I have an application in which I'm forced to recreate Recur objects every time a recurrence string changes instead of modifying a single Recur object. This is due to the fact that Recur doesn't expose accessors to all its properties. It's there a reason behind this?

If I created a pull request for this feature would it be considered?

**Comment by eddnav** [comment]
Closing this. For future reference I had forgotten about list mutability. You can just get the list of the Recur object and modify it.

**Comment by benfortuna** [comment]
I agree it is a little inconsistent, however I am inclined to move more in the direction of immutable objects (i.e. removing setters) and relying on builders to create copies, etc. I think this leads to less bugs overall, however I won't be changing it for now.
