### ISSUE TITLE
Missing property exposure breaks applications downstream

### ISSUE THREAD

**Issue by Tie-fighter** [ical4j/ical4j#300]
I was wondering if you folks could help us with this.
Apparently not all properties get exposed, breaking stuff downstream :/

[Full thread](https://github.com/tasks/tasks/issues/635)

**Comment by Tie-fighter** [comment]
Mea culpa.

**Comment by benfortuna** [comment]
Note we have RFC 7986 in the backlog:

https://github.com/ical4j/ical4j/issues/141

**Comment by Tie-fighter** [comment]
Thank you, @benfortuna, I saw it but didn't understand.
How will this influence the current situation with the CATEGORIES-property?

**Comment by benfortuna** [comment]
I believe it allows the CATEGORIES property specified for the whole calendar object rather than individual components (e.g. VEVENT, etc)
