### ISSUE TITLE
DTSTAMP compatibility: accept erroneous TZID parameters

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#303]
Hello,

Many iCalendars out there (especially Webcal feeds generated by PHP scripts etc.) contain `DTSTAMP` values with `TZID` parameter like that:

```
DTSTAMP;TZID=Europe/Prague:20190104T155229 
```

According to the iCalendar RFC, this is invalid and it causes ical4j to fail with:

    Caused by: net.fortuna.ical4j.data.ParserException: Error at line xx:Cannot set timezone for UTC properties
        at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:158)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:198)
        at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:178) 
        at at.bitfire.ical4android.Event$Companion.fromReader(Event.kt:78)
        at ...
    Caused by: java.lang.UnsupportedOperationException: Cannot set timezone for UTC properties
        at net.fortuna.ical4j.model.property.UtcProperty.setTimeZone(UtcProperty.java:95)
        at net.fortuna.ical4j.data.CalendarBuilder.updateTimeZone(CalendarBuilder.java:353)
        at net.fortuna.ical4j.data.CalendarBuilder.access$300(CalendarBuilder.java:68)
        at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(CalendarBuilder.java:278)
        at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:367)

While this is technically correct, it [often causes compability problems](https://forums.bitfire.at/search?term=dtstamp&in=posts&matchWords=all&sortBy=relevance&sortDirection=desc&showAs=posts).

Would it be possible to accept time values with time zone when `ical4j.parsing.relaxed` is true?

**Comment by benfortuna** [comment]
The thing about DTSTAMP is that the RFC specifically states it should be UTC time, presumably because it avoids ambiguity when dealing with historical timezone definitions.

As such ical4j implements as a UTC property that can't have a timezone even in relaxed mode.

What we could explore is transforming the input calendar to convert the timezone-based value to a UTC value when parsing.

**Comment by rfc2822** [comment]
> The thing about DTSTAMP is that the RFC specifically states it should be UTC time, presumably because it avoids ambiguity when dealing with historical timezone definitions.

I think it might also be helpful for servers which use the `DTSTAMP` to determine when events have been updated. To convert the `DTSTAMP` into a last-modified timestamp reliably, there should be no time zones to consider.

But whatever the reasons behind this are: Although I don't like it, there are many iCalendars out there which contain `DTSTAMP` with `TZID`, and parsing completely fails for all those events.

> As such ical4j implements as a UTC property that can't have a timezone even in relaxed mode.

What about:

1. Allowing time zones for _all_ UTC properties in relaxed mode?
1. At least ignoring invalid UTC properties in relaxed mode? Actually I don't need the `DTSTAMP` value, but the parser throws an exception, so that the whole iCalendar can't be used, which really causes problems…

**Comment by rfc2822** [comment]
[The same problem often occurs for the `COMPLETED` property.](https://forums.bitfire.at/post/9700)

Would it be possible to enable timezone parsing for all `UtcProperty`s like `DateProperty`s do? Of course, these properties should only be written as UTC, but there are really many broken implementations out there, which makes it hard to use ical4j for real-world iCalendars (especially because the whole iCalendar is not parsed when there's only a single `DTSTAMP`/`COMPLETED` with `TZID`).

Maybe `UtcProperty` could be derived from `DateProperty` in a way that it converts input values to UTC automatically?

**Comment by benfortuna** [comment]
I guess the easiest approach would be to modify the `ContentHandlerImpl.updateTimeZone()` method to ignore UtcProperty when in relaxed mode. However this would just ignore the timezone, which will probably mean the timestamps are wrong.. but at least the calendar would parse.

It might be possible to improve the logic to detect UtcProperty and perform the conversion. The reason I hesitate is that I'm currently focusing on replacing the Java date classes with the new date/time API, so any work on this in the master branch would need to be redone. 

However I think you are more interested in the 2.x maintenance branch so probably still worth doing.

**Comment by benfortuna** [comment]
@rfc2822 Apologies for the delay, I've just release 2.2.4 that includes ability to set timezone on Utc properties when relaxed parsing is enabled.

Note that this fix probably won't be merged to the 3.x branch as I am currently working on replacing date/time classes with the new Java date/time API, so we'll probably consider doing this differently.

Let me know if it fixes the issue.

**Comment by rfc2822** [comment]
Thank you very much! I will post again after trying whether this solves the problem (but it looks good :)).
