### ISSUE TITLE
TZID of DTSTART completely ignored when VALUE=DATE

### ISSUE THREAD

**Issue by atnak** [ical4j/ical4j#31]
#### Summary

`ical4j` seems to completely ignore the `TZID` parameter in `DTSTART` when `VALUE=DATE`.

##### Example .ics file:
https://www.mozilla.org/projects/calendar/caldata/JapanHolidays.ics

##### Example `DTSTART`:
`DTSTART;VALUE=DATE;TZID=/mozilla.org/20070129_1/Asia/Tokyo:20070101`

After parsing, `Period.getStart()` returns `20070101T000000Z`.  Expected is something like `20070101T000000+0900`.

#### More details:

Actually, this behavior is somewhat documented in `DateProperty.java`, as it partially states that time zones are not supported by `ical4j` when `VALUE=DATE` (and effectively, unfortunately, become UTC).

```java
    public void setValue(final String value) throws ParseException {
        // value can be either a date-time or a date..
        if (Value.DATE.equals(getParameter(Parameter.VALUE))) {
            // ensure timezone is null for VALUE=DATE properties..
            updateTimeZone(null);
```

```java
    /**
     * Updates the timezone associated with the property's value. If the specified timezone is equivalent to UTC any
     * existing TZID parameters will be removed. Note that this method is only applicable where the current date is an
     * instance of <code>DateTime</code>. For all other cases an <code>UnsupportedOperationException</code> will be
     * thrown.
     * @param vTimeZone
     */
    private void updateTimeZone(final TimeZone timezone) {
```

**Comment by arnaudq** [comment]
I dont know who generated this file but in general, having a DTSTART with VALUE=DATE and a TZID, while not illegal, does not make much sense.

See http://tools.ietf.org/html/rfc5545#section-3.2.29

<<
The "TZID" property parameter MUST NOT be applied to DATE
      properties and DATE-TIME or TIME properties whose time values are
      specified in UTC.
>>

**Comment by benfortuna** [comment]
Further to what Arnaud said, ideally in ical4j a Date property wouldn't even have a timezone, but due to the limitations of the implementation we set it to UTC by default. Eventually if we can implement the new date/time api (jsr-310) this can hopefully be fixed.

In the meantime though, there is a workaround that may suit you, which is to override the default behaviour and use the local timezone for Date properties. You can enable this by adding the following flag to your ical4j.properties  file:

` net.fortuna.ical4j.timezone.date.floating=true`

**Comment by solomax** [comment]
Actually there is implementation of JSR-310: http://www.threeten.org/
But it is for Java7 .... (which is almost at the EOL)

**Comment by benfortuna** [comment]
Yes we have a branch dedicated to integrating the java 7 backport here:

https://github.com/ical4j/ical4j/tree/jsr-310

It may be quite a challenge, but time-willing we'll make some progress on that soon. Feel free to fork and contribute if you are able.

**Comment by solomax** [comment]
Will try

**Comment by atnak** [comment]
> See http://tools.ietf.org/html/rfc5545#section-3.2.29

Thanks for that, extremely informative.

> Further to what Arnaud said, ideally in ical4j a Date property wouldn't even have a timezone, but due to the limitations of the implementation we set it to UTC by default. Eventually if we can implement the new date/time api (jsr-310) this can hopefully be fixed.

Thanks for the insight.  I'm now more confident about converting `Period.getStart()` into a `LocalDate`.

**Comment by jeff303** [comment]
We are experiencing this problem as well, but in our case, the DTSTART string is generated by ical4j itself.  Working on producing a test case now.

**Comment by NoSubstitute** [comment]
> 
> 
> I dont know who generated this file but in general, having a DTSTART with VALUE=DATE and a TZID, while not illegal, does not make much sense.
> 
> See http://tools.ietf.org/html/rfc5545#section-3.2.29
> 
> <<
> The "TZID" property parameter MUST NOT be applied to DATE
> properties and DATE-TIME or TIME properties whose time values are
> specified in UTC.

I can't find that section in the RFC.

**Comment by NoSubstitute** [comment]
Oh, maybe there was a typo in the URL and you really meant this one?
https://tools.ietf.org/html/rfc5545#section-3.2.19
