### ISSUE TITLE
Tzurl.org is down

### ISSUE THREAD

**Issue by pshsh88** [ical4j/ical4j#318]
Please restore it again.

https://github.com/ical4j/ical4j/issues/220
https://github.com/ical4j/ical4j/issues/227

https://uptime.com/tzurl.org
![image](https://user-images.githubusercontent.com/11333265/55455082-249fbf00-561d-11e9-9bb2-02d21e53ee13.png)

**Comment by Tristan971** [comment]
To be honest, it might be a good thing to make the fetch opt-in as this means hanging apps startup for any user, including potentially in prod?

**Comment by benfortuna** [comment]
Hopefully you'll see tzurl.org back online - it may take some time to propagate DNS changes though.

![image](https://user-images.githubusercontent.com/984966/55475023-85032080-565e-11e9-8cae-f0e3ad6ab8fc.png)

**Comment by benfortuna** [comment]
A brief summary of what happened:

* About a year ago tzurl.org was exceeding capacity of the hosting, so I had to split traffic across two hosts. One host contained a load balancer for routing traffic.
* It seems the host with load balancer was rebooted this morning and it just isn't responding. I tried rebooting but nothing worked.
* So I decided to cutover to a new site I've been working on that should hopefully perform better (and more reliably). The DNS changes are slowly propagating, but so far I don't see many errors.

Please comment here if you see any weird behaviour. The site wasn't fully tested before this unplanned cutover so there might be a couple of bugs.

**Comment by douglm** [comment]
Have you considered supporting tzdist? - RFC 7808?

**Comment by benfortuna** [comment]
Hi Mike, I don't think I was aware of that RFC. 

Will definitely have a look and see if we can support it.

**Comment by douglm** [comment]
Bedework has an implementation - also a client and an implementation of the tz registry for ical4j

**Comment by pshsh88** [comment]
I checked the connection. Thank you. :)

**Comment by sextuple** [comment]
tzurl.org still seems to be down - or rather the two links http://d1iyq9tbp3ab5f.cloudfront.net/zoneinfo and http://d1iyq9tbp3ab5f.cloudfront.net/zoneinfo-outlook.

**Comment by benfortuna** [comment]
The change from Apache httpd to AWS cloudfront means that directory listing no longer works.

I didn't have a chance to find a solution prior to the switch, but if you can raise a new issue with a description of the use-case for directory listing then I'll try to provide a solution.

**Comment by sextuple** [comment]
Thanks.  I have raised a new issue at https://github.com/ical4j/ical4j/issues/322.
