### ISSUE TITLE
java.io.NotSerializableException: net.fortuna.ical4j.model.TemporalAmountAdapter

### ISSUE THREAD

**Issue by EmanueleRossi** [ical4j/ical4j#321]
**Describe the bug**
Trying to serialize a `net.fortuna.ical4j.model.Calendar` object for putting it into an HTTP Session Attribute, but the class `net.fortuna.ical4j.model.TemporalAmountAdapter` doesn't implements Serializable interface. 

**To Reproduce**
1. Try to serialize a `net.fortuna.ical4j.model.Calendar` object.
2. This exception will be thrown:
`Caused by: java.io.NotSerializableException: net.fortuna.ical4j.model.TemporalAmountAdapter
[INFO]  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_202]
[INFO]  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_202]`

**Expected behavior**
Serialization can be done correctly.

**Environment (please complete the following information):**
All Java Versions.

**Comment by benfortuna** [comment]
I've applied a fix as part of #326 that will be included in the next release.
