### ISSUE TITLE
Links on tzurl.org return 404 errors

### ISSUE THREAD

**Issue by sextuple** [ical4j/ical4j#322]
The links to [zoneinfo](http://d1iyq9tbp3ab5f.cloudfront.net/zoneinfo) and [zoneinfo-outlook](http://d1iyq9tbp3ab5f.cloudfront.net/zoneinfo-outlook) on [tzurl.org](http://d1iyq9tbp3ab5f.cloudfront.net/) no longer work and return 404 errors.

I need to be able to (a) find the timezone definitions for a particular timezone (eg Europe/London) and (b) find all the available timezone definitions, so that I can use them in a web based calendar application by including VTIMEZONE components in iCalendar email notifications.

**Comment by sextuple** [comment]
I also need to be update existing timezone definitions which have invalid properties such as

~~~~
TZURL:http://tzurl.org/zoneinfo-outlook/Europe/London
~~~~

**Comment by benfortuna** [comment]
@sextuple what part of `Europe/London` is invalid?

**Comment by sextuple** [comment]
Sorry, you are right, it is not invalid. I thought it was returning a 404 error but on re-testing I see it is not and is returning a valid VTIMEZONE.    So I think the issue is the original one, ie that I need a way of finding all the available timezone definitions.

**Comment by benfortuna** [comment]
I've just updated the cloudfront distribution with index files for each of the directories. Hopefully this will provide a similar behaviour to the previous directory listing support.

http://d1iyq9tbp3ab5f.cloudfront.net/zoneinfo/index.html

**Comment by sextuple** [comment]
Many thanks, that's great.

**Comment by benfortuna** [comment]
Closing as fixed
