### ISSUE TITLE
Calendar Invite with no option to respond to the invite

### ISSUE THREAD

**Issue by nik-birur** [ical4j/ical4j#329]
Hey @benfortuna ,

We have a very weird requirement and we are wondering if you could help us with this. Is there a way to use ical4j to send invites without an option to respond to the invitation? The invite should be displayed as ACCEPTED by default in the user's calendar. Is this even possible?

**Comment by benfortuna** [comment]
I don't believe there is an option for auto-acceptance of invites. It would depend on the user agent (e.g. Outlook, google cal, etc.) and I don't think they have such a feature.

The best place to look at what is possible with iCalendar is the interoperability protocol here:

https://tools.ietf.org/html/rfc5546

The method PUBLISH will allow you to send events without option to respond, but the user must choose to add to their calendar:

https://tools.ietf.org/html/rfc5546#section-3.2.1

Maybe this is sufficient for your use-case?

**Comment by nik-birur** [comment]
Thank you, @benfortuna . We will try this. Appreciate your quick response.
