### ISSUE TITLE
Deprecated interval,until,count,frequency...

### ISSUE THREAD

**Issue by RenHong-HC** [ical4j/ical4j#330]
Hello everyone, I would like to ask a question. I saw that in the 3.0.6 version, the properties of until, interval, and count in Recur are Deprecated, and the comments are: will be removed in a future version to support immutable pattern. Don't you support it? Is there an alternative?

**Comment by benfortuna** [comment]
The actual fields aren't deprecated, but the setter methods are. This is because we now encourage you to use the Recur.Builder class to create new Recur instances:

https://github.com/ical4j/ical4j/blob/develop/src/main/java/net/fortuna/ical4j/model/Recur.java#L1098

e.g.

```
Recur recur = new Recur.Builder().frequency(Frequency.YEARLY).count(-1).interval(2)
                .monthList(new NumberList("1")).dayList(new WeekDayList(SU))
.hourList(new NumberList("8,9")).minuteList(new NumberList("30")).build();
```

**Comment by RenHong-HC** [comment]
> The actual fields aren't deprecated, but the setter methods are. This is because we now encourage you to use the Recur.Builder class to create new Recur instances:
> 
> https://github.com/ical4j/ical4j/blob/develop/src/main/java/net/fortuna/ical4j/model/Recur.java#L1098
> 
> e.g.
> 
> ```
> Recur recur = new Recur.Builder().frequency(Frequency.YEARLY).count(-1).interval(2)
>                 .monthList(new NumberList("1")).dayList(new WeekDayList(SU))
> .hourList(new NumberList("8,9")).minuteList(new NumberList("30")).build();
> ```

thank you very much

**Comment by edwhiting** [comment]
This issue looks fixed to me.  @RenHong-HC are you happy to close this ticket?

**Comment by RenHong-HC** [comment]
> This issue looks fixed to me. @RenHong-HC are you happy to close this ticket?

of course
