### ISSUE TITLE
java.lang.NoClassDefFoundError: net.fortuna.ical4j.data.CalendarBuilder

### ISSUE THREAD

**Issue by tracyis** [ical4j/ical4j#337]
I tried to parse ics file on Android 5.1, but it throws a exception.

ical4j version: 'org.mnode.ical4j:ical4j:3.0.6'
device info: OPPO A37M, Android 5.1,level 22, arm64-v8a
code:`CalendarBuilder().build(FileInputStream(file.absolutePath)
.getComponents<CalendarComponent>(VEVENT)
?.takeIf { it.isNotEmpty() }`

**Comment by benfortuna** [comment]
I'm not sure if ical4j 3.x is compatible with Android. You may want to try the latest 2.x release:

https://github.com/ical4j/ical4j/releases/tag/jdk7_ical4j-2.2.4

**Comment by tracyis** [comment]
> I'm not sure if ical4j 3.x is compatible with Android. You may want to try the latest 2.x release:
> 
> https://github.com/ical4j/ical4j/releases/tag/jdk7_ical4j-2.2.4

it works, thank you very much!
