### ISSUE TITLE
Timezones data update for 1.x

### ISSUE THREAD

**Issue by urusha** [ical4j/ical4j#34]
Please, update timezones data for 1.x branch. It seems https://github.com/ical4j/ical4j/commit/4001177936daefa37ad7d498429928158670a445 could be used for this.
Also, here is the patch for 1.0.6: https://gist.github.com/urusha/591c02512cd0684d48b3#file-0001-updated-zoneinfo-to-tzdata2015c-patch
Thanks!

**Comment by benfortuna** [comment]
I've just released ical4j 1.0.7, which includes the latest timezone definitions.

**Comment by solomax** [comment]
Hello Ben,
can you release 2.x version as well?
