### ISSUE TITLE
Upload SNAPSHOTs of jsr-310-localdate

### ISSUE THREAD

**Issue by mwkroening** [ical4j/ical4j#341]
I would to start using ical4j in my application.

To prevent having to rework the whole thing once #242 is resolved, I would like to suggest uploading SNAPSHOTs of the [jsr-310-localdate](/ical4j/ical4j/tree/feature/jsr-310-localdate) branch to e.g. https://oss.sonatype.org/content/repositories/snapshots/org/mnode/ical4j/.

That way I could already work with the new API more easily than having to build ical4j along my application in CI etc..

What do you think?

**Comment by benfortuna** [comment]
Hi Martin,

That's fine, I can do that. I was planning to release an alpha version once I get all the unit tests passing, but that is taking longer than expected.

I don't believe the API will be changing much more from the current branch.

**Comment by mwkroening** [comment]
Thanks for your fast reply! Sounds very promising!

In the meanwhile I experimented with building the branch myself but I could not `$ ./gradlew compileJava` successfully using Java 8. Are you able to compile on the feature branch?

**Comment by benfortuna** [comment]
I still have a few changes locally I haven't committed yet, I'll try to push them shortly so even if the tests fail it should compile.

**Comment by mwkroening** [comment]
All right. I thought so. Thanks for your work!

**Comment by derTobsch** [comment]
Hey, we also starting to use iCal4j and we also would like to use the 4.x line. Are there any snapshots available?

**Comment by mwkroening** [comment]
FYI: [org.mnode.ical4j : ical4j : 4.0.0-alpha2 - The Central Repository Search Engine](https://search.maven.org/artifact/org.mnode.ical4j/ical4j/4.0.0-alpha2/jar)
