### ISSUE TITLE
Declare stable Java module name

### ISSUE THREAD

**Issue by mwkroening** [ical4j/ical4j#346]
Currently this library does not define a stable Java module name. Thus this automatic module name is derived from it's JAR filename to be `ical4j`.

It would be useful to set a stable automatic module name to what it will eventually be when the library natively supports the JPMS (see #345). `net.fortuna.ical4j` is one possibility but would take ownership of the package of the same name. This would conflict with other projects being subpackages thereof (e.g. `net.fortuna.ical4j.vcard`).

Maybe the best solution would be moving the `net.fortuna.ical4j` package from this project to `net.fortuna.ical4j.core` with the next big version. That way the module name `net.fortuna.ical4j.core` would not conflict with the other projects.

For more details about Java module names see: [sormuras/modules#about-java-module-names](/sormuras/modules#about-java-module-names)

**Comment by mwkroening** [comment]
The stable module name would then be set in the library's `MANIFEST.MF`. See: [Automatic-Module-Name: Calling all Java Library Maintainers](http://branchandbound.net/blog/java/2017/12/automatic-module-name/)

**Comment by benfortuna** [comment]
Changing to core package seems like a good idea. Perhaps we can do this for ical4j v4.

Note package would be org.mnode.ical4j.core as I don't have rights to the fortuna.net domain name.

**Comment by mwkroening** [comment]
Looking forward to it!

"Module names are strongly recommended to be the same as the name of the super-package."

I think this should not be an explicit module with the names not matching, so that should probably wait until v4.
We could change the name of the current automatic module to mark it as stable for this project in the `MANIFEST.MF`.

Note that for v4 we could also change the artifact coordinates to e.g. `org.mnode.ical4j:ical4j-core` for consistency, but this is not required. See: [Joda's Java SE 9 - JPMS modules are not artifacts](https://blog.joda.org/2017/04/java-se-9-jpms-modules-are-not-artifacts.html)

**Comment by benfortuna** [comment]
Just using the bnd plugin to define the automatic-module-name in manifest: #347

**Comment by mwkroening** [comment]
I see, you also defined the module names in most of the other ical4j projects. Thanks for your work!

What about [ical4j-integration](https://github.com/ical4j/ical4j-integration)?

**Comment by benfortuna** [comment]
Updated ical4j-integration, will be released shortly.

**Comment by benfortuna** [comment]
Trying to find evidence that sub-packages can't exist across multiple modules. This post seems to indicate they can:

https://stackoverflow.com/questions/50889780/java-9-sub-packages-split-across-modules

**Comment by mwkroening** [comment]
It might indeed be possible, but that would not be best practice, as far as I understand:

* ...
* Module names are strongly recommended to be the **same as the name of the super-package**.
* Creating a module with a particular name **takes ownership** of that package name and everything beneath it.
* As the owner of that namespace, any sub-packages may be grouped into sub-modules as desired so long as no package is in two modules.

(highlights taken from jodastephen)
This strategy is advertized by [sormuras](https://github.com/sormuras/modules#about-java-module-names) and [jodastephen](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html), who have much more experience on this topic than I do.

**Comment by benfortuna** [comment]
Yeah, I guess I'm just looking for some precedent for how other libraries similar to ical4j have done it.

For example, if I look at slf4j I can see they didn't change the core package (although the "sub modules" don't appear to export packages explicitly, but they do provide services in the same namespace):

```
module org.slf4j { 
  exports org.slf4j;
  exports org.slf4j.spi;
  exports org.slf4j.event;
  exports org.slf4j.helpers;
  uses org.slf4j.spi.SLF4JServiceProvider;
}
```
https://github.com/qos-ch/slf4j/blob/master/slf4j-api/src/main/java9/module-info.java

```
module org.slf4j.nop { 
  requires org.slf4j;
  provides org.slf4j.spi.SLF4JServiceProvider with org.slf4j.nop.NOPServiceProvider;
}
```
https://github.com/qos-ch/slf4j/blob/master/slf4j-nop/src/main/java9/module-info.java

Log4j also hasn't changed the base package but then I can only see one module from that project:

```
module org.apache.logging.log4j {
    exports org.apache.logging.log4j;
    exports org.apache.logging.log4j.message;
    exports org.apache.logging.log4j.simple;
    exports org.apache.logging.log4j.spi;
    exports org.apache.logging.log4j.status;
    exports org.apache.logging.log4j.util;

    uses org.apache.logging.log4j.spi.Provider;
    uses org.apache.logging.log4j.util.PropertySource;
    uses org.apache.logging.log4j.message.ThreadDumpMessage.ThreadInfoFactory;
}
```
https://github.com/apache/logging-log4j2/blob/master/log4j-api-java9/src/main/java/module-info.java


I'll keep looking for better examples, but my current thinking is that it doesn't feel right to change the base package of ical4j (i.e. `org.mnode.ical4j.core.*`), but if necessary perhaps the other libraries will require a more significant package name change.

e.g. for ical4j-core package might be: `org.mnode.ical4j.*`, for ical4j-vard: `org.mnode.ical4jvcard`, ical4j-connector: `org.mnode.ical4jconnector`, etc.

Again it doesn't feel right, but I want to explore all the possibilities as in the articles linked above they say to think very carefully about the module/package naming.
