### ISSUE TITLE
Accept empty values in compatibility mode

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#350]
Some buggy servers like Horde send empty values for properties which need a value, for instance `PRIORITY`:

```
SUMMARY: ...
PRIORITY:                            <- !!
STATUS:COMPLETED
```

which causes a NumberFormatException/ParserException. See also https://forums.bitfire.at/post/11777

I suggest to ignore such properties completely (instead of stopping with an exception) when compatibility mode is active.

**Comment by benfortuna** [comment]
I'd prefer not to ignore properties completely if possible. Because Priority has a valid value of `UNDEFINED`, would it be ok to use this in place of invalid values when relaxed parsing is enabled.

So instead of the ParserException would you see a `PRIORITY: 0` in the object model.

**Comment by rfc2822** [comment]
> So instead of the ParserException would you see a `PRIORITY: 0` in the object model.

Sounds like a good solution! Anything that allows parsing of (invalid) empty values without exception would be fine.

**Comment by benfortuna** [comment]
Included in 3.0.10 release. Will backport to the 2.x stream.

**Comment by rfc2822** [comment]
Nice, thanks! :)

**Comment by benfortuna** [comment]
iCal4j 2.2.6 just released will also include this - should appear in maven central shortly.
