### ISSUE TITLE
3.0.9 was uploaded without proper POM

### ISSUE THREAD

**Issue by MikeN123** [ical4j/ical4j#353]
**Describe the bug**
Version 3.0.9 does not list any dependencies in the POM: https://mvnrepository.com/artifact/org.mnode.ical4j/ical4j/3.0.9
3.0.7 did: https://mvnrepository.com/artifact/org.mnode.ical4j/ical4j/3.0.7

**Expected behavior**
Dependencies are included in the POM.

**Comment by benfortuna** [comment]
Fixed in 3.0.10 release
