### ISSUE TITLE
Apple Holiday iCalendar feeds fails to parse (net.fortuna.ical4j.validate.ValidationException: Property [DTSTAMP] must be specified once)

### ISSUE THREAD

**Issue by marcoismobile** [ical4j/ical4j#357]
**Describe the bug**

When trying to parse Holiday icalendar feeds from Apple, it fails with the following error:

```
net.fortuna.ical4j.validate.ValidationException: Property [DTSTAMP] must be specified once
```
Example feed:

- http://ical.mac.com/ical/Dutch32Holidays.ics

```
BEGIN:VEVENT
UID:271
DTSTART;VALUE=DATE:20191231
DTEND;VALUE=DATE:20200101
SUMMARY:Oudejaarsdag
RESOURCES;LANGUAGE=EN:New Year's Eve
END:VEVENT
```
According to the specs this ValidationException is indeed CORRECT and the missing DTSTAMP is required.

To use the Apple icalendar feeds, while still doing some validation, my question is as follow:

Is it possible to ignore this ValidationException when **ical4j.validation.relaxed=true** ?

**To Reproduce**
Try to parse this icalendar feed:
- http://ical.mac.com/ical/Dutch32Holidays.ics

**Expected behavior**
Parse icalendar feed to icalendar java object.

**Environment:**
 - OS: Linux
 - Java Version 8
 - iCal4j: v3.0.6

**Comment by benfortuna** [comment]
We do already support this when relaxed validation is enabled. Note that this setting should be either in an `ical4j.properties` file in the root of the classpath or specified as a system property (e.g. `-Dical4j.validation.relaxed=true`)

**Comment by marcoismobile** [comment]
Thank you for the fast reply!

I do have the validation.relaxed=true property set and working. But it is not relaxing the DTSTAMP property as far I can see.

According to the code in the VEvent publish validator:

public void validate(final VEvent target) throws ValidationException {
        Arrays.asList(DTSTAMP, DTSTART).forEach(property -> PropertyValidator.getInstance().assertOne(property, target.getProperties()));

So as far as I can see the DTSTAMP is required even if the relaxed property is set to true.

Or am I doing something wrong?

**Comment by benfortuna** [comment]
The publish validator shouldn't be invoked when parsing a calendar object. In fact i can't see anywhere it is used implicitly right now.

There is a `validate()` method in Component that is used to validate, and that is the one that has the relaxed validation on DTSTAMP.

**Comment by marcoismobile** [comment]
Sorry I think I wasn't really clear.

The parsing did indeed worked normally (no problem at all).
But when calling the validate method on the parsed (i)calendar object, then the Exception occured.

So that's probably why I didn't see the relaxed validation in the validator code :)

What I do is parsing an input stream (e.g. an URL) to an icalendar object and afterwards calling the validate() method on that object. Is that the correct way?

Because now the parsing is going just fine, only the validation afterwards is failing because of the missing DTSTAMP property in the VEvents.

**Comment by benfortuna** [comment]
Ah yes you are right, I missed that one. I'll update the publish validator to support relaxed validation also.

**Comment by marcoismobile** [comment]
Tnx the new validation was exactly what I was looking for!

Working wonderfull.
