### ISSUE TITLE
All Packages are marked as private inside the manifest

### ISSUE THREAD

**Issue by daMihe** [ical4j/ical4j#360]
**Describe the bug**
The bintray releases contain a manifest, which does not export any package so the library can not be used in OSGi-Environments properly.

**To Reproduce**
1. Download Release-jar
2. Open META-INF/MANIFEST.MF inside the jar

**Expected behavior**
All Packages inside net.fortuna.ical4j should be listed at Export-Package

**Environment:**
 - Seen in 3.0.9, 3.0.10

Thanks in advance

**Comment by benfortuna** [comment]
Fixed in release 3.0.11: https://github.com/ical4j/ical4j/releases/tag/ical4j-3.0.11

Other ical4j projects also updated with fix, will be released shortly.

**Comment by daMihe** [comment]
Thank you ben for this really fast handling of the issue. Now i'm getting a different error while depending on ical4j:

```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.2.6:verify (karaf-feature-verification) on project org.openhab.binding.icalpresence: Feature resolution failed for [openhab-binding-icalpresence/2.5.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-icalpresence; type=karaf.feature; version=2.5.0.SNAPSHOT; filter:="(&(osgi.identity=openhab-binding-icalpresence)(type=karaf.feature)(version>=2.5.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-icalpresence/2.5.0.SNAPSHOT: missing requirement [openhab-binding-icalpresence/2.5.0.SNAPSHOT] osgi.identity; osgi.identity=org.openhab.binding.icalpresence; type=osgi.bundle; version="[2.5.0.201910122016,2.5.0.201910122016]"; resolution:=mandatory [caused by: Unable to resolve org.openhab.binding.icalpresence/2.5.0.201910122016: missing requirement [org.openhab.binding.icalpresence/2.5.0.201910122016] osgi.wiring.package; filter:="(&(osgi.wiring.package=net.fortuna.ical4j.model)(version>=3.0.0)(!(version>=4.0.0)))" [caused by: Unable to resolve ical4j/3.0.11: missing requirement [ical4j/3.0.11] osgi.serviceloader; filter:="(osgi.serviceloader=net.fortuna.ical4j.model.*)"; cardinality:=multiple]]]
```

This may be a karaf issue as `ical4j` (for me it looks like a naming issue - but my knowledge about OSGi issues is limited) is the symbolic name and a different container may resolve this without any issues. Which container did you use for verification?

**Comment by benfortuna** [comment]
This appears to be related to support for `java.util.ServiceLoader`: #143 #115 

If you can have a look at this from OSGi Alliance it may also help:

https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html

**Comment by daMihe** [comment]
Again, thanks for your really quick pointer.

I tried to dig more into the issue. Looking at SPI fly (was not able to load ical4j, openhab2 (where i'm trying to create an addons for) seems to use SPI fly as well, as the bundle is available even if i don't declare the usage in my addon) and the resulting `MANIFEST.MF`, currently ical4j is a consumer for various Services in `net.fortuna.ical4j.model.*`. So far everything in my eyes is right and this also matches to the output i'm getting.

Now the strange part: These services' implementations are also included in the same bundle and not marked as provided (even if there are definitions inside of `META-INF/services`). Instead, the `ical4j-extensions` artifact provides the implementations but does not contain these currently.

So from my point of view the solution may be the just correct declaration of "Provide-Capability" and also requiring the SPI-registrar inside this package (according to [SPI fly Provider doc](http://aries.apache.org/modules/spi-fly.html#providers)). I'm just not sure how to test this, as the openhab2-environment makes testing non-published things hard.
