### ISSUE TITLE
Hang on TimeZone.getTimeZone(String)

### ISSUE THREAD

**Issue by valenpo** [ical4j/ical4j#376]
**Describe the bug**
In concurrent environment we get threads stuck on TimeZone.getTimeZone(String). Each call take 0.5 sec. 

**Screenshots**
<img width="1189" alt="Screenshot 2019-12-19 at 11 32 17" src="https://user-images.githubusercontent.com/1099203/71157861-d9cde200-2253-11ea-8ba3-5803349814a3.png">

**Environment (please complete the following information):**
 - OS: [Linux]
 - Java Version [8]

**Additional context**
One way is cache values or use Joda-Time

https://stackoverflow.com/questions/5682236/why-is-timezone-gettimezoneid-synchronized-and-why-this-isnt-documented.

**Comment by benfortuna** [comment]
Note we have a branch in progress to update to new date/time api (see sticky issues). In the meantime the attached PR has been merged.
