### ISSUE TITLE
Move from non ThreadSave Date to DateTime etc... 

### ISSUE THREAD

**Issue by valenpo** [ical4j/ical4j#378]
**Is your feature request related to a problem? Please describe.**
#377 

**Describe the solution you'd like**
Date is not thread save. And min requirements for 3.x is JVM8.

**Describe alternatives you've considered**
Use DateTime, ZoneId etc...

**Comment by benfortuna** [comment]
Merged PR. Reopen and provide more info if issue not resolved.
