### ISSUE TITLE
Groovy dependency

### ISSUE THREAD

**Issue by husayt** [ical4j/ical4j#38]
I was surprised to find out that ical4j library depends on groovy-all.jar, which makes it very expensive to add. We only use ical4j for simple ical generation, do we still need to ship groovy-all.jar?

I will appreciate for some clarification for when this library needed and when can be safely omitted.

**Comment by benfortuna** [comment]
Hi,

No, you don't need Groovy to use the standard calendar parsing/generation
features. The Groovy dependency should only be required for extra
Groovy-specific features such as builder support (and running unit tests).

I'll try to make that clearer for future releases.

Regards,
Ben

**Comment by husayt** [comment]
Thanks for reply.
I'm using Ical4j from maven (see below) and that pulls groovy-all library
which is 7Mb. Is there any way to exclude it ?

```
<dependency>
    <groupId>org.mnode.ical4j</groupId>
    <artifactId>ical4j</artifactId>
    <version>${ical4j.version}</version>
</dependency>

```

Thanks

Best  regards,
Huseyn Guliyev

------------------------------------------------------------

**Comment by benfortuna** [comment]
Yes you should be able to use a dependency exclusion:

https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

e.g:

<dependency>
 <groupId>org.mnode.ical4j</groupId>
 <artifactId>ical4j</artifactId>
 <version>${ical4j.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
        </exclusion>
      </exclusions>
 </dependency>

**Comment by husayt** [comment]
Thank you. this was very useful and appreciated.
