### ISSUE TITLE
Recurring Last day of month does not work for leap year

### ISSUE THREAD

**Issue by rwankar** [ical4j/ical4j#380]
If you set the recur rule to last day of the month then Feb 29 2020 doesn't come up as it is a leap year.

**To Reproduce**
Use the recur rule "FREQUENCY:MONTHLY;BYMONTHDAY=-1".
Seed Date = Dec 1 2019
Start Date = Dec 1 2019
End Date  = Apr 1 2020
Check recur dates

**Expected behavior**
Expect Feb 29 2020 to show up

**Environment (please complete the following information):**
Java 11

**Comment by bgabrhelik** [comment]
I came across similar issue. I tested your case and it works form me in 3.0.11. The syntax of RRULE above doesn't seem to be correct. See the example below.

`
        // test last day of the month
        recur = new Recur("FREQ=MONTHLY;BYMONTHDAY=-1");
        DateList dates2 = recur.getDates(new DateTime("20191201T000000"), new DateTime("20191201T000000"), new DateTime("20200401T100000"), Value.DATE_TIME);
        assertEquals(new DateTime("20200229T000000"), dates2.get(2));
`

**Comment by rwankar** [comment]
My apologies. I am using the correct pattern just mistyped it here.

RRULE = FREQ=MONTHLY;BYMONTHDAY=-1

The issue seems to be with the seed date. See following conditions.

1. Feb 29, 2020 missing
Start ="2019-12-30-00-00-00"
End ="2020-12-30-00-00-00"
Seed="2019-12-30-00-00-00"

2. Skips all months with 30 days
Start ="2019-12-30-00-00-00"
End ="2020-12-30-00-00-00"
Seed="2019-12-31-00-00-00"  (Only seed date changed)

3. Works correctly if seed date = "2019-12-01-00-00-00"

The above conditions work correctly with 1.0.3

**Comment by bgabrhelik** [comment]
So, it seems that I reported the same issue in  #383.

**Comment by rwankar** [comment]
Yes.

**Comment by benfortuna** [comment]
Should be fixed in latest release.
