### ISSUE TITLE
Integer overflow bug in TemporalAmountAdapter causes incorrect duration to be calculated

### ISSUE THREAD

**Issue by lhillman** [ical4j/ical4j#386]
**Describe the bug**
There's a bug in the `TemporalAmountAdapter` class that causes durations longer than 24 days (and exactly N days) to be miscalculated due to an integer overflow:

```
duration = java.time.Period.ofDays((int) durationMillis / (24 * 60 * 60 * 1000));
```
[link](https://github.com/ical4j/ical4j/blob/1e717ea0987b7b59975138bf6522becea315f80d/src/main/java/net/fortuna/ical4j/model/TemporalAmountAdapter.java#L134)

This should be:

```
duration = java.time.Period.ofDays((int) (durationMillis / (24 * 60 * 60 * 1000)));
```

**To Reproduce**
```
DtStart start = new DtStart("20200107T000000");
DtEnd end = new DtEnd("20200331T000000");
TemporalAmount rDuration = TemporalAmountAdapter.fromDateRange(start.getDate(), end.getDate()).getDuration();
System.out.println(rDuration);
```

Output:
`P-15D`

**Expected behavior**
Should output: `P84D`.

**Environment (please complete the following information):**
 - OS: Linux
 - Java Version: 8

Will submit a pull request with the fix if I can, but having trouble successfully running the tests at the moment (getting failures in `VEventRecurrenceParametrizedTest`).

**Comment by benfortuna** [comment]
Fix applied in #389
