### ISSUE TITLE
tzurl.org has expired

### ISSUE THREAD

**Issue by matmannion** [ical4j/ical4j#390]
Timezone updates don't work with the default `net.fortuna.ical4j.timezone.update.enabled=true` because tzurl.org has expired.

```
$ whois tzurl.org
Domain Name: TZURL.ORG
Registry Domain ID: D155263266-LROR
Registrar WHOIS Server: whois.dreamhost.com
Registrar URL: http://www.dreamhost.com/
Updated Date: 2020-02-03T08:41:59Z
Creation Date: 2009-02-03T22:14:15Z
Registry Expiry Date: 2020-02-03T22:14:15Z
...
```

Unless tzurl.org can be brought back (I'm not sure if it's directly related to the project or not), there needs to be a replacement and/or the default setting of `net.fortuna.ical4j.timezone.update.enabled` changed to `false`.

**Comment by benfortuna** [comment]
Apologies, yes I do also manage that domain. I just forgot to renew, but I've done it now so it should be back up within an hour or so.
