### ISSUE TITLE
exceptions to a recurring range not handled correctly by ComponentGroup; period not taken into account

### ISSUE THREAD

**Issue by tbee** [ical4j/ical4j#396]
The situation is simple; I have a recurring vevent on weekdays, for example mo, tu, th and fr. Then I create an exception by moving tu to we. Now I have two events in the ical file

BEGIN:VEVENT
DTSTART;TZID=Europe/Rome:20200303T061500
DTEND;TZID=Europe/Rome:20200303T071500
DTSTAMP:20200304T064905Z
UID:7lecbe8p0aag51tq9ausokse3x@google.com
RECURRENCE-ID;TZID=Europe/Rome:20200304T061500
CREATED:20200202T092719Z
DESCRIPTION:
LAST-MODIFIED:20200301T212302Z
LOCATION:
SEQUENCE:3
STATUS:CONFIRMED
SUMMARY:precond
TRANSP:OPAQUE
END:VEVENT

BEGIN:VEVENT
DTSTART;TZID=Europe/Rome:20200203T061500
DTEND;TZID=Europe/Rome:20200203T071500
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR,MO,TH,WE
DTSTAMP:20200304T064905Z
UID:7lecbe8p0aag51tq9ausokse3x@google.com
CREATED:20200202T092719Z
DESCRIPTION:
LAST-MODIFIED:20200212T071944Z
LOCATION:
SEQUENCE:2
STATUS:CONFIRMED
SUMMARY:precond
TRANSP:OPAQUE
END:VEVENT

If I now ask ical4j which is the getLatestRevision for the UID, I always get the one valid on 20200203, because that logic does not take any timeframe into account. If I then calculate the calculateRecurrenceSet for the day before, I get no periods. But on the day for the exception, the original recurring event should be used.

Using group.calculateRecurrenceSet does not work either, because then I get all periods, both from the recurring and the exception. Shouldn't getLatestRevision take the period into account?

**Comment by benfortuna** [comment]
The sequence should be the first thing considered when getting the latest revision, so I think I need to check the logic there.

Thanks for reporting the issue, will let you know when a fix is available.

**Comment by tbee** [comment]
I slept over it, and what I think is that there is a more fundamental issue here. What the current code does is compare a recurring event with a non-recurring event, I'm not sure those two are on the same "level". 

Could it be that first the recurring event needs to generate actual events, and then the non-recurring event must be "applied" to that set. Because somehow the events on mo,tu,th,fr must be converted to events on mo,we,th,fr. So not only is the we added, but the one on tu must be removed. It is moved afterall.

Somehow that non-recurring event needs to say "my original time is 20200303, but make it 20200304", so that the generated set can correctly be modified.

**Comment by benfortuna** [comment]
Ok, so there is support for removal of recurrences from an event via the EXDATE property:

https://tools.ietf.org/html/rfc5545#section-3.8.5.1

When I look at your example closer I think that probably you need to do two things:

1. Create a new (non-recurring) VEVENT representing the Wednesday exception to the recurrence rule. I think this event should have a distinct UID and not be related to the original VEVENT (i.e. shouldn't be part of the component group)

2. Add an EXDATE to the recurring VEVENT to exclude the Tuesday occurrence that was replaced with the new VEVENT.

This is my theory, but it may be worth trying to recreate the scenario in MS Outlook (for example) and export the ICS file to see how other tools do this.

**Comment by tbee** [comment]
The ical file is what Google calendar gives me. I have made the change of moving a recurring event from Tu to We. I was expecting ical4j to give me mo, we, th, fr for this week, but it does not. If I use ComponentGroup it does not give me the original recurring anymore.

As said, I think ComponentGroup should first generate the events for the period from the recurring event (being mo, tu, th, fr) and then apply the single one to that set resulting in mo, we, th, fr.

So this one 
DTSTART;TZID=Europe/Rome:20200203T061500
DTEND;TZID=Europe/Rome:20200203T071500
**RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR,MO,TH,WE**

Generates four events:
DTSTART;TZID=Europe/Rome:**20200302**T061500
DTEND;TZID=Europe/Rome:20200302T071500
+
DTSTART;TZID=Europe/Rome:**20200303**T061500
DTEND;TZID=Europe/Rome:20200303T071500
+
DTSTART;TZID=Europe/Rome:**20200305**T061500
DTEND;TZID=Europe/Rome:20200305T071500
+
DTSTART;TZID=Europe/Rome:**20200306**T061500
DTEND;TZID=Europe/Rome:20200306T071500

Then this one is applied
DTSTART;TZID=Europe/Rome:**20200303**T061500
DTEND;TZID=Europe/Rome:20200303T071500
RECURRENCE-ID;TZID=Europe/Rome:**20200304**T061500

Changing 20200303 to 20200304, resulting in the set that is wanted.

**Comment by benfortuna** [comment]
Yup ok, I think my previous understanding was a bit incomplete (EXDATE is only used to remove instances, not replace).

The key is the RECURRENCE-ID property, which is used to identify a replacement in the calculated set. 

In this case we must assume the start date of the resulting period set matches the original DTSTART property and use the RECURRENCE-ID to replace the matching period.

I'll look at how to fix this shortly.

**Comment by benfortuna** [comment]
I've added a pull request (#397) that I think fixes the issue. Will release shortly.

**Comment by tbee** [comment]
Commented in the pull request. 

I've taken a look at what happens when you delete an appointment, but that indeed is marked as EXDATE.

DTSTART;TZID=Europe/Rome:20200203T061500
DTEND;TZID=Europe/Rome:20200203T071500
RRULE:FREQ=WEEKLY;WKST=MO;BYDAY=FR,MO,TH,WE
**EXDATE;TZID=Europe/Rome:20200305T061500**
**EXDATE;TZID=Europe/Rome:20200304T061500**

Here I deleted the WE and TH in the same week. EXDATE (removing events) should also be applied to the generated set of events.

**Comment by benfortuna** [comment]
@tbee Could you elaborate on the last sentence? Are they not being excluded from the results of calculateRecurrenceSet?

**Comment by tbee** [comment]
Ah, sorry, That already seems to work in the current version. 

It seemed logical to me that all types of exceptions to an effected recurring, would be handled in the same place. And I had not seen code handling EXDATE in the pull request, so I assumed that it did not handle that either.

**Comment by tbee** [comment]
Something is still strange. So it works correctly, but if I reduce the ical file I used to test the logic to exactly the three vevents I need for the test, then wednesday fails on that the moved event from tuedays is not present. If I add a random additional fourth vevent, then all test pass.

Need to examine closer what is causing that.

**Comment by tbee** [comment]
My bad, it works! Thank you very much.

**Comment by tbee** [comment]
I still would suggest adding the calendar.getComponentGroups() method, to remove the need for duplicate UID checking for the user of ical4j. :-)

**Comment by benfortuna** [comment]
Actually it may not be obvious, but the ComponentGroup implementation will filter on matching events in the component list. 

So for any given UID you can say `new ComponentGroup(calendar.getComponents(), uid).getRevisions()` and it will only return events matching that uid.

But then you still have the problem of getting the full list of UIDs for a calendar, which I think is currently missing..

**Comment by tbee** [comment]
Yes, I understand. So if I have a list with 7 Components with UIDs A,B,B,C,C,C,D, I would like to get a list with 4 ComponentGroups for UIDs A,B,C,D, where B en C of course have 2 and 3 Components. I can then iterate over the ComponentGroups instead of over Components (and having to handle duplicates). Something in the spirit of this:

ComponentList<CalendarComponent> components = calendar.getComponents();
List<ComponentGroup<CalendarComponent>> componentGroups = components.stream()
	.filter(c -> c instanceof VEvent)
	.map(c -> (VEvent)c)
	.map(e -> e.getUid())
	.distinct()
	.map(uid -> new ComponentGroup<CalendarComponent>(components, uid))
	.collect(Collectors.toList());

Hm. Which makes me think... What happens if the summary of a moved event was changed (that is a determining factor for my algorithm). Right now only the date was changed. So for me the uniqueness is not only the UID; I need to extend that map(e -> e.getUid()).

**Comment by tbee** [comment]
Yes. So how do I get to the summary of the event that caused a certain period to be present in the result of componentGroup.calculateRecurrenceSet(period)? The period may originate from the recurring event or from an exception, which may have a different value.
