### ISSUE TITLE
Remove clover.license file

### ISSUE THREAD

**Issue by parlt91** [ical4j/ical4j#415]
HI,

**Is your feature request related to a problem? Please describe.**
We want to build and ship ical4j on our project https://github.com/uyuni-project/uyuni,
but this proprietary license file `clover.license` prevents us from using it due to legal
reasons.

**Describe the solution you'd like**
Since clover is not in use in the project anymore (since 2013 if my investigations are correct),
could you remove the `clover.license` file located at `/etc/clover.license`?

**Comment by benfortuna** [comment]
Yes, no problem. I've created a PR to remove the file here: #416

**Comment by parlt91** [comment]
Great! Thank you very much. I will close the issue once the PR is merged.
