### ISSUE TITLE
TemporalAmountAdapter: durationToString drops minutes when using P2DT1H4M format

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#420]
Steps to reproduce (ical4j 3.0.19):

`TemporalAmountAdapter(Duration.parse("P2DT1H4M")).toString()`

Actual result: `P2DT1H`
Expected result: `P2DT1H4M`

This is because [this case is not handled here](https://github.com/ical4j/ical4j/blob/e6a002f3b43ef2ba23a72f547685e3e6e8be5c86/src/main/java/net/fortuna/ical4j/model/TemporalAmountAdapter.java#L95).

As soon as a second is added, it works again: `TemporalAmountAdapter(Duration.parse("P2DT1H4M5S")).toString()` → `P2DT1H4M5S`

**Comment by rfc2822** [comment]
Test:

    @Test
    fun testTemporalAmountAdapter_durationToString_DropsMinutes() {
        assertEquals("P1DT1H4M", TemporalAmountAdapter.parse("P1DT1H4M").toString())
    }
    // org.junit.ComparisonFailure: 
    // Expected :P1DT1H4M
    // Actual   :P1DT1H

**Comment by benfortuna** [comment]
Fix applied in #421

**Comment by nealeu** [comment]
@benfortuna I just spotted this and wondering why it's still in review?  I think it can be closed

**Comment by benfortuna** [comment]
Great thx.
