### ISSUE TITLE
Parsing VCALENDAR with only one VTIMEZONE possible?

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#43]
Hello,

Thanks for your new 2.0-beta1 release. I have a question: is it possible to parse a VCALENDAR with only one VTIMEZONE component with the current ical4j version? Background: Calendar collections on CalDAV servers have a property called [`calendar-timezone`](http://tools.ietf.org/html/rfc4791#section-5.2.2) which is »an iCalendar object with exactly one VTIMEZONE component«.

For instance, a server returns:

```
<?xml version='1.0' encoding='UTF-8'?>
<multistatus xmlns='DAV:'>
  <response>
    <href>/xxxxx/calendars/home/</href>
    <propstat>
      <prop>
        <calendar-timezone xmlns='urn:ietf:params:xml:ns:caldav'><![CDATA[BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.4//EN
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
DTSTART:20070311T020000
TZNAME:GMT-7
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
DTSTART:20071104T020000
TZNAME:GMT-8
TZOFFSETTO:-0800
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
]]></calendar-timezone>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
```

When I try to parse this string (the content of calendar-timezone) with `Calendar cal = builder.build(new StringReader(timezoneDef))`, `cal.getComponents()` returns only one component which is of type `net.fortuna.ical4j.model.component.XComponent`, so I can't get the TZID.

Is there a new way to parse such a time zone definition?

**Comment by rfc2822** [comment]
Sorry, that was my mistake *again*. I forgot to set

```
Thread.currentThread().setContextClassLoader(getInstrumentation().getContext().getClassLoader());
```

in the tests (Android tests). It's quite annoying that Android doesn't set the context class loader, so I have to do it manually for every new thread before calling anything in ical4j.

**Comment by benfortuna** [comment]
That does seem very painful. I'm keen to do what I can in ical4j to make it
easier to use on Android, so if you have any suggestions feel free to raise
a new ticket.
