### ISSUE TITLE
EMAIL parameter not supported?

### ISSUE THREAD

**Issue by monkeyfdude** [ical4j/ical4j#44]
Caused by: java.lang.IllegalArgumentException: Unsupported parameter name: EMAIL
 at net.fortuna.ical4j.model.ParameterFactoryImpl.createParameter(ParameterFactoryImpl.java:90)

ATTENDEE;CN=U O;CUTYPE=INDIVIDUAL;EMAIL=gj@localhost;PARTSTAT=NE
 EDS-ACTION;ROLE=REQ-PARTICIPANT;RSVP=TRUE;SCHEDULE-STATUS=1.2:urn:x-uid:gj

I use Darwin Calendar Server 6.0

**Comment by arnaudq** [comment]
The EMAIL parameter is indeed a non RFC5545 standard parameter. To define it you will need to
1) add an Email class extending Parameter
2) add a custom ParameterFactoryRegistry (defining the parameter defined above)
3) pass that registry to the CalendarBuilder used to do the parsing/loading.

Have a look at https://github.com/ical4j/ical4j-extensions although this repo does not seem to contain this particular parameter.

**Comment by rfc2822** [comment]
DAVdroid uses this non-standard parameter too: https://github.com/bitfireAT/davdroid/blob/v0.8.4/app/src/main/java/at/bitfire/davdroid/resource/iCalendar.java#L137 (for better iCloud support)

**Comment by benfortuna** [comment]
FYI I've started adding support for the calext extensions draft on this branch of the ical4j-extensions project:

https://github.com/ical4j/ical4j-extensions/tree/feature/draft-ietf-calext-extensions

If you have any further input you can raise issues here:

https://github.com/ical4j/ical4j-extensions/issues
