### ISSUE TITLE
Certain timezones never get cached, resulting in net.fortuna.ical4j.model.TimeZoneLoader#updateDefinition() being called every time

### ISSUE THREAD

**Issue by ShervinM-AVISPL** [ical4j/ical4j#459]
Have found few timezones (see below) that are not being cached, resulting in tzurl.org being contacted every time:
"America/Nuuk" which should have same ID as "America/Godthab"
"Europe/Belgrade" which should have same ID as "Europe/Sarajevo"
"Africa/Lagos" which should have same ID as "Africa/Luanda"
"Africa/Maputo" which should have same ID as "Africa/Harare"
"Europe/Istanbul" which should have same ID as "Asia/Istanbul"
"Asia/Riyadh" which should have same ID as "Asia/Kuwait"
"Asia/Dubai" which should have same ID as "Asia/Muscat"

The bug is in net.fortuna.ical4j.model.TimeZoneRegistryImpl#getTimeZone() method. It looks like you know about issue, but did not address it yet.
The code in question is:
```
// XXX: temporary kludge..
// ((TzId) vTimeZone.getProperties().getProperty(Property.TZID)).setValue(id);
timezone = new TimeZone(vTimeZone);
DEFAULT_TIMEZONES.put(timezone.getID(), timezone);

```
There is a line attempting the replace time zone ID, but it is commented out. The proper fix IMHO would be not replacing time zone ID but adding the same time zone to the map twice – with original ID and with updated ID. This way time zone will be there with both e.g. Asia/Kuwait and Asia/Riyadh IDs. Something like:
```
timezone = new TimeZone(vTimeZone);
DEFAULT_TIMEZONES.put(timezone.getID(), timezone);
if (!timezone.getID().equals(id)) {
    DEFAULT_TIMEZONES.put(id, timezone);
}
```

**To Reproduce**
create a class and add followng 2 methods to it.
create a unit test and call calculateRecurrenceSet() twice for the same timeZone
Current behavior is that the first time calculateRecurrenceSet() is called, tzurl.org is contacted, and the ID should be cached, and second time this method is called, same timezone should be retrieved from the cached list. But, for above-mentioned timezones, cache is never updated, and tzurl.org is being contacted every time.

```
public final static PeriodList calculateRecurrenceSet(Date eventStartTime, Date eventEndTime, TimeZone eventTimeZone, String recurrenceRule,
    Date from, Date to) throws Exception {
  // build iCalendar event
  StringBuilder sb = new StringBuilder();
  sb.append("BEGIN:VCALENDAR\n");
  sb.append("BEGIN:VEVENT\n");
  sb.append("DTSTART;TZID=");
  final String timeZoneId = eventTimeZone.getID();
  sb.append(timeZoneId);
  sb.append(":");
  sb.append(dateToICalString(eventStartTime, eventTimeZone));
  sb.append("\n");
  sb.append("DTEND;TZID=");
  sb.append(timeZoneId);
  sb.append(":");
  sb.append(dateToICalString(eventEndTime, eventTimeZone));
  sb.append("\n");
  sb.append(recurrenceRule);
  sb.append("\n");
  sb.append("END:VEVENT\n");
  sb.append("END:VCALENDAR");

  try (StringReader stringReader = new StringReader(sb.toString())) {
    if (System.getProperty("net.fortuna.ical4j.timezone.cache.impl") == null) {
      System.setProperty("net.fortuna.ical4j.timezone.cache.impl", "net.fortuna.ical4j.util.MapTimeZoneCache");
    }
    CalendarBuilder calendarBuilder = new CalendarBuilder();
    Calendar calendar = calendarBuilder.build(stringReader);

    return calendar.getComponent("VEVENT").calculateRecurrenceSet(new Period(new DateTime(from), new DateTime(to)));
  }
}
  
public final static String dateToICalString(Date date, TimeZone timeZone) {
		SimpleDateFormat dateFormat;
		if (timeZone.equals(UTC) || timeZone.hasSameRules(UTC)) {
			dateFormat = new SimpleDateFormat("yyyyMMdd'T'HHmmss'Z'");
		} else {
			dateFormat = new SimpleDateFormat("yyyyMMdd'T'HHmmss");
		}
		dateFormat.setTimeZone(timeZone);
		return dateFormat.format(date);
} 

```
**Expected behavior**
if time zone ID does not match, you should cache the time zone and, therefore, such requests for update should not be issued every time when time zone is used

**Environment (please complete the following information):**
 - OS: CentOS Linux
 - Java Version: openjdk version "14.0.1"

**Comment by benfortuna** [comment]
Apologies for taking so long to address this. There are some recent changes to timezone updates to make caching more efficient, however I think your suggestion here is still valid.

I've added the suggested fix and will be included in the next release. Many thx.
