### ISSUE TITLE
Incorrect method value of "DECLINECOUNTER"

### ISSUE THREAD

**Issue by tommix000** [ical4j/ical4j#465]
Hello, 

The value 
**public static final Method DECLINE_COUNTER = new ImmutableMethod("DECLINE-COUNTER");**
in net.fortuna.ical4j.model.property.Method.java should be
**public static final Method DECLINE_COUNTER = new ImmutableMethod("DECLINECOUNTER");**

The "-" is only used to break the word into 2 lines in the PDF of the RFC. All other declarations in the RFC use the form "DECLINECOUNTER".

best regards,
Thomas

**Comment by benfortuna** [comment]
Hi Thomas,

Thanks for the bug report, I have a fix in place. 

I must say I'm quite surprised this went for so long unnoticed - has been like that since the initial commit in 2004! I guess that's an indication of how much this method has been used with ical4j (i.e. probably not at all yet) ;-)
