### ISSUE TITLE
Rrule incorrectly includes invalidCandidateCount in the count check

### ISSUE THREAD

**Issue by voronaam** [ical4j/ical4j#47]
Consider for example this RRULE: FREQ=MONTHLY;WKST=FR;COUNT=3;INTERVAL=1;BYMONTH=1,9,10,12;BYMONTHDAY=12

Evaluated today it should give Oct 12, Dec 12 and Jan 12. Using iCal4j 2.0.1beta (and 1.0.6 as well) this is not happening. Only Oct 12 and Dec 12 are returned and Jan 12 is ruled out by the count check:

```java
if (getCount() >= 1
    && (dates.size() + invalidCandidateCount) >= getCount()) {
```

That is in Recur.class:getDates(), line 630 (as of now).

This check should not include invalid candidates (the ones that were filtered out by BYMONTH rule in this example)

**Comment by voronaam** [comment]
The issue is because BYMONTH rule populates candidates with all valid months - a year worth of them. But `increment(cal)` method only increments seed date by the recurrence interval - one month.

As a result, when queried for dates in January 2016, Recur counts skipped October and December instance multiple times. It starts in September - counts October and December as invalid (+2). Moves seed to October, and counts December again (2+1) which reaches the specified count (3) and no occurrence in January is returned.

**Comment by voronaam** [comment]
Pull Request PR48 created to address this issue.

**Comment by benfortuna** [comment]
PR merged. Many thanks.
