### ISSUE TITLE
ComponentGroup handling of recurrence instance with an RRule

### ISSUE THREAD

**Issue by LeeWorrall** [ical4j/ical4j#472]
I have a calendar created by the Atlassian Confluence Calendar Plugin that contains a recurring (all-day) event:
- initially created with no endDate
- two instances have subsequently been edited
- one instance has subsequently been deleted
- then "all future instances" from a specific date have deleted

If I create a ComponentGroup and then calculateRecurrenceSet, the instances continue forever, the don't stop where I deleted "all future instances".

The root cause seems to be that when I edit a single instance (in confluence) it adds a VEVENT with a RECURRENCE-ID, as it should, _but includes the original RRULE in that VEVENT_

ComponentGroup.calculateRecurrenceSet contains (comments are mine)

```
        PeriodList finalPeriods = periods;
        replacements.forEach(component -> {
            RecurrenceId recurrenceId = component.getProperty(Property.RECURRENCE_ID);
            // Remove only the instance that matches the replacement VEVENT RECURRENCE-ID's DATE
            List<Period> match = finalPeriods.stream().filter(p -> p.getStart().equals(recurrenceId.getDate()))
                    .collect(Collectors.toList());
            finalPeriods.removeAll(match);

            // Add instances calculated from the RRULE on the replacement, which may extend beyond the main VEVENT's RRULE UNTIL
            finalPeriods.addAll(component.calculateRecurrenceSet(period));
        });
```

I understand the behavior is maybe not well-defined in this area and confluence is possibly doing the wrong thing in including the RRULE in the replacement VEVENTS (if I try the same thing in Google calendar then export that, the replacement VEVENTS do not have the RRULE in them), however, if I import the calendar from confluence into either Google Calendar or Outlook then those replacement VEVENTS occur only once (on the RECURRENCE-ID date).

The Confluence_Create_ThenOverride_ThenDelete_ThenDeleteAllFutureInstances.ics example in [ical4j-test.zip](https://github.com/ical4j/ical4j/files/5684374/ical4j-test.zip) (and included below)
shows what I mean. The main event has
`RRULE:FREQ=WEEKLY;UNTIL=20210212;INTERVAL=5;BYDAY=SA`
but the UNTIL=20210212 was added in the final step of delete "all future instances", the other VEVENTS with the same UID and a RECURRENCE-ID have the original
`RRULE:FREQ=WEEKLY;INTERVAL=5;BYDAY=SA`

Again, I realize it may not be well-defined what's should happen given this source but the Google and Outlook handling seems more reasonable that the replacements only happens on the date in their RECURRENCE-ID.

```BEGIN:VCALENDAR
PRODID:-//Atlassian Confluence//Calendar Plugin 1.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:20201207T095828Z
DTSTART;VALUE=DATE:20191116
DTEND;VALUE=DATE:20191123
SUMMARY:111
EVENT-ID:1
EVENT-ALLDAY:true
UID:xxx@yyy
RRULE:FREQ=WEEKLY;UNTIL=20210212;INTERVAL=5;BYDAY=SA
CREATED:20191014T061003Z
LAST-MODIFIED:20201030T100040Z
EXDATE;VALUE=DATE:20201205
SEQUENCE=4
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20201207T095828Z
DTSTART;VALUE=DATE:20200926
DTEND;VALUE=DATE:20201003
SUMMARY:222
EVENT-ID:2
EVENT-ALLDAY:true
UID:xxx@yyy
RRULE:FREQ=WEEKLY;INTERVAL=5;BYDAY=SA
RECURRENCE-ID;VALUE=DATE:20200926
CREATED:20200916T060405Z
LAST-MODIFIED:20200916T060405Z
SEQUENCE=1
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20201207T095828Z
DTSTART;VALUE=DATE:20200822
DTEND;VALUE=DATE:20200829
SUMMARY:333
EVENT-ID:3
EVENT-ALLDAY:true
UID:xxx@yyy
RRULE:FREQ=WEEKLY;INTERVAL=5;BYDAY=SA
RECURRENCE-ID;VALUE=DATE:20200822
CREATED:20200817T015248Z
LAST-MODIFIED:20200817T015248Z
SEQUENCE=1
END:VEVENT
END:VCALENDAR
```

**Comment by benfortuna** [comment]
Hi Lee, thanks for the feedback. I think for this case the specification would suggest that the last "version" of the event should be the one uses to calculate recurrences (ie. Using the RRULE property). The version is indicated by a combination of the UID and SEQUENCE properties, however in the last example you have two events with the same sequence (should be different). Maybe Google is not following the standard for this case, but happy to explore some more testing here to see how we can better handle such situations.

**Comment by LeeWorrall** [comment]
It seems confluence always adds the override VEVENTs with SEQUENCE=1, regardless of the sequence of the main recurring VEVENT.

I was reading https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/ and it does say

> Once UID 1/SEQUENCE 0 hits UID 1/SEQUENCE 1 (which would
mean something significant about the set of instances
has changed) all bets are off in regards to RECURRENCE-ID
values that previously existed.

but, in practice, when I import these into Outlook or Google they seem to work with the sequences as they are above, and the result matches what was in the confluence calendar.

I guess my main point would be that, even if there is an RRULE along with the RECURRENCE-ID there should still only be a single instance generated _if the RECURRENCE-ID contains a VALUE=DATE or VALUE=DATE-TIME_, right? My understanding is that for a RECURRENCE-ID to generate multiple instances it would have to have RANGE=THISANDFUTURE or RANGE=THISANDPRIOR (which I understand is not widely used or supported). The existing code does component.calculateRecurrenceSet(period) on the (replacement) instance but doesn't check the resulting instances against the RECURRENCE-ID date.

I'm wondering if ComponentGroup.calculateRecurrenceSet should have something more like
```        PeriodList finalPeriods = periods;
        replacements.forEach(component -> {
            RecurrenceId recurrenceId = component.getProperty(Property.RECURRENCE_ID);
            finalPeriods.removeIf(p -> p.getStart().equals(recurrenceId.getDate()));
            component.calculateRecurrenceSet(period).stream()
                    .filter(p -> p.getStart().equals(recurrenceId.getDate()))
                    .forEach(finalPeriods::add);
        });```

**Comment by benfortuna** [comment]
I think this change makes sense, as recurrence-id should replace any matching instances in the recurrence set. Not sure if this will fix the issue you are seeing but I've added the change. thx

**Comment by LeeWorrall** [comment]
Thanks for the quick action Ben. It will solve my issue, I'm already running with a ComponentGroup replacement using that code.
