### ISSUE TITLE
Asia/Karachi timezone calculates offset +6 instead of +5

### ISSUE THREAD

**Issue by rfc2822** [ical4j/ical4j#475]
Hi,

Applies to: ical4j 3.0.21, but seems to also happen with 4.0.0-alpha8 (couldn't test everything)

**Asia/Karachi currently has a fixed offset of +5 (no DST).** It had DST in the history, but it doesn't apply anymore. The [zone file](https://github.com/ical4j/ical4j/blame/ical4j-3.0.21/src/main/resources/zoneinfo/Asia/Karachi.ics) seems to be correct (but maybe you can have a look; see test below).

**ical4j however calculates an offset of +6 for current dates** (e.g. in year 2021), because the observance with the latest onset is not detected correctly (because the latest onset is not calculated correctly).

Expected result: 20210106T200000 Asia/Karachi should be resolved with offset +5
Actual result: 20210106T200000 Asia/Karachi is resolved with offset +6, shifting events by one hour

Example problem report: https://forums.bitfire.at/post/13800

```
package com.example.test;

import net.fortuna.ical4j.model.DateTime;
import net.fortuna.ical4j.model.TimeZone;
import net.fortuna.ical4j.model.TimeZoneRegistry;
import net.fortuna.ical4j.model.TimeZoneRegistryFactory;
import net.fortuna.ical4j.model.component.Observance;

import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class TestKarachi {

    /* ical4j 3.0.21, but seems to also happen with 4.0.0-alpha8 (couldn't test everything) */

    @Test
    public void testTzKarachi() throws Exception {
        TimeZoneRegistry tzReg = TimeZoneRegistryFactory.getInstance().createRegistry();

        TimeZone origKarachi = tzReg.getTimeZone("Asia/Karachi");
        TimeZone karachi = origKarachi;

        long ts1 = 1609945200000L;       // 20210106T150000Z; 20210106T200000 Asia/Karachi
        DateTime dt1 = new DateTime(ts1);
        dt1.setUtc(true);

        System.err.println("Applicable observance: " + karachi.getVTimeZone().getApplicableObservance(dt1));
        /* prints:

           BEGIN:DAYLIGHT
           TZNAME:PKST
           TZOFFSETFROM:+0500
           TZOFFSETTO:+0600
           DTSTART:20020407T000000
           RDATE:20080601T000000
           RDATE:20090415T000000
           END:DAYLIGHT

           which is wrong. Should be this one:

           BEGIN:STANDARD
           TZNAME:PKT
           TZOFFSETFROM:+0600
           TZOFFSETTO:+0500
           DTSTART:20081101T000000
           RRULE:FREQ=YEARLY;UNTIL=20091031T180000Z
           END:STANDARD
        */

        for (Observance obs : karachi.getVTimeZone().getObservances()) {
            System.err.print("Found observance: " + obs.toString());
            System.err.println("Latest onset: " + obs.getLatestOnset(dt1));
            System.err.println();
        }
        /* prints:

        Found observance: BEGIN:STANDARD
        TZNAME:+0530
        TZOFFSETFROM:+042812
        TZOFFSETTO:+0530
        DTSTART:19070101T000000
        END:STANDARD
        Latest onset: 19061231T193148Z

        Found observance: BEGIN:DAYLIGHT
        TZNAME:+0630
        TZOFFSETFROM:+0530
        TZOFFSETTO:+0630
        DTSTART:19420901T000000
        END:DAYLIGHT
        Latest onset: 19420831T183000Z

        Found observance: BEGIN:STANDARD
        TZNAME:+0530
        TZOFFSETFROM:+0630
        TZOFFSETTO:+0530
        DTSTART:19451015T000000
        END:STANDARD
        Latest onset: 19451014T173000Z

        Found observance: BEGIN:STANDARD
        TZNAME:+05
        TZOFFSETFROM:+0530
        TZOFFSETTO:+0500
        DTSTART:19510930T000000
        END:STANDARD
        Latest onset: 19510929T183000Z

        Found observance: BEGIN:STANDARD
        TZNAME:PKT
        TZOFFSETFROM:+0500
        TZOFFSETTO:+0500
        DTSTART:19710326T000000
        END:STANDARD
        Latest onset: 19710325T190000Z

        Found observance: BEGIN:DAYLIGHT
        TZNAME:PKST
        TZOFFSETFROM:+0500
        TZOFFSETTO:+0600               // <- this is what is used for 2021
        DTSTART:20020407T000000
        RDATE:20080601T000000
        RDATE:20090415T000000        // <-- newer than 20081031T180000Z so this one is used
        END:DAYLIGHT
        Latest onset: 20090414T190000Z

        Found observance: BEGIN:STANDARD
        TZNAME:PKT
        TZOFFSETFROM:+0600
        TZOFFSETTO:+0500
        DTSTART:20021006T000000
        END:STANDARD
        Latest onset: 20021005T180000Z

        Found observance: BEGIN:STANDARD
        TZNAME:PKT
        TZOFFSETFROM:+0600
        TZOFFSETTO:+0500                         // <- this is what should be used for 2021
        DTSTART:20081101T000000
        RRULE:FREQ=YEARLY;UNTIL=20091031T180000Z
        END:STANDARD
        Latest onset: 20081031T180000Z                // <- this should be 20091031T180000Z
         */

        assertEquals(5, karachi.getOffset(ts1)/3600000);  // fails!

        DateTime dt2 = new DateTime("20210106T200000", karachi);
        assertEquals(1609945200000L, dt2.getTime());    // fails!
    }

}
```

Thanks for looking at it!

**Comment by devvv4ever** [comment]
Hello Ben,

did you have time to look at this bug? We got another report with the GMT+9:30, Australia/Darwin timezone, too. It is also offset by 1 hour too far.

Thank you very much!

**Comment by benfortuna** [comment]
Apologies, have been busy with work. Will investigate shortly, might need an update to tz definitions.

**Comment by devvv4ever** [comment]
Great, thank you. We've also emailed you about this back in January – an as always we're open to pay/donate for the efforts you have as we're happily using your library in our apps!

**Comment by benfortuna** [comment]
@rfc2822 I think I've identified the issue with `Asia/Karachi`, not quite sure of the best fix just yet..

The latest STANDARD definition isn't being recognized due to the way the RRULE is configured:

```
BEGIN:STANDARD
TZNAME:PKT
TZOFFSETFROM:+0600
TZOFFSETTO:+0500
DTSTART:20081101T000000
RRULE:FREQ=YEARLY;UNTIL=20091031T180000Z
END:STANDARD
```

The rule has `FREQ=YEARLY`, but is cut off at `20091031T180000Z`. This is just short of one year, so the 2009 occurrence isn't being calculated.

As such the DAYLIGHT observance has a 2009 occurrence so it takes precedence.

I will first check for any updates in the latest timezone definitions, but if it's still the same then I may need to look a bit closer at the code for recurrence calculations.

**Comment by xBelladonna** [comment]
I'm just popping in to say I've just experienced this issue regarding the Austraila/Darwin timezone in the DAVx5 android application using this library. It would be amazing if this could be fixed since it's the last thing keeping me from- good lord I just watched your comment get posted! You work fast.

**Comment by benfortuna** [comment]
@xBelladonna I think the Darwin issue might be something else, I need to check the rules as they have a lot more in that definition. 

Anyway will try to have a look at that shortly.

**Comment by xBelladonna** [comment]
Great, thank you! I'd have a crack at it but my area is machine learning, not timezones and java and I'll wager you know far more about this than I. I'd love to donate a little if you've got a paypal or something else though, your work is enabling me to finally stop depending on Google and Microsoft!

**Comment by benfortuna** [comment]
@xBelladonna thanks for the support, there's a QR code/link on the main site - http://ical4j.github.io/

And well done for ditching Google/Microsoft!  I am still yet to achieve that myself.. ;-)

**Comment by rfc2822** [comment]
Hi! Thanks for ical4j 3.0.23/.24! I have seen that it changes the Apache CommonsLang3 dependency to lang3-3.10, which requires Java 8 and thus are not fully supported on Android below 7 (Android can rewrite Java 8 bytecode for lower Android versions, but doesn't provide the full Java 8 API). So it can't be used on Android 6 (or below) anymore.

Would it be possible to lower that to the versions previously used again? (or the latest which don't require Java 8). I think this would also make sense when you see the 3.0.xx branch as pure bug fix branches, while 4.x comes with new dependencies.

**Comment by benfortuna** [comment]
Ah, ok I didn't realise this. Let me check if I can downgrade again (I thought it was a minor version increment but maybe I was wrong).

**Comment by rfc2822** [comment]
Thanks, that would really be helpful.

(I had made the same "mistake" some time ago with DAVx5 and had to find out the latest Java 7 versions and go back to these ones)

**Comment by benfortuna** [comment]
@rfc2822 just want to check if the `Australia/Darwin` issue is also fixed. If not perhaps we can make a new ticket for that.

**Comment by xBelladonna** [comment]
I don't have a way to test this myself since I haven't integrated the library into anything and found the bug through another app that does, however I'd be happy to attempt anything from simple tests to writing Java unit tests, just let me know if I can help.

**Comment by devvv4ever** [comment]
@xBelladonna we've now published an open beta, but if you don't use the Google Play Store you can't join it right now. We will be waiting a few days if the beta works without any issues and then push it to production level. At that time it will also be tagged for F-Droid release which will then be built by the f-droid-team after that. So that might take a little while, if you have the f-droid version.

**Comment by rfc2822** [comment]
I have tested with Australia/Darwin and can confirm that times are still shifted by one hour. So I'll create a separate issue for that.

**Comment by rfc2822** [comment]
The new report: https://github.com/ical4j/ical4j/issues/491
