### ISSUE TITLE
Parsing ics file with invalid VTIMEZONE

### ISSUE THREAD

**Issue by huubvv** [ical4j/ical4j#476]
Hi,

I need to parse a calendar file generated by a different application which I do not control. 
The VTIMEZONE section seems to be missing a DTSTART and END time. ( See below)
This leads to the error below:
[main] ERROR net.fortuna.ical4j.model.component.Observance  - Unexpected error calculating initial onset
net.fortuna.ical4j.model.ConstraintViolationException: Missing DTSTART property
	at net.fortuna.ical4j.model.Component.getRequiredProperty(Component.java:212)
	at net.fortuna.ical4j.model.component.Observance.getLatestOnset(Observance.java:161)
	at net.fortuna.ical4j.model.component.VTimeZone.getApplicableObservance(VTimeZone.java:254)

What do you suggest ? How can I handle this in the best way?

Regards,
    Huub

BEGIN:VCALENDAR
VERSION:2.0
PRODID:xxx
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
X-LIC-LOCATION:Europe/Amsterdam
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE

**Comment by benfortuna** [comment]
Hi, what version of ical4j are you using? We might be able to ignore the error when RELAXED_VALIDATION flag is enabled.

**Comment by huubvv** [comment]
Hi Ben,
I am using 3.0.29

**Comment by benfortuna** [comment]
I've added a fix to avoid exceptions when `DTSTART` is not specified, however the results may still not be valid when using with the example definition above.

The problem with the above definition is there is no difference in when to apply the `DAYLIGHT` vs `STANDARD` definition, so will result in the DAYLIGHT offset being used always (as it is the last definition).
