### ISSUE TITLE
Error on loading timezone registry from tzurl.org

### ISSUE THREAD

**Issue by MarcinuB** [ical4j/ical4j#482]
**Describe the bug**
This is the same issue as 
https://github.com/ical4j/ical4j/issues/464

tzurl.org is down and our tests are failing 

**To Reproduce**
TimeZoneRegistry registry = TimeZoneRegistryFactory.getInstance().createRegistry();
TimeZone timezone = this.registry.getTimeZone("Asia/Bangkok");

System.out.println(timezone); // is null

**Expected behavior**
Actual Timezone should return

**Screenshots**

![image](https://user-images.githubusercontent.com/8589350/106733054-51ea9900-6609-11eb-8fbf-a4955f4f24a3.png)

**Environment (please complete the following information):**
 - OS: Linux

**Additional context**
na

**Comment by benfortuna** [comment]
Apologies, fix applied but may take some time to propagate. Please refresh DNS caches and retry in an hour or so.

**Comment by MarcinuB** [comment]
Thanks @benfortuna for fixing this. Did you had a chance to document how to self-host timezones as you've mentioned in https://github.com/ical4j/ical4j/issues/464 ? That would be really helpful !

**Comment by benfortuna** [comment]
Please see the latest changes to timezone updates here:

http://ical4j.github.io/2022/11/06/timezone-updates-and-tzurl-org.html

This includes the ability to self-host timezones, I will provide a containerised implementation of tzurl.org shortly.
