### ISSUE TITLE
Getting NoClassDefFoundError

### ISSUE THREAD

**Issue by jjangir610** [ical4j/ical4j#486]
I am developing a spring-boot application and everything works fine for me on the local machine. but once I deploy my docker image on the server, I start receiving the NoClassDefFoundError Exception

```
java.lang.NoClassDefFoundError: javax/cache/configuration/Configuration
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:275) ~[ical4j-3.0.0.jar!/:na]
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:81) ~[ical4j-3.0.0.jar!/:na]
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125) ~[ical4j-3.0.0.jar!/:na]
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116) ~[ical4j-3.0.0.jar!/:na]
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48) ~[ical4j-3.0.0.jar!/:na]
pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105) ~[ical4j-3.0.0.jar!/:na]
```

I tried with everything, Added `ical4j.properties` and also tried with         `System.setProperty("net.fortuna.ical4j.timezone.cache.impl", "net.fortuna.ical4j.util.MapTimeZoneCache");`

Java version: 11
Using: Maven
iCal version: 3.0.0

**Comment by juvs** [comment]
> I am developing a spring-boot application and everything works fine for me on the local machine. but once I deploy my docker image on the server, I start receiving the NoClassDefFoundError Exception
> 
> ```
> java.lang.NoClassDefFoundError: javax/cache/configuration/Configuration
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:275) ~[ical4j-3.0.0.jar!/:na]
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:81) ~[ical4j-3.0.0.jar!/:na]
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125) ~[ical4j-3.0.0.jar!/:na]
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116) ~[ical4j-3.0.0.jar!/:na]
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48) ~[ical4j-3.0.0.jar!/:na]
> pcs-669667f84b-xtfdx pcs 	at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:105) ~[ical4j-3.0.0.jar!/:na]
> ```
> 
> I tried with everything, Added `ical4j.properties` and also tried with `System.setProperty("net.fortuna.ical4j.timezone.cache.impl", "net.fortuna.ical4j.util.MapTimeZoneCache");`
> 
> Java version: 11
> Using: Maven
> iCal version: 3.0.0

@jjangir610 Did you solve this issue?
