### ISSUE TITLE
Potential security problem with codecov.io

### ISSUE THREAD

**Issue by renner** [ical4j/ical4j#492]
This is to inform you about a potential security problem with your Travis CI configuration, particularly with this line:

https://github.com/ical4j/ical4j/blob/develop/.travis.yml#L23

We are building Linux packages from your sources and our security team found the problematic line of code. Instead of calling `curl` to download the script each time it should be safer to locally store the script. Here is some background information:

> A security breach relating to code verification service Codecov was
> published on April 15th and got media attention over the past week.
> Around end of January, customer-facing systems of codecov.io were
> compromised which in turn led to potential compromise of customer CI/CD
> pipelines.
>
> As part of Codecov's integration into CI/CD pipelines, an upload script
> gets downloaded from https://codecov.io/bash. This script was replaced
> by adversaries with a modified version which uploads the caller's
> environment variables to an adversary-controlled IP address. As this
> script is used in CI/CD deployments the likelihood for secret leakage is
> high. Potential leaks are CI/CD target system credentials or signing
> keys for code or binaries.
> 
> The Codecov breach notification was published on April 15th:
> https://about.codecov.io/security-update/

**Comment by benfortuna** [comment]
Fix applied in develop branch
