### ISSUE TITLE
Significant GC activity due to repeated creation of immutable thread-safe identical objects

### ISSUE THREAD

**Issue by nealeu** [ical4j/ical4j#496]
I've just been looking into an out of memory issue on a calendar server and spotted that ValidationRule was over 10% of the heap dump, so I investigated and found that identical instances are being created unnecessarily (in our case 600,000+ instances in a very short time).

The constructor for ValidationRule is invoked every time an object that may need validating is created, yet there are limited combinations of this which could all be made `static final`.

For example in Location.java

```
private final Validator<Property> validator = new PropertyValidator(Arrays.asList(
        new ValidationRule(OneOrLess, ALTREP, LANGUAGE, VVENUE)));
```
In this case not only could ValidationRule be a single instance, but the PropertyValidator instance could also be static.

@benfortuna Would you be open to a pull request to address this?

**Comment by benfortuna** [comment]
Hi Neale,

Yes definitely would welcome any improvements to the code. I'm sure there are many optimisations that are yet to be discovered. :-)
