### ISSUE TITLE
VAlarm with duration of minus two days not correctly parsed (minus sign appears twice)

### ISSUE THREAD

**Issue by danielgrigore** [ical4j/ical4j#498]
**Describe the bug**
When parsing an event that has an alarm with a duration of two days the trigger is not correctly parsed (minus sign appears twice) 

**To Reproduce**
1. Create an event with an alarm
2. Set the trigger of the alarm to two days before the event
3. Export the event to ics format
4. Use CalendarBuilder to parse the exported event
5. Check the trigger of the alarm

Here's the code
```
Calendar original = new Calendar();
VEvent vEvent = new VEvent();
original.getComponents().add(vEvent);
VAlarm alarm = new VAlarm(Duration.ofDays(2).negated());
vEvent.getAlarms().add(alarm);

System.out.println(original.toString());
Calendar build = new CalendarBuilder().build(new ByteArrayInputStream(original.toString().getBytes()));
System.out.println(build);

assertEquals(original, build);
```
And here's the generated ics content of the code above.

Original:
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20210618T114917Z
BEGIN:VALARM
TRIGGER:-P2D
END:VALARM
END:VEVENT
END:VCALENDAR
```

Parsed:
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTAMP:20210618T114917Z
BEGIN:VALARM
TRIGGER:-P-2D
END:VALARM
END:VEVENT
END:VCALENDAR
```
Notice that initially the trigger has the value **-P2D** and after parsing it became **-P-2D**

**Expected behavior**
The parsed trigger should have the same duration/value as the original one.

**Environment (please complete the following information):**
 - Linux: Ubuntu: 20.04.02
 - Java Version: 8 (openjdk version "1.8.0_292")
 - ical4j Version: 3.0.25

Please let me know if you need any details. 
Thanks,

**Comment by benfortuna** [comment]
Thanks @danielgrigore for the bug report, I've created a PR with fix, will release shortly: #499
