### ISSUE TITLE
Exception Text cannot be parsed to a Duration

### ISSUE THREAD

**Issue by spierjoe** [ical4j/ical4j#502]
On a Mac, a calendar entry with the reminder "alert at time of event" can be made.
The incorrectly formatted value for triggers is generated by the Mac calendar application.

The parser throws an exception:
net.fortuna.ical4j.data.ParserException: Error at line 51,940: Text cannot be parsed to a Duration
at net.fortuna.ical4j.data.CalendarParserImpl.parse (CalendarParserImpl.java:158)
at net.fortuna.ical4j.data.CalendarBuilder.build (CalendarBuilder.java:183)
at net.fortuna.ical4j.data.CalendarBuilder.build (CalendarBuilder.java:171)
...

Extract from the event:
```
BEGIN:VALARM
ACTION:AUDIO
TRIGGER:PT
ATTACH:Chord
X-WR-ALARMUID:43F93F98-6524-4F9A-A1A8-02E9A18E4D3E
END:VALARM
```
The problem is the entry: **TRIGGER:PT**

The CompatibilityHints.KEY_RELAXED_PARSING doesn't help.

```
StringReader stringIn = new StringReader(myCalendarString);
CompatibilityHints.setHintEnabled(CompatibilityHints.KEY_RELAXED_PARSING, true);
CalendarBuilder builder = new CalendarBuilder();
calendar = builder.build(stringIn);
```

**Comment by benfortuna** [comment]
Note that `TRIGGER:PT` is invalid, but I'll add support for it (i.e. ZERO duration) in the next release.
