### ISSUE TITLE
CompatibilityHints not testing Configurator result correctly

### ISSUE THREAD

**Issue by douglm** [ical4j/ical4j#519]
**Describe the bug**

The test is here: 
`    public static boolean isHintEnabled(final String key) {
        if (HINTS.get(key) != null) {
            return HINTS.get(key);
        }
        return "true".equals(Configurator.getProperty(key));
    }
`
That last test is incorrect as Configurator.getProperty returns an Optional.
This should work:
`return "true".equals(Configurator.getProperty(key).orElse("false"));`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux, Android]
 - Java Version [e.g. 7, 8, 9]
 - 8 and 11

**Additional context**

**Comment by benfortuna** [comment]
Good catch, thanks. Not the first time I've made that mistake with refactoring code to use Optional.. ;-)

Fix will be in the next release.
