### ISSUE TITLE
Parse Exceptions in some embedded HTML

### ISSUE THREAD

**Issue by kiddkaffeine** [ical4j/ical4j#528]
**Describe the bug**
A fraction of ICAL files seem to cause parser errors in embedded HTML

**To Reproduce**
Submit the following file, with relaxed parsing.

```
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
METHOD:REQUEST
PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
VERSION:2.0
BEGIN:VEVENT
DTEND:20211001T213000Z
DTSTAMP:20210929T234622Z
DTSTART:20211001T210000Z
LAST-MODIFIED:20210929T234622Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:[EXTERNAL] Redacted
TRANSP:OPAQUE
UID:redacted
X-ALT-DESC;FMTTYPE=text/html:<style type="text/css">#EmailBody a color:#00
 338E\; </style>\n<table style="max-width: 600px\; font-family: arial\; fo
 nt-size: 13pt\;">\n<tr><td><div id="EmailHeader" style="text-align: center
 \; background-color: #ffffff\;" >\n
END:VEVENT
END:VCALENDAR
```

(I have removed other fields in this file because they some may contain personal information.)

**Expected behavior**
The file parses.

**Screenshots**
This error is thrown:
net.fortuna.ical4j.data.ParserException: Error at line 19:Expected [61], read [58]
Other files with similar structure exhibit the same error, although the read byte may differ.

**Environment (please complete the following information):**
iCal4j 3.1.0, JDK 11

**Additional context**

**Comment by benfortuna** [comment]
I just tried your example and it parses ok for me. The only Compatibility Hint enabled is `RELAXED_UNFOLDING`, but I don't think that is the cause.

Can you confirm which (if any) settings you have in ical4j.properties?

**Comment by kiddkaffeine** [comment]
This does indeed seem to fix it, thank you.  Our settings were:

net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache
ical4j.parsing.relaxed=true

If there are other suggested properties, I'd love to know -- I thought the relaxed parser setting would have covered this.
