### ISSUE TITLE
Adding new property does not lead to adding the property to collection

### ISSUE THREAD

**Issue by BootGenius** [ical4j/ical4j#538]
https://github.com/ical4j/ical4j/blob/01f955d01df290980ec13a500e3a0be78dab057d/src/main/java/net/fortuna/ical4j/model/PropertyList.java#L64

Hi. I was trying to use the latest version of ical4j library and there is a mistake in the code. If you take a look, you will see that adding properties does not lead to  adding these properties to collection

**Comment by BootGenius** [comment]
Just try this code and you will see it's not working
calendar.getProperties().add(new ProdId("***")))
As the result getProperties of the calendar instance does not contain added property

**Comment by benfortuna** [comment]
Which version of ical4j are you using? There is an important change with the 4.0 release in that you need to use the following convention instead of what you have described:

```calendar.add(new ProdId("***")))```

For ical4j 3.x the above example should work.

**Comment by BootGenius** [comment]
I tried to use 4.0.0-alpha10 because I have java 16 and Spring Boot, but the latest release (3.1.1) has a lot of incompatibilities with the libraries I use in the Spring Boot application.

**Comment by BootGenius** [comment]
Thanks for the hint. The code you provided works
`calendar.add(new ProdId("***")))`
