### ISSUE TITLE
ClassCastException in Cal4j beta 1

### ISSUE THREAD

**Issue by jamieb22** [ical4j/ical4j#54]
ClassCastException Back traces

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
|                                                                                                   Name                                                                                                   |    Count     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
|  +---net.fortuna.ical4j.data.CalendarBuilder.updateTimeZone(Property, TimeZone) CalendarBuilder.java:353                                                                                                 |  238   96 %  |
|  | |                                                                                                                                                                                                     |              |
|  | +---net.fortuna.ical4j.data.CalendarBuilder.access$300(CalendarBuilder, Property, TimeZone) CalendarBuilder.java:68                                                                                   |              |
|  |   |                                                                                                                                                                                                   |              |
|  |   +---net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(String, String) CalendarBuilder.java:278                                                                                   |              |
|  |     |                                                                                                                                                                                                 |              |
|  |     +---net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:328                                                         |              |
|  |       |                                                                                                                                                                                               |              |
|  |       +---net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$1700(CalendarParserImpl$ParameterParser, StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:283             |              |
|  |         |                                                                                                                                                                                             |              |
|  |         +---net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:271                                                 |              |
|  |           |                                                                                                                                                                                           |              |
|  |           +---net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:208                                                    |              |
|  |             |                                                                                                                                                                                         |              |
|  |             +---net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1100(CalendarParserImpl$PropertyParser, StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:190         |              |
|  |               |                                                                                                                                                                                       |              |
|  |               +---net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:173                                            |              |
|  |                 |                                                                                                                                                                                     |              |
|  |                 +---net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:383                                             |              |
|  |                   |                                                                                                                                                                                   |              |
|  |                   +---net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$900(CalendarParserImpl$ComponentParser, StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:367  |              |
|  |                     |                                                                                                                                                                                 |              |
|  |                     +---net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(StreamTokenizer, Reader, ContentHandler) CalendarParserImpl.java:171                                      |              |
|  |                       |                                                                                                                                                                               |              |
|  |                       +---net.fortuna.ical4j.data.CalendarParserImpl.parse(Reader, ContentHandler) CalendarParserImpl.java:122                                                                        |              |
|  |                                                                                                                                                                                                       |              |
|  +---com.stimulus.archiva.connect.google.GoogleUserSync.getHistoryID(GoogleUserAdapter) GoogleUserSync.java:394                                                                                          |    9    4 %  |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+

Generated by YourKit Java Profiler 2014 build 14114 13 Nov 2015 10:50:07 AM

**Comment by benfortuna** [comment]
older versions now in maintenance mode only
