### ISSUE TITLE
NullPointer exception in ical4j beta 1

### ISSUE THREAD

**Issue by jamieb22** [ical4j/ical4j#55]
Back traces

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|                                                                                                  Name                                                                                                  |   Count    |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+
|  +---java.lang.Class.forName(String) Class.java:264                                                                                                                                                    |  2   33 %  |
|  |                                                                                                                                                                                                     |            |
|  +---java.util.Properties$LineReader.readLine() Properties.java:434                                                                                                                                    |  2   33 %  |
|  | |                                                                                                                                                                                                   |            |
|  | +---java.util.Properties.load(InputStream) Properties.java:341                                                                                                                                      |            |
|  |   |                                                                                                                                                                                                 |            |
|  |   +---net.fortuna.ical4j.model.TimeZoneRegistryImpl.<clinit>() TimeZoneRegistryImpl.java:107                                                                                                        |  1   17 %  |
|  |   | |                                                                                                                                                                                               |            |
|  |   | +---net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry() DefaultTimeZoneRegistryFactory.java:48                                                                             |            |
|  |   |   |                                                                                                                                                                                             |            |
|  |   |   +---net.fortuna.ical4j.data.CalendarBuilder.<init>() CalendarBuilder.java:104                                                                                                                 |            |
|  |   |     |                                                                                                                                                                                           |            |
|  |   |     +---com.stimulus.archiva.plugin.blob.ICalBlob.parse(Data) ICalBlob.java:81                                                                                                                  |            |
|  |   |       |                                                                                                                                                                                         |            |
|  |   |       +---com.stimulus.archiva.plugin.blob.AbstractCommonBlob.init(Data, PxBlobID, Principal) AbstractCommonBlob.java:63                                                                        |            |
|  |   |         |                                                                                                                                                                                       |            |
|  |   |         +---com.stimulus.archiva.plugin.blob.ICalBlob.init(Data, PxBlobID, Principal) ICalBlob.java:1                                                                                           |            |
|  |   |           |                                                                                                                                                                                     |            |
|  |   |           +---com.stimulus.archiva.blob.Blob.init(Data, BlobID, FieldValues, Principal) Blob.java:110                                                                                           |            |
|  |   |             |                                                                                                                                                                                   |            |
|  |   |             +---com.stimulus.archiva.service.BlobService.insertBlob(Principal, Connection, String, String, String, Data, boolean, int, TimeUnit) BlobService.java:661                           |            |
|  |   |               |                                                                                                                                                                                 |            |
|  |   |               +---com.stimulus.archiva.connect.exchange.ExchangeConnectionHelper.updateBlob(ExchangeLink$ExchangeItem, String, boolean) ExchangeConnectionHelper.java:45                        |            |
|  |   |                 |                                                                                                                                                                               |            |
|  |   |                 +---com.stimulus.archiva.connect.exchange.ExchangeSync$ObjectFoundCallback.createItem(ExchangeLink$ExchangeItem) ExchangeSync.java:339                                          |            |
|  |   |                   |                                                                                                                                                                             |            |
|  |   |                   +---com.stimulus.archiva.connect.exchange.AbstractEWSExchangeLink.syncItems(ExchangeLink$ExchangeFolder, ExchangeLink$ItemListener, String) AbstractEWSExchangeLink.java:885  |            |
|  |   |                     |                                                                                                                                                                           |            |
|  |   |                     +---com.stimulus.archiva.connect.exchange.EWSOffice365Link.syncItems(ExchangeLink$ExchangeFolder, ExchangeLink$ItemListener, String) EWSOffice365Link.java:1                |            |
|  |   |                                                                                                                                                                                                 |            |
|  |   +---net.fortuna.ical4j.util.Configurator.<clinit>() Configurator.java:57                                                                                                                          |  1   17 %  |
|  |                                                                                                                                                                                                     |            |
|  +---com.stimulus.archiva.monitor.StatusService$Summary.getVolumesStatus() StatusService.java:345                                                                                                      |  1   17 %  |
|  |                                                                                                                                                                                                     |            |
|  +---org.subethamail.smtp.command.AuthCommand.execute(String, Session) AuthCommand.java:88                                                                                                             |  1   17 %  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------+

Generated by YourKit Java Profiler 2014 build 14114 13 Nov 2015 10:53:21 AM

**Comment by benfortuna** [comment]
older versions now in maintenance mode only
