### ISSUE TITLE
Incorrect next date computed for `RRule` if `tzurl.org` is unreachable

### ISSUE THREAD

**Issue by moadi** [ical4j/ical4j#551]
**Describe the bug**

ical4j version - 3.0.27

Hello - we noticed an issue when invoking `net.fortuna.ical4j.model.Recur#getNextDate` if the method `net.fortuna.ical4j.model.TimeZoneRegistry#getTimeZone` fails to update the timezone definition via `tzurl.org`.

Given the following code:

```
        RRule rRule = new RRule(recurringExpression);
        Recur recur = rRule.getRecur();
        net.fortuna.ical4j.model.TimeZoneRegistry registry =
                net.fortuna.ical4j.model.TimeZoneRegistryFactory.getInstance().createRegistry();
        net.fortuna.ical4j.model.TimeZone tz = registry.getTimeZone(zoneId.getId());
        Date date = recur.getNextDate(
                new net.fortuna.ical4j.model.DateTime(new Date(seedTimestamp), tz),
                new net.fortuna.ical4j.model.DateTime(new Date(timestamp), tz));
```

given the following values for the params:

`recurringExpression`: `FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR`
`zoneid`: `America/Toronto`
`seedTimestamp`: `1634547600000L` (`Monday, October 18, 2021 9:00:00 AM UTC / Monday, October 18, 2021 5:00:00 AM [GMT-04:00] DST`)
`timestamp`: `1646906400001L` (`Thursday, March 10, 2022 10:00:00.001 AM UTC / Thursday, March 10, 2022 5:00:00.001 AM [GMT-05:00]`)

the expected output for the date is supposed to be `1646992800000 `, ie `Friday, March 11, 2022 10:00:00 AM UTC / Friday, March 11, 2022 5:00:00 AM [GMT-05:00]`. However, when this code was being executed we had the following exception in our logs:

```
java.io.IOException: Server returned HTTP response code: 503 for URL: http://tzurl.sgp1.cdn.digitaloceanspaces.com/zoneinfo/America/Toronto.ics
```

consequently, `registry.getTimeZone(zoneId.getId());` returned `null` and the date was computed as `Friday, March 11, 2022 9:00:00 AM UTC / Friday, March 11, 2022 4:00:00 AM [GMT-05:00]`

reading the timezone docs, it seems we can disable the remote updates via the following property:

```
        System.setProperty("net.fortuna.ical4j.timezone.update.enabled", "false");
```

and we continue to work correctly.

I was wondering if this is safe to disable for the long term? Are there any issues we should be aware of?

Also, if the remote update fails, is returning `null` intentional? Or should it provide the timezone as constructed from the zoneinfo files provided in the library?

**Comment by benfortuna** [comment]
Yes, it is safe to disable the automatic timezone updates. iCal4j includes a copy of all the timezone definitions internally, so it will just use the included definitions if updates are disabled.

The only caveat is that new timezone updates are published maybe once every couple of months, and the included definitions may not include the latest changes.

I'll also see if we can improve error handling to avoid the bug described above.

**Comment by benfortuna** [comment]
1. Yes, I will try to update the zoneinfo definitions included in new releases of ical4j, however realistically it may not be as often as the tzurl.org site. Also note, when we move to ical4j v4 on the main branch I probably will no longer update definitions in the v3 maintenance branch unless via specific request.

2. I think a static`TimeZoneRegistryImpl` should be safe if you don't parse custom timezone definitions. The issue with sharing a static registry arises when you are parsing iCalendar data that includes custom timezone definitions, as this will register those timezones in the registry (see `DefaultContentHandler.endComponent`), and it may override the default definitions provided by the library.

**Comment by benfortuna** [comment]
Regarding HTTPS, initially we didn't have this enabled and I wasn't sure how well supported it would be by some clients (e.g. Android phones, etc.). 

I think I am going to enable HTTPS redirection for all requests on the tzurl.org site and see if this causes any major issues, in which case I'll revert to explicit HTTP/HTTPS support.

But now that HTTPS is working correctly on the tzurl.org site I will start to use this in all zoneinfo definitions going forward.

**Comment by MikeN123** [comment]
@benfortuna the https redirect seems to break all iCal4j clients. A raw `URLConnection` is opened, which does not handle HTTP redirects, thus iCal4j tries to parse the following response body:

```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>
```

For iCal4j versions below 3.1.1 this breaks pretty badly, it just crashes. For newer versions it just logs this:

```
net.fortuna.ical4j.data.ParserException: Error at line 1:Expected [BEGIN], read [<html>]
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:542)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:192)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:163)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:197)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:185)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:172)
	at net.fortuna.ical4j.model.TimeZoneUpdater.updateDefinition(TimeZoneUpdater.java:111)
	at net.fortuna.ical4j.model.TimeZoneLoader.loadVTimeZone(TimeZoneLoader.java:85)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.getTimeZone(TimeZoneRegistryImpl.java:193)
```

**Comment by benfortuna** [comment]
Thanks for letting me know. There was always a redirection in place but I will revert to previous shortly and confirm the issue.

**Comment by benfortuna** [comment]
So I've identified it wasn't so much the redirection but the change in protocol from HTTP to HTTPS that breaks the client update. 

For example, Java `URLConnection` can't handle this type of redirect:

`http://tzurl.org/zoneinfo/America/Toronto -> https://tzurl.org/zoneinfo/America/Toronto`

I have an alternate domain to test this at: https://www2.tzurl.org, which works ok when I explicitly change the embedded update URL to `https://www2.tzurl.org/...`.

However, as should be expected HTTPS is significantly slower than HTTP, especially when retrieving many tz definitions, so I will likely publish a separate zoneinfo collection (with HTTPS update URLs) rather than forcing HTTPS on the default collection at this stage.

I expect to make HTTPS the default at some point in the future.

**Comment by benfortuna** [comment]
Please note the latest changes to timezone updates in iCal4j:

http://ical4j.github.io/2022/11/06/timezone-updates-and-tzurl-org.html

This includes fixes for https (this is now the default).

**Comment by moadi** [comment]
Hi Ben - thank you so much for fixing the issue and the docs! We will upgrade our library soon.
