### ISSUE TITLE
Timezone update server dependency

### ISSUE THREAD

**Issue by pieroxy** [ical4j/ical4j#553]
**Describe the bug**
The same problem as in https://github.com/ical4j/ical4j/issues/317 happened again on Friday. As a result, plenty of exceptions in my logs and plenty of ICS emails not generated

I see the fix is to declare `net.fortuna.ical4j.timezone.update.enabled=false` in my `ical4j.properties`, so I did it.

IMO this should be the default behavior if the update server is unreachable instead of throwing an exception to the caller. Logging an error message would be the way to go.

**To Reproduce**
1. Cut access to the update timezone server (cut internet of add server to hos file)
2. Try to execute `TimeZoneRegistryFactory.getInstance().createRegistry().getTimeZone("Europe/Paris")`

**Expected behavior**
If the update of the timezone fails, it should act as if the flag `net.fortuna.ical4j.timezone.update.enabled=false` was set

**Environment (please complete the following information):**
Any

**Comment by benfortuna** [comment]
Can you provide more details about the type of exception you received? Currently it should log a warning when unable to update timezone definitions from the update server, i.e:

```
try {
                    URLConnection connection = openConnection(tzUrl.getUri().toURL());

                    final CalendarBuilder builder = new CalendarBuilder();
                    final Calendar calendar = builder.build(connection.getInputStream());
                    final VTimeZone updatedVTimeZone = calendar.getComponent(Component.VTIMEZONE);
                    if (updatedVTimeZone != null) {
                        return updatedVTimeZone;
                    }
                } catch (IOException | ParserException e) {
                    LoggerFactory.getLogger(TimeZoneLoader.class).warn("Error updating timezone definition", e);
                }
```

If you see a different exception let me know and I can add it to the error handling. Otherwise to suppress the warning you can also configure your logging to ERROR level and above for `net.fortuna.ical4j.model` package.

**Comment by MikeN123** [comment]
What iCal4j version are you on? Older versions (i think pre-3.1.1) crash, but the latest version shouldn't.

**Comment by pieroxy** [comment]
I am using version 3.0.11, but as previously mentioned, it is the fact that ical4j doesn't hold a local store for timezones that bugs me. Every time the server is down, I do not have a timezone at my disposal. I'm going to have to build my own local store for this...

**Comment by benfortuna** [comment]
The library does include a copy of all the timezone definitions current at release, but as mentioned in earlier versions the server outage was not handled as gracefully as later versions.

If you cannot upgrade then I would suggest to disable the update server by adding this to your ical4j.properties:

`net.fortuna.ical4j.timezone.update.enabled=false`

**Comment by benfortuna** [comment]
Please note the latest changes to timezone updates here:

http://ical4j.github.io/2022/11/06/timezone-updates-and-tzurl-org.html

Reviewing the original issue I believe it does behave the expected way, even with older versions. Warning logs can be suppressed via log configurations.
