### ISSUE TITLE
Properties are not extracted

### ISSUE THREAD

**Issue by rudivk** [ical4j/ical4j#562]
**Describe the bug**
I am parsing a calendar with the following code:

`this.calendar = new CalendarBuilder().build(bodyPart.getInputStream());
Optional<Property> uid = this.calendar.getProperty(Property.UID);
Optional<Property> summary = this.calendar.getProperty(Property.SUMMARY);
Optional<DateProperty<Temporal>> start = this.calendar.getProperty(Property.DTSTART);
        Optional<DateProperty<Temporal>> end = this.calendar.getProperty(Property.DTEND);
        if (start.isPresent() && end.isPresent()) {
            return Range.closedOpen(Instant.from(start.get().getDate()), Instant.from(end.get().getDate()));
        } else if (start.isPresent()) {
            return Range.atLeast(Instant.from(start.get().getDate()));
        } else if (end.isPresent()) {
            return Range.atMost(Instant.from(end.get().getDate()));
        } else {
            return null;
        }`

The contents of the input stream should be the following:
`BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Romance Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=yzungula@linkedstrategies.com;SENT-BY="mailto:geert.haegens@amp
 lifino.com":mailto:yzungula@linkedstrategies.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Ticket 107
 4:mailto:ticket1074@connect-infinity.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Geert Haeg
 ens:mailto:geert.haegens@amplifino.com
ATTACH:CID:441124BA733CBF48B087948CD4F25EA3@eurprd04.prod.outlook.com
DESCRIPTION;LANGUAGE=en-US:\n\n-----Original Appointment-----\nFrom: yzungu
 la@linkedstrategies.com<mailto:yzungula@linkedstrategies.com> <yzungula@li
 nkedstrategies.com<mailto:yzungula@linkedstrategies.com>>\nSent: 05 April 
 2022 14:18\nTo: yzungula@linkedstrategies.com<mailto:yzungula@linkedstrate
 gies.com>\; ticket1074@connect-infinity.com<mailto:ticket1074@connect-infi
 nity.com>\; Geert Haegens\nSubject: Yamkela Zungula's Calendar test\nWhen:
  05 April 2022 14:18-15:18 (UTC+01:00) Brussels\, Copenhagen\, Madrid\, Pa
 ris.\nWhere: https://us02web.zoom.us/j/6223941191?pwd=UzlJaHBVQmE2YzJkVUVW
 eEY2NTByUT09\n\nYou have been invited to the following event.\nYamkela Zun
 gula's Calendar test\nWhen\nTue Apr 5\, 2022 2:17pm – 3:17pm South Afric
 a Standard Time\nWhere\nhttps://us02web.zoom.us/j/6223941191?pwd=UzlJaHBVQ
 mE2YzJkVUVWeEY2NTByUT09 (map<https://www.google.com/url?q=https%3A%2F%2Fus
 02web.zoom.us%2Fj%2F6223941191%3Fpwd%3DUzlJaHBVQmE2YzJkVUVWeEY2NTByUT09&sa
 =D&source=calendar&usd=2&usg=AOvVaw2j2lZecx-i-y61EL1My7i0>)\nCalendar\ngee
 rt.haegens@amplifino.com<mailto:geert.haegens@amplifino.com>\nWho\n•\nyz
 ungula@linkedstrategies.com<mailto:yzungula@linkedstrategies.com> - organi
 zer\n•\nticket1074@connect-infinity.com<mailto:ticket1074@connect-infini
 ty.com>\n•\ngeert.haegens@amplifino.com<mailto:geert.haegens@amplifino.c
 om>\nmore details »<https://calendar.google.com/calendar/event?action=VIE
 W&eid=dGVodGc4dGZyOWtwcGtlbWQ2bGdycTdhc28gZ2VlcnQuaGFlZ2Vuc0BhbXBsaWZpbm8u
 Y29t&tok=MjkjeXp1bmd1bGFAbGlua2Vkc3RyYXRlZ2llcy5jb21lZGU2MzYxNGY2NDNhZmZkN
 2MzYjIxZmYyNWVmMmEwYTViODAxNmRl&ctz=Africa%2FJohannesburg&hl=en&es=0>\nYam
 kela Zungula is inviting you to a scheduled Zoom meeting.\n\nJoin Zoom Mee
 ting\nhttps://us02web.zoom.us/j/6223941191?pwd=UzlJaHBVQmE2YzJkVUVWeEY2NTB
 yUT09<https://www.google.com/url?q=https%3A%2F%2Fus02web.zoom.us%2Fj%2F622
 3941191%3Fpwd%3DUzlJaHBVQmE2YzJkVUVWeEY2NTByUT09&sa=D&source=calendar&usd=
 2&usg=AOvVaw2j2lZecx-i-y61EL1My7i0>\n\nMeeting ID: 622 394 1191\nPasscode:
  145258\nOne tap mobile\n+13462487799\,\,6223941191# US (Houston)\n+147038
 12552\,\,6223941191# US (Atlanta)\n\nDial by your location\n        +1 346
  248 7799 US (Houston)\n        +1 470 381 2552 US (Atlanta)\n        +1 6
 46 558 8656 US (New York)\n        +1 720 928 9299 US (Denver)\n        +1
  971 247 1195 US (Portland)\n        +1 312 626 6799 US (Chicago)\n       
  +1 647 374 4685 Canada\n        +44 203 481 5237 United Kingdom\nMeeting 
 ID: 622 394 1191\nFind your local number: https://us02web.zoom.us/u/kcWri3
 2Sh4<https://www.google.com/url?q=https%3A%2F%2Fus02web.zoom.us%2Fu%2FkcWr
 i32Sh4&sa=D&source=calendar&usd=2&usg=AOvVaw0TNEW5Ofg5l1UHtzY3TcUi>\n\nGoi
 ng (geert.haegens@amplifino.com<mailto:geert.haegens@amplifino.com>)?   Ye
 s<https://calendar.google.com/calendar/event?action=RESPOND&eid=dGVodGc4dG
 ZyOWtwcGtlbWQ2bGdycTdhc28gZ2VlcnQuaGFlZ2Vuc0BhbXBsaWZpbm8uY29t&rst=1&tok=M
 jkjeXp1bmd1bGFAbGlua2Vkc3RyYXRlZ2llcy5jb21lZGU2MzYxNGY2NDNhZmZkN2MzYjIxZmY
 yNWVmMmEwYTViODAxNmRl&ctz=Africa%2FJohannesburg&hl=en&es=0> - Maybe<https:
 //calendar.google.com/calendar/event?action=RESPOND&eid=dGVodGc4dGZyOWtwcG
 tlbWQ2bGdycTdhc28gZ2VlcnQuaGFlZ2Vuc0BhbXBsaWZpbm8uY29t&rst=3&tok=MjkjeXp1b
 md1bGFAbGlua2Vkc3RyYXRlZ2llcy5jb21lZGU2MzYxNGY2NDNhZmZkN2MzYjIxZmYyNWVmMmE
 wYTViODAxNmRl&ctz=Africa%2FJohannesburg&hl=en&es=0> - No<https://calendar.
 google.com/calendar/event?action=RESPOND&eid=dGVodGc4dGZyOWtwcGtlbWQ2bGdyc
 Tdhc28gZ2VlcnQuaGFlZ2Vuc0BhbXBsaWZpbm8uY29t&rst=2&tok=MjkjeXp1bmd1bGFAbGlu
 a2Vkc3RyYXRlZ2llcy5jb21lZGU2MzYxNGY2NDNhZmZkN2MzYjIxZmYyNWVmMmEwYTViODAxNm
 Rl&ctz=Africa%2FJohannesburg&hl=en&es=0>    more options »<https://calend
 ar.google.com/calendar/event?action=VIEW&eid=dGVodGc4dGZyOWtwcGtlbWQ2bGdyc
 Tdhc28gZ2VlcnQuaGFlZ2Vuc0BhbXBsaWZpbm8uY29t&tok=MjkjeXp1bmd1bGFAbGlua2Vkc3
 RyYXRlZ2llcy5jb21lZGU2MzYxNGY2NDNhZmZkN2MzYjIxZmYyNWVmMmEwYTViODAxNmRl&ctz
 =Africa%2FJohannesburg&hl=en&es=0>\n\nInvitation from Google Calendar<http
 s://calendar.google.com/calendar/>\n\nYou are receiving this courtesy emai
 l at the account geert.haegens@amplifino.com<mailto:geert.haegens@amplifin
 o.com> because you are an attendee of this event.\n\nTo stop receiving fut
 ure updates for this event\, decline this event. Alternatively you can sig
 n up for a Google account at https://calendar.google.com/calendar/ and con
 trol your notification settings for your entire calendar.\n\nForwarding th
 is invitation could allow any recipient to send a response to the organize
 r and be added to the guest list\, or invite others regardless of their ow
 n invitation status\, or to modify your RSVP. Learn More<https://support.g
 oogle.com/calendar/answer/37135#forwarding>.\n\n
UID:tehtg8tfr9kppkemd6lgrq7aso@google.com
SUMMARY;LANGUAGE=en-US:6 april > 08:49 > FW: Yamkela Zungula's Calendar tes
 t
DTSTART;TZID=Romance Standard Time:20220405T141800
DTEND;TZID=Romance Standard Time:20220405T151800
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220405T121810Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-US:https://us02web.zoom.us/j/6223941191?pwd=UzlJaHBVQm
 E2YzJkVUVWeEY2NTByUT09
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:1344894626
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-LOCATIONS:[{"DisplayName":"https://us02web.zoom.us/j/6223941191
 ?pwd=UzlJaHBVQmE2YzJkVUVWeEY2NTByUT09"\,"LocationAnnotation":""\,"Location
 Uri":""\,"LocationStreet":""\,"LocationCity":""\,"LocationState":""\,"Loca
 tionCountry":""\,"LocationPostalCode":""\,"LocationFullAddress":""}]
END:VEVENT
END:VCALENDAR
`

The above clearly has the properties UID, SUMMARY, DTSTART and DTEND but the library is not extracting it. It returns an empty optional for all. It detects the properties METHOD:REQUEST, PRODID and VERSION

**Expected behavior**
I was expected UID, SUMMARY, DTSTART and DTEND to be recognised and extracted from the inputstream

**Environment (please complete the following information):**
 - OS: MacOS & Ubuntu
 - Java Version 15

**Additional context**

**Comment by benfortuna** [comment]
Properties are defined at both the top-level (i.e. `VCALENDAR` and in embedded components (i.e. `VEVENT`). The properties you are trying to extract are defined in the `VEVENT`, but you are querying the `VCALENDAR`.

You can change your code to something like this:

```
VEvent event = calendar.getComponent(Component.VEVENT);
Summary summary = event.getProperty(Property.SUMMARY);
...
```

**Comment by rudivk** [comment]
Marvelous, works like a charm. Thank you very much!
