### ISSUE TITLE
Critical bug in Apache Collections4 used by ical4j

### ISSUE THREAD

**Issue by marcelbaumann** [ical4j/ical4j#566]
I am using version org.mnode.ical4j:ical4j:3.2.1 which has a dependency to apache commons collections4 version 4.1.

This version of commons collections4 has a bug/security issue see [][(org.mnode.ical4j:ical4j:3.2.1](https://issues.apache.org/jira/browse/COLLECTIONS-701)). Apache project defines the problem as a **critical bug.**

Could you please upgrade the dependency to version 4.3 or higher to close the problem?

Sincerely

**Comment by benfortuna** [comment]
Thanks for the feedback, I've just release v3.2.2 with updated dependencies.

Note that you should also be able to override the transitive dependencies by specifying an updated version of the ical4j dependency in your build configuration (i.e. pom.xml or build.gradle). This will remediate immediate concerns with vulnerabilities until it is updated with a new release.
