### ISSUE TITLE
Referencing subclass ImmutableClazz from superclass Clazz initializer might lead to class loading deadlock 

### ISSUE THREAD

**Issue by douglm** [ical4j/ical4j#571]
**Describe the bug**
My ide (intellij) flagged the creation of the immutable objects with the above message.

**To Reproduce**
1. Edit Clazz in intellij

**Expected behavior**
No warning I guess

**Environment (please complete the following information):**
 - Mac
 - Java Version 11

Looking at other places with similar issues it appears the fix is to move the class out of Clazz

I noticed this replicating Clazz as a new property RelativeTo. 

As a side note: For years I have had intermittent failures on a reboot of the system in which VtimeZone objects are not recognized as such. I've never tracked down the cause but it can happen if there are a lot of requests as the system initializes. Wonder if this is related.

**Comment by douglm** [comment]
Note: Following the solution here:

https://github.com/apache/rocketmq/commit/4a59207ef780af14eb7c6f9104b9a95a28f12360

the immutable objects need to be created in the immutable class.

I created a model.property.immutable package and put the new immutable class in there

This

https://github.com/Bedework/ical4j/blob/master/src/main/java/net/fortuna/ical4j/model/property/RelativeTo.java

is my copy of Clazz updated - referring to an immutable class which defines the constants.

**Comment by douglm** [comment]
So a problem with that approach - though there may be no other - is that it moves the constant which will break any code referring to those constants.

So far I don't se any solution other than this.

I did find this issue for openjdk 1.4 (2005) in which this is characterised as a  misuse of java adn will not be fixed

https://bugs.openjdk.java.net/browse/JDK-6301579?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by benfortuna** [comment]
Thanks @douglm, I was also just looking at this thinking if there was a better way..

I think your solution is good, and although it may break code that directly references the constant it is hard to gauge how big an impact this would be to ical4j users.

I'm just working on a refresh of the ical4j-vcard library, so will make this change, and also in ical4j v4, as most code will need to be modified anyway to adopt these.

If there is enough support for this (and the resulting code breakage) then happy to also apply in ical4j v3.
