### ISSUE TITLE
Recur.getDates: duplicate instances when using BYWEEKNO

### ISSUE THREAD

**Issue by K-e-l-v-i-n-12** [ical4j/ical4j#576]
I have an event that happens every odd week. So far I have used an RRule with Interval for this recurring event. However, this is not correct during the turn of the year. I would therefore like to create a RRule that only applies to odd weeks. The RRule looks like this:
**FREQ=WEEKLY;BYDAY=WE;BYWEEKNO=1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53**

I have therefore calculated the events for the period from 05/01/2022 to 05/01/2999 as a test. With Interval I get 25,489 occurrences. My expectation would have been that I would get an approximately identical number of occurrences for the byweekno method as well.

Unfortunately, the byweekno method reproduces this 52 times. When I distinct the list, I get 25489 occurrences, which seem correct.

Unfortunately, this is not a feasible way, since the throughput time requires 5792ms instead of 312ms. Is there a bug in ical4j or is the rule simply wrong?

`
        private LocalDate startRange = LocalDate.of(2022, 5, 1);
        private LocalDate endRange = LocalDate.of(2999, 5, 1);
 
        @Test
        public void byWeekNo() {
                String rrule = "FREQ=WEEKLY;BYDAY=WE;BYWEEKNO=1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53";
                LocalTime start = LocalTime.now();
               
                long count = new Recur<LocalDate>(rrule).getDates(startRange, endRange).stream().count();
               
                LocalTime end = LocalTime.now();
                System.out.println(String.format("[byWeekNo] %d elements in %s ms", count, ChronoUnit.MILLIS.between(start, end)));
               
               
        }
       
        @Test
        public void interval() {
                String rrule = "FREQ=WEEKLY;BYDAY=WE;INTERVAL=2";
                LocalTime start = LocalTime.now();
               
                long count = new Recur<LocalDate>(rrule).getDates(startRange, endRange).stream().count();
               
                LocalTime end = LocalTime.now();
                System.out.println(String.format("[interval] %d elements in %s ms", count, ChronoUnit.MILLIS.between(start, end)));
               
        }
`

Result: 
[interval] 25489 elements in 357 ms
[byWeekNo] 1333840 elements in 5798 ms

with stream().distinct().count
[interval] 25489 elements in 312 ms
[byWeekNo] 25575 elements in 5792 ms:

**Comment by benfortuna** [comment]
Thanks for the feedback, definitely seems to be a bug. 

Just to confirm, it looks like you are using the 4.0.0-alpha releases, can you confirm which version specifically? Thanks.

**Comment by K-e-l-v-i-n-12** [comment]
Yes, correct. I use the latest alpha.

**Comment by benfortuna** [comment]
Thanks @elirenato for the PR. I actually should have looked more closely at the original rule as I think actually the syntax here is not valid.

This is an excerpt from the RFC5545 specification:

```
      The table below summarizes the dependency of BYxxx rule part
      expand or limit behavior on the FREQ rule part value.

      The term "N/A" means that the corresponding BYxxx rule part MUST
      NOT be used with the corresponding FREQ value.

...

   +----------+--------+--------+-------+-------+------+-------+------+
   |          |SECONDLY|MINUTELY|HOURLY |DAILY  |WEEKLY|MONTHLY|YEARLY|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMONTH   |Limit   |Limit   |Limit  |Limit  |Limit |Limit  |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYWEEKNO  |N/A     |N/A     |N/A    |N/A    |N/A   |N/A    |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYYEARDAY |Limit   |Limit   |Limit  |N/A    |N/A   |N/A    |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMONTHDAY|Limit   |Limit   |Limit  |Limit  |N/A   |Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYDAY     |Limit   |Limit   |Limit  |Limit  |Expand|Note 1 |Note 2|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYHOUR    |Limit   |Limit   |Limit  |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYMINUTE  |Limit   |Limit   |Expand |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYSECOND  |Limit   |Expand  |Expand |Expand |Expand|Expand |Expand|
   +----------+--------+--------+-------+-------+------+-------+------+
   |BYSETPOS  |Limit   |Limit   |Limit  |Limit  |Limit |Limit  |Limit |
   +----------+--------+--------+-------+-------+------+-------+------+
```

So actually the rule `FREQ=WEEKLY;BYDAY=WE;BYWEEKNO=1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53` is not valid.

However, if you change the rule to `FREQ=YEARLY` as follows I believe it works as expected:

`FREQ=YEARLY;BYDAY=WE;BYWEEKNO=1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53`

I will incorporate the tests from your PR as this helps to validate the correct behaviour, but I think in this case it was the recurrence rule that was the problem.

**Comment by elirenato** [comment]
Hi @benfortuna,

Thank you, I should have seen that that.

As this rule is not valid and it can cause a bug like this, what do you think we add some check inside the Recur::validateFrequency to make sure it won't happen again in the future?

**Comment by benfortuna** [comment]
I've just added some more validation for recurrence rules, that will be applied with relevant properties are validated (i.e. RRULE/EXRULE).

https://github.com/ical4j/ical4j/blob/develop/src/main/java/net/fortuna/ical4j/validate/RecurValidator.java

Let me know if you have any feedback on this.

**Comment by elirenato** [comment]
Hi @benfortuna,

For me is good.

Thanks
