### ISSUE TITLE
UTC timezone alias are being mapped to Europe/London

### ISSUE THREAD

**Issue by hubpan** [ical4j/ical4j#58]
Hi,

  Europe/London observes daylight saving, so it's not a good candidate for replacing UTC and its variants. I am able to fix this issue for my distribution by generating ics files from `etcetera` (containing timezones like Etc/GMT, Etc/Zulu).

  I am not sure if that's the appropriate solution, but if you don't mind adding those extra ics - I could create a patch for you that address the UTC issue.

**Comment by benfortuna** [comment]
Hi,

Yes I think it is probably the best solution to generate ics files for GMT, etc. We actually use a fork of vzic, called tzurl (https://github.com/benfortuna/tzurl) to generate the ics, so it would be good to maybe patch that project, if possible, to generate ics from the etcetera file.

regards,
ben

**Comment by hubpan** [comment]
ah I didn't notice you are using a fork of vzic. I have submitted a PR there : 
https://github.com/benfortuna/tzurl/pull/6/commits

btw there is a new version of timezone database available at https://www.iana.org/time-zones 
you might want to generate a new set of ics files using that. Once the new Etc/* are added, you could simply remove existing GMT mappings in `/src/main/resources/net/fortuna/ical4j/model/tz.alias`

Thank you for ical4j
Regards,
Hubert

**Comment by benfortuna** [comment]
This has been merged to the master branch and will be included in the next 2.x release.
