### ISSUE TITLE
Accept/tolerate invalid email addresses in lenient mode 

### ISSUE THREAD

**Issue by sunkup** [ical4j/ical4j#584]
**Is your feature request related to a problem? Please describe.**
The Thunderbird desktop client (with CalDAV provider installed) may produce events where the organizer email property contains invalid email addresses like the following:
```
ORGANIZER;EMAIL="example@https://exaple.com/remote.php/caldav/":mailto:
 example@https://example.com/remote.php/caldav/
```
Though syntactically correct, it's semantically questionable... Either way ical4j throws an `IllegalArgumentException` even when in lenient mode, so we have to dismiss the whole event.
```
Caused by: java.lang.IllegalArgumentException: Invalid address: exaple@https://example.com/remote.php/caldav/
	at net.fortuna.ical4j.model.parameter.Email.<init>(Email.java:66)
	at net.fortuna.ical4j.model.parameter.Email$Factory.createParameter(Email.java:84)
	at net.fortuna.ical4j.model.parameter.Email$Factory.createParameter(Email.java:75)
	at net.fortuna.ical4j.model.ParameterBuilder.build(ParameterBuilder.java:66)
```

**Describe the solution you'd like**
We would like ical4j not to throw an exception on invalid emails, when in lenient mode, so we can still handle the event.

**Additional context**
[Discussion at the DAVx5 repo](https://github.com/bitfireAT/davx5-ose/discussions/82)

**Comment by benfortuna** [comment]
Ok, I've just added a change to skip email validation if RELAXED_VALIDATION compatibility hint is enabled.

So behaviour of Email parameter is now:

1. If RELAXED_PARSING is enabled, removed any trailing dot from end of address string (e.g. `joeb@example.com.`)
2. If RELAXED_VALIDATION is enabled, don't test for valid email string (i.e. any string is allowed)
