### ISSUE TITLE
Bad escaping of various lineBreak char

### ISSUE THREAD

**Issue by bubbatls** [ical4j/ical4j#590]
When I do
`vEvent.getProperties().add(new Description("test N\n test RN\r\n test NR\n\r test R\r end"));`

the generated ics looks like
`DESCRIPTION:test N\n test RN
\n test NR\n
 test R
 end`

![image](https://user-images.githubusercontent.com/2863829/185630429-c947edb4-daf7-40a2-b977-e90d35b64329.png)

And it is not a valid file

I use the 3.2.5

**Comment by benfortuna** [comment]
Certain characters are escaped when output to prevent malformed iCalendar data. This includes backslash, newlines, quotes, etc. In your example the carriage return character (`\r`) is not escaped, which is the cause of the invalid file.

I will update the encoding to include `\r`.

**Comment by bubbatls** [comment]
It happens with data coming from my database.
After research I find that the single `\r` was used on Apple II and Mac OS until version 9.

As old data might come from old database, in my mind the good behaviour is to handle
`\r\n` `\r` and `\n` with the same output. So keeping a line break for single `\r`

`\n\r` is obviously weird data, so for this one ignoring `\r` will do the same as setting a line break.

Thanks a lot! :)
