### ISSUE TITLE
Parsing several meetings with different timezones causes ParserException: Unable to register zone as one already registered with that ID ...

### ISSUE THREAD

**Issue by leccyril** [ical4j/ical4j#592]
**Issue :** 

If you create 2 events with 2 differents timezones and the exception occurs each time : 

_net.fortuna.ical4j.data.ParserException: Error at line 32:Unable to register zone as one already registered with that ID: ical4j~e44813b3-68fa-4a85-ab88-19e8ceda4349, currently loading from provider: net.fortuna.ical4j.model.ZoneRulesProviderImpl@43ed0ff3_

**Behaviour expected :** 

Exception not throwed and parsing working

**How to reproduce :** 

Take the following code in java test with version 4 beta 1 of ICal4j (it will be reproduced each time), first event will be parsed but it crashes on the second one

```
var events = List.of( """
				BEGIN:VCALENDAR
				CALSCALE:GREGORIAN
				PRODID:-//Ximian//NONSGML Evolution Calendar//EN
				VERSION:2.0
				BEGIN:VTIMEZONE
				TZID:Asia/Kuwait
				X-LIC-LOCATION:Asia/Kuwait
				BEGIN:STANDARD
				TZNAME:+03
				TZOFFSETFROM:+030652
				TZOFFSETTO:+0300
				DTSTART:19470314T000000
				END:STANDARD
				END:VTIMEZONE
				BEGIN:VEVENT
				UID:e65f626ec762bbe33a44900cc267b8c03590ffb9
				DTSTAMP:20220822T113350Z
				DTSTART;TZID=Asia/Kuwait:20220823T103000
				DTEND;TZID=Asia/Kuwait:20220823T113000
				SEQUENCE:4
				ORGANIZER:mailto:sylvain@equitativa.com
				SUMMARY:test asia
				LOCATION:asia
				TRANSP:OPAQUE
				URL:test asia dubai
				DESCRIPTION:test asia dubai
				CLASS:PUBLIC
				CREATED:20220823T053128Z
				LAST-MODIFIED:20220823T054416Z
				ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:test@mantiq.com
				END:VEVENT
				END:VCALENDAR
				""", """
				BEGIN:VCALENDAR
				CALSCALE:GREGORIAN
				PRODID:-//Ximian//NONSGML Evolution Calendar//EN
				VERSION:2.0
				BEGIN:VTIMEZONE
				TZID:Asia/Dubai
				X-LIC-LOCATION:Asia/Dubai
				BEGIN:STANDARD
				TZNAME:+04
				TZOFFSETFROM:+034112
				TZOFFSETTO:+0400
				DTSTART:19200101T000000
				END:STANDARD
				END:VTIMEZONE
				BEGIN:VEVENT
				UID:63db11aa7f51388eb149302c2ae7c499da334d4f
				DTSTAMP:20220822T113350Z
				DTSTART;TZID=Asia/Dubai:20220830T110000
				DTEND;TZID=Asia/Dubai:20220830T120000
				SEQUENCE:2
				ORGANIZER:mailto:sylvain@equitativa.com
				ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:test@mantiq.com
				SUMMARY:fefef
				LOCATION:fdefefe
				TRANSP:OPAQUE
				URL:fefef
				DESCRIPTION:efefef
				CLASS:PUBLIC
				CREATED:20220823T054633Z
				LAST-MODIFIED:20220823T054633Z
				END:VEVENT
				END:VCALENDAR
				""" );
		final var calendarBuilder = new CalendarBuilder();
		for( String event : events ){
			calendarBuilder.build( new StringReader( event ) );
		}
```

**Comment by leccyril** [comment]
Any news because it is a big issue and really simple to reproduce
thanks !

**Comment by benfortuna** [comment]
Yeah, so the issue here is that you cannot reuse the same calendar builder instance for multiple files/input data.

The reason is that there is an assumption of a separate timezone registry for each calendar, to avoid calendar-local timezone definitions affecting other calendars.

It probably isn't documented well as yet, and may be different behaviour from ical4j v3 due to changes in the timezone model.

**Comment by leccyril** [comment]
Yes thanks, but it means also code less efficient etc.... so the only things to do is to mode the builder and not reuse it ? it is a normal behaviour ? nothing will be done on development side ? if yes so we can close it.

thanks !

**Comment by benfortuna** [comment]
Yeah, ultimately we require a separate Timezone registry for each calendar object to ensure isolation of local timezone definitions. We may change some things in future to address any specific performance concerns but currently we'll focus correctness first.
