### ISSUE TITLE
TimeZoneUpdater with flags net.fortuna.ical4j.timezone.update.enabled and net.fortuna.ical4j.timezone.update.connection.secure enabled does not work

### ISSUE THREAD

**Issue by devanand** [ical4j/ical4j#602]
When the aforementioned flags are enabled in iCal4j.properties, the updated ics file is fetched from the following url
https://tzurl.org/zoneinfo/{continent}/{country}. However the secure tzurl.org does not work and the log is inundated with the following message "Error updating timezone definition". 
Is there a fix for this on the horizon? As a temporary recourse, I have set net.fortuna.ical4j.timezone.update.enabled to false

**Comment by benfortuna** [comment]
There is a fix for this included in the latest releases:

http://ical4j.github.io/2022/11/06/timezone-updates-and-tzurl-org.html

Note that secure connection is now the default, however it can be overridden via new configuration options.
