### ISSUE TITLE
DateTimeException evaluating FREQ=YEARLY;INTERVAL=2;UNTIL=20230101 as LocalDateTime

### ISSUE THREAD

**Issue by fmossott** [ical4j/ical4j#608]
**Describe the bug**
Using Recur<LocalDateTime> and generating dates for "FREQ=YEARLY;INTERVAL=2;UNTIL=20230101" throws the following exception

```
java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: 2020-01-01T00:00 of type java.time.LocalDateTime

	at java.base/java.time.Instant.from(Instant.java:378)
	at net.fortuna.ical4j.model.TemporalAdapter.isAfter(TemporalAdapter.java:307)
	at net.fortuna.ical4j.model.Recur.getDates(Recur.java:810)
	at net.fortuna.ical4j.model.Recur.getDates(Recur.java:737)
        ....
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: InstantSeconds
	at java.base/java.time.LocalDate.get0(LocalDate.java:708)
	at java.base/java.time.LocalDate.getLong(LocalDate.java:687)
	at java.base/java.time.LocalDateTime.getLong(LocalDateTime.java:720)
	at java.base/java.time.Instant.from(Instant.java:373)
	... 90 more
```

**To Reproduce**
Run the following code
```java
        Recur<LocalDateTime> recur = new Recur<>("FREQ=YEARLY;INTERVAL=2;UNTIL=20230101");
        List<LocalDateTime> dates = recur.getDates(LocalDate.of(2020, 1, 1).atStartOfDay(),
                LocalDate.of(2020, 1, 1).atStartOfDay(),
                LocalDate.of(2025, 1, 1).atStartOfDay());
```
**Expected behavior**
Should work, like for LocalDate and ZoneDateTime, generating the following dates
[2020-01-01T00:00, 2022-01-01T00:00]

**Environment (please complete the following information):**
 - Java 11
 - iCal4j Version: 4.0.0-beta2 and 4.0.0-beta3

**Additional context**
The problem is in net.fortuna.ical4j.model.TemporalAdapter#isAfter that should compare LocalDateTime with LocalDate without trying to convert them to instants

**Comment by fmossott** [comment]
Thanks you so much for the quick fix.
I know, java.time is awesome, but some scenarios could be tricky (with java.util.Date you was just not aware of that, though).

Looking your change I see that is some cases when you need to add a ZoneId you use the system default, this could introduce some unwanted behavior if the library is used on the server side where usually you don't want to rely on the machine time zone.
It would be nice to have an option to specify the zoneId in Recur (coming from VTIMEZONE in case it's coming from vCard)

**Comment by benfortuna** [comment]
Sure, I was thinking maybe there is room for some configuration options here.

Feel free to add more suggestions and use-cases to help refine the implementation.
