### ISSUE TITLE
proposal - support of java.time (Java 8)

### ISSUE THREAD

**Issue by herau** [ical4j/ical4j#62]
Provide a support of java.time (LocalDateTime, Datetime etc) for usage of `Date`, `DateTime` classes

**Comment by benfortuna** [comment]
We do have a branch for this already - [jsr-310](https://github.com/ical4j/ical4j/tree/jsr-310), however to be honest we haven't made much progress as yet. This is definitely a priority however it will not be a trivial task.

**Comment by solomax** [comment]
This https://github.com/ThreeTen/threetenbp library can be used to unify the code, works for us

**Comment by herau** [comment]
What is the more efficient way to use the existing ical4j API with LocalDate, LocalDatetime ? 
I have tried with `ZoneId` and `Instant` classes but i'm not sure that is the best solution:

```Java
LocalDateTime startDate = LocalDateTime.now();
ZoneId zoneId = ZoneId.of("Europe/Paris");

DateTime eventStartDate = new DateTime(startDate.atZone(zoneId).toInstant().toEpochMilli());
VEvent vEvent = new VEvent(eventStartDate, ...);
```

**Comment by herau** [comment]
when i talk about support of jsr-310, i mean that the external api support method with java.time types. it could be a first step of the support of the jsr-310 (have 2 methods each with previous and new datetime Java api). 
When you talk about jsr-310 support you mean rewrite all the code of the library ?

**Comment by benfortuna** [comment]
Yes, I was thinking of replacing the duration, date-time, period, etc
classes. I guess in the interim we could provide some utility methods for
conversion, but it's probably a similar amount of work as what I was
planning.

**Comment by herau** [comment]
@benfortuna, i forked and checkout the jsr-310 branch to try to continue your job but i have some questions about it: 

 - does it update compare to the master branch ?
 - some unit tests are not ok (partially or entirely): 
  - net.fortuna.ical4j.filter.PeriodRuleTest
  - net.fortuna.ical4j.data.CalendarBuilderTest
  - `net.fortuna.ical4j.filter.FilterTest#testFilteredIsNotEmpty`
  - net.fortuna.ical4j.model.DurTest
  - net.fortuna.ical4j.model.DurSpec
  - net.fortuna.ical4j.filter.PeriodRuleTest
  - net.fortuna.ical4j.data.CalendarBuilderTest

**Comment by benfortuna** [comment]
* Yes the jsr-310 branch is based off master
* Failing tests are a known issue I think - need to verify if the test will change or the code
* Initially I wanted to support Java 6 onwards, but if there is a reason not to I would consider Java7 minimum
