### ISSUE TITLE
ComponentFilter hard cast set to list

### ISSUE THREAD

**Issue by Skillkiller** [ical4j/ical4j#623]
**Describe the bug**
The ``FilterExpression.in()`` method accepts a string and a collection as passing parameters. Because a collection can be passed, sets can also be passed.
The problem is that in the program flow the collection is later cast to a list.

Error
```java
java.lang.ClassCastException: class java.util.ImmutableCollections$Set12 cannot be cast to class java.util.List (java.util.ImmutableCollections$Set12 and java.util.List are in module java.base of loader 'bootstrap')
	at net.fortuna.ical4j.filter.AbstractFilter.properties(AbstractFilter.java:125) ~[ical4j-3.2.9.jar:3.2.9]
	at net.fortuna.ical4j.filter.ComponentFilter.predicate(ComponentFilter.java:59) ~[ical4j-3.2.9.jar:3.2.9]
	at net.fortuna.ical4j.filter.PredicateFactory.predicate(PredicateFactory.java:15) ~[ical4j-3.2.9.jar:3.2.9]
	at de.skillkiller.firmenkalender.WebhookController.webhook(WebhookController.java:54) ~[classes/:na]
```

**To Reproduce**
Code to reproduce the behavior:
```java
Predicate filter = new ComponentFilter().predicate(FilterExpression.in(Property.SUMMARY, Set.of("Test")));
calendar.getComponents(Component.VEVENT).stream().filter(filter).forEach(System.out::println);
```

**Expected behavior**
No cast exception or ``FilterExpression.in`` requires ``List<?>`` instead of ``Collection<?>``.

**Environment (please complete the following information):**
 - OS: Linux
 - Spring Boot + Spring Web: 3.0.2 
 - Java Version 17
 - iCal4j Version 3.2.9

**Additional context**

**Comment by benfortuna** [comment]
Thanks for the feedback. I've just added a fix and will be available in the next release on 3.x/4.x branches
