### ISSUE TITLE
everit-json-schema superseded by json-sKema

### ISSUE THREAD

**Issue by SingingBush** [ical4j/ical4j#631]
ical4j has an optional dependency on `com.github.erosb:everit-json-schema` which has a deprecation notice on it's github readme:

> This library is currently in maintenance mode and superseded by [erosb/json-sKema](https://github.com/erosb/json-sKema).

it's probably worth updating to the newer `com.github.erosb:json-sKema` if schema validation is still needed. Personally though I'd prefer ical4j to have very minimal dependencies and not require it at all. Is the `net.fortuna.ical4j.validate.schema.JsonSchemaValidator` class really needed?

**Comment by benfortuna** [comment]
I think we can consider removing this dependency.. the intention was to provide some validation of any included `STRUCTURED-DATA` properties, which is a relatively new specification that probably isn't yet supported by most iCalendar implementations.

We'll wait and see how the use of this property evolves and address at a later date.

**Comment by benfortuna** [comment]
The PR to upgrade dependency has been merged, but we may still remove entirely in future depending on usefulness
