### ISSUE TITLE
use Gradle feature variants instead of optional dependencies

### ISSUE THREAD

**Issue by SingingBush** [ical4j/ical4j#632]
ical4j uses a few optional dependencies. from what I can tell _optional_ is more of a Maven thing than it is Gradle. Gradle has a few pages about using feature variants instead.

https://docs.gradle.org/current/userguide/feature_variants.html

https://blog.gradle.org/optional-dependencies

worth pointing out though that if ical4j handles all date/time related code with _java.time_ (#62 which would also probably resolve multiple [time related issues](https://github.com/ical4j/ical4j/issues?q=is%3Aissue+is%3Aopen+time+)) and used Java only instead of Java+Groovy, the majority of those optional dependencies can go altogether.  As mentioned in #631, I personally prefer libraries to be as slim as possible.

**Comment by benfortuna** [comment]
Thanks for the feedback. ical4j v4 will use the new date/time api, so potentially will review the optional dependencies for that. For now I have added feature variants to the develop branch.
