### ISSUE TITLE
replace gradle-command-action with gradle-build-action

### ISSUE THREAD

**Issue by SingingBush** [ical4j/ical4j#635]
GitHub pipeline warns that `eskatos/gradle-command-action@v1` uses node 12:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: eskatos/gradle-command-action@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

I looked for an updated version but it seems that `eskatos/gradle-command-action` should just be replaced by `gradle/gradle-build-action`

**Comment by benfortuna** [comment]
Thanks I'll start making the change in the github workflows
