### ISSUE TITLE
Can't create properly formatted CONFERENCE property

### ISSUE THREAD

**Issue by mcastro121** [ical4j/ical4j#650]
**Describe the bug**
I am using the latest beta: 4.0.0-beta9

Referencing:
https://www.rfc-editor.org/rfc/rfc7986.html#section-5.11

I am trying to use the CONFERENCE Property to add a video conferencing link to the calendar file.

This property should have this form:

CONFERENCE;VALUE=URI;FEATURE=AUDIO,VIDEO;
    LABEL=Attendee dial-in:https://chat.example.com/audio?id=123456

But it doesn't seem possible with the Conference Property object.

This is the closest I was able to get using this constructor Conference(net.fortuna.ical4j.model.ParameterList params, java.lang.String value), and passing a null in for the value

CONFERENCE;VALUE=URI;FEATURE="AUDIO,VIDEO";LABEL="Attendee dial-in:https://examplelink.com":

It seems the issue is that the Label value has quotes around it, and there shouldn't be. Removing the quotes seems to fix the issue. The quotes around the FEATURE value don't seem to do harm.

**Comment by mcastro121** [comment]
After some more debugging, quotes are being added when there is a colon present in the string.

**Comment by mcastro121** [comment]
It doesn't seem like the Conference property is support across all browers. It seems adding a link to the Description might work better.

**Comment by benfortuna** [comment]
Hi, I've just added a unit test that demonstrates how to construct the CONFERENCE property using the example above:

https://github.com/ical4j/ical4j/blob/develop/src/test/groovy/net/fortuna/ical4j/model/property/ConferenceTest.groovy

The confirmed output of the last test example as follows:

`CONFERENCE;VALUE=URI;FEATURE="AUDIO,VIDEO";LABEL=Attendee dial-in:https://chat.example.com/audio?id=123456`

**Comment by mcastro121** [comment]
Thank you, It seems I wasn't doing it exactly the right way.
