### ISSUE TITLE
nebula plugins should probably be removed - latest versions are no-op

### ISSUE THREAD

**Issue by SingingBush** [ical4j/ical4j#658]
in my fork I was looking at updating the Gradle version and needed to bump the nebula plugins as v7 doesn't support Gradle 8.

In _build.gradle_ they are currently:

```
    id "nebula.provided-base" version "7.0.0"
    id "nebula.optional-base" version "7.0.0"
```

In recent versions they have updated the id (latest is v10):

```
    id "com.netflix.nebula.provided-base" version "10.0.0"
    id "com.netflix.nebula.optional-base" version "10.0.0"
```

I did see on the github for there was mention of them being a no-op and in the build output there was the following:

```
nebula.provided-base plugin does nothing. Use the 'compileOnly' configuration
nebula.optional-base plugin does nothing. Please remove the plugin
```

**Comment by benfortuna** [comment]
Thanks for the advice and PR. I've added feature variants to replace the optional plugin, now available in the develop branch
