### ISSUE TITLE
Update android minify receipe in https://www.ical4j.org/android/ for R8-Minify

### ISSUE THREAD

**Issue by k3b** [ical4j/ical4j#665]
After upgrading my android ical4j app  to android-api34 the minify with R8 does not work anymore as described in the the receipe https://www.ical4j.org/android/https://www.ical4j.org/android/

These changes made it work again (assuming android-compilesdk=34 + java8 (to keep it compatible with android-4.0)

Note i have not tested with android with java-11 or java-17 and ical4j version 3.xxxx

----
Changes in build.gradle Working example: https://github.com/k3b/calef/blob/master/app/build.gradle

	dependencies {
		//noinspection GradleDependency
		// most recent version 2.x: compiles with api-14 + java8
		implementation 'org.mnode.ical4j:ical4j:2.2.7'

		// required by ical4j R8-minify: must be present in order to be removed :-(
		implementation 'javax.cache:cache-api:1.1.1'

---
Changes in proguard-rules.pro Working example: https://github.com/k3b/calef/blob/master/app/proguard-rules.pro

	## ical4j also contains groovy code which is not used in android
	-dontwarn groovy.**
	-dontwarn org.codehaus.groovy.**
	-dontwarn org.apache.commons.logging.**

	## ical4j specific: replace JCacheTimeZoneCache with MapTimeZoneCache which is much smaller and does not requiere internet access to reload timezones
	-assumenosideeffects class net.fortuna.ical4j.util.JCacheTimeZoneCache
	-assumenosideeffects class javax.cache.Cache
	-assumenosideeffects class javax.cache.CacheManager
	-assumenosideeffects class javax.cache.Caching
	-assumenosideeffects class javax.cache.configuration.Configuration
	-assumenosideeffects class javax.cache.configuration.MutableConfiguration
	-assumenosideeffects class javax.cache.spi.CachingProvider
	-keep class net.fortuna.ical4j.util.MapTimeZoneCache
	
---
add initialisation code (from working example https://github.com/k3b/calef/blob/master/app/src/main/java/de/k3b/android/calef/SettingsImpl.java#L56C1-L59C1 )

        // replace JCacheTimeZoneCache with MapTimeZoneCache which is much 
        // smaller and does not requiere internet access to reload timezones
        new MapTimeZoneCache(); // tell proguard that the class is used
        System.setProperty("net.fortuna.ical4j.timezone.cache.impl", "net.fortuna.ical4j.util.MapTimeZoneCache");

**Comment by benfortuna** [comment]
@k3b thanks so much for the update. I have added your working examples inline with attribution, hope that is ok. 

Unfortunately I don't have an environment to test Android in right now, but feel free to add more suggestions to improve our support for Android.
