### ISSUE TITLE
Times of events are off by one hour

### ISSUE THREAD

**Issue by haavar** [ical4j/ical4j#667]
**Describe the bug**
In version 4.0.0-rc1 the time of the events are off by 1 hour. I'm assuming that's because of daylight savings.

**To Reproduce**
I've attached java class to reproduce the issue. I was not able to get the formatting to work, and I think it was better to use an attachment.

I'm using output from apple calendar for an event recently created. The event time is 17:00 to 18:00 PST (-8). When reading the calendar the event times comes back 17:00-18:00 -7. Meaning the correct value time of day, but with the wrong timezone.

I tried simplifying the time zone definitions in the input, but I was not able to reproduce with that. It's probably related to the issue.

[Test.java](https://github.com/ical4j/ical4j/files/13668858/Test.txt)

**Expected behavior**
The output should be in the correct timezone. In the example above it should be 2023-12-14T17:00-08:00

**Environment (please complete the following information):**
 - OS: macOs 14.1.2
 - Java Version 20
 - iCal4j Version 4.0.0-rc1

**Comment by benfortuna** [comment]
Same issue also reported here: #662

After some extensive investigation I discovered `ZoneRulesBuilder` implementation was wrong. I have now reimplemented this and added some tests to confirm it now works.

Fix available in 4.0.0-rc2
