### ISSUE TITLE
Errors need to be flagged as such in log

### ISSUE THREAD

**Issue by douglm** [ical4j/ical4j#674]
**Describe the bug**
In the configurator (at least) we have code like this:

`try {
                return Optional.of((T) Class.forName(property.get()).newInstance());
            } catch (InstantiationException | IllegalAccessException | ClassNotFoundException e) {
                LOG.info(String.format("Invalid configuration value: %s", key), e);
                return Optional.empty();
            }`

I feel we should be calling LOG.error here. I missed messages indicating I had a missing dependency which prevented ical4j from location a timezones registry.

**To Reproduce**
1. I have ical4j loaded as a wildfly module - each module must specify it's dependencies. I missed the one for the timezone registry.
2. Any activity that calls ical4j
3. See error as an informational message rather than error.

**Expected behavior**
Output as erro messages so that they get written to an error log.

**Environment (please complete the following information):**
 - OS: Many
 - Java Version 11
 - iCal4j Version - present on development version in repo

**Comment by benfortuna** [comment]
Would a WARNING be sufficient to appear in the logs? Just thinking that technically it won't always make ical4j dysfunctional to have a bad configuration, so an ERROR might be a bit too severe.

But if you feel strongly about ERROR then I can do that.

**Comment by douglm** [comment]
Sorry - missed your response.

I think it warrants an ERROR. I probably would have missed a warning - there seem to be a number of these from mnay packages which are really mostly about possible performance issues.

I think this error could potentially damage data. Maybe the code shoudl take into account what th econfiguration option is. Bad timezones is potentially a very bad problem.

**Comment by benfortuna** [comment]
Fixed applied to log invalid configuration as ERRROR
