### ISSUE TITLE
TZ aliases not working

### ISSUE THREAD

**Issue by ArnyminerZ** [ical4j/ical4j#676]
**Describe the bug**
Since the last update of ical4j (3.2.15), time zone aliases have stopped working, so for example, `GMT` is not recognized as a valid time zone, but `Etc/GMT` is.

**To Reproduce**
I've set up this testbench which tries all the time zone names available in Java:
```kotlin
private val tzRegistry = TimeZoneRegistryFactory.getInstance().createRegistry()

@Test
fun testLoadSystemTimezones() {
    for (id in ZoneId.getAvailableZoneIds()) {
        val name = ZoneId.of(id).getDisplayName(TextStyle.FULL, Locale.US)
        val info = try {
            tzRegistry.getTimeZone(id)
        } catch(e: Exception) {
            Assert.fail("Invalid system timezone $name ($id)")
        }
        if (info == null)
            assertNotNull("ical4j can't load system timezone $name ($id)", info)
    }
}
```
and it fails with
```
ical4j can't load system timezone GMT (GMT)
```

with an even simpler test:
```
@Test
fun testGetTimezone() {
    assertNotNull(tzRegistry.getTimeZone("Vienna"))
}
```
the same happens, null is returned.

**Expected behavior**
Aliases should work as well as full names.

**Environment (please complete the following information):**
 - OS: Android
 - Java Version: `17`
 - iCal4j Version: `3.2.15`

**Additional context**
I've seen that for `3.2.15` the way aliases are loaded have changed, as well as the files where they are loaded from:

https://github.com/ical4j/ical4j/compare/ical4j-3.2.14..ical4j-3.2.15

I guess something broke up in the way.

They are in fact well defined here

https://github.com/ical4j/ical4j/blob/ical4j-3.2.15/src/main/resources/net/fortuna/ical4j/model/tz.alias

So I'm not sure what the problem might be.

**Comment by benfortuna** [comment]
Thanks for the bug report. In v3.2.15 we integrated aliased for Microsoft timezone IDs, however they weren't loading correctly and messed up the other aliases.

v3.2.16 provides a fix to load the MS timezones correctly.

**Comment by ArnyminerZ** [comment]
Awesome, thank you very much for the quick fix
