### ISSUE TITLE
`calculateRecurrenceSet` return value is not accurate

### ISSUE THREAD

**Issue by raboof** [ical4j/ical4j#683]
The signature of the `calculateRecurrenceSet` function is:

    <T extends Temporal> Set<Period<T>> calculateRecurrenceSet(final Period<T> period)

This suggests that when passing in a `Period<LocalDateTime>`, you'd get a Set<Period<LocalDateTime>> in response. However, AFAICS this is not guaranteed: depending on the events the return value could be a `Period<ZonedDateTime>` as well.

Wouldn't it be more accurate to have:

    <T extends Temporal> Set<Period<Temporal>> calculateRecurrenceSet(final Period<T> period)

?

**Comment by benfortuna** [comment]
Thanks for the feedback, apologies for late response.

This has been fixed in a recent version, although the fix is slightly different to your suggestion:

```java
public final <T extends Temporal> Set<Period<T>> calculateRecurrenceSet(Period<? extends Temporal> period)
```

This basically indicates there is no correlation between the period and the recurrence set, as the temporal type is derived from the type used in `DTSTART` property.

The difference is that the caller can use their knowledge of the `DTSTART` property to assume the correct type, e.g:

```java
Set<Period<LocalDate>> result = calculateRecurrenceSet(period);
```

Let me know if you think there are advantages for your suggestion over this one.

https://javadoc.io/doc/org.mnode.ical4j/ical4j/latest/ical4j.core/net/fortuna/ical4j/model/Component.html

**Comment by raboof** [comment]
> Let me know if you think there are advantages for your suggestion over this one.

Gladly!

> This basically indicates there is no correlation between the period and the recurrence set, as the temporal type is derived from the type used in `DTSTART` property.

That makes sense to me.

Generally, I think a library should use the type system to specify what it guarantees. The user of the library can make additional assumptions, and the mechanism to encode those is casts. From that perspective, I think

```java
public final Set<Period<Temporal>> calculateRecurrenceSet(Period<? extends Temporal> period)
```

would be slightly better. In

```java
Set<Period<LocalDate>> result = calculateRecurrenceSet(period);
LocalDate date = result.iterator().next().getStart()
```

, when passing in events with different types for the `DTSTART` property, it would be surprising to me to get a ClassCastException on the second line. With my proposed signature, indeed this code becomes either

```java
Set<Period<LocalDate>> result = (Set<Period<LocalDate>>) calculateRecurrenceSet(period);
LocalDate date = result.iterator().next().getStart()
```

or

```java
Set<Period<Temporal>> result = calculateRecurrenceSet(period);
LocalDate date = (LocalDate) result.iterator().next().getStart()
```

While this is more verbose, I like how the cast makes it explicit that I'm responsible for this assumption (justified by the knowledge of the `DTSTART` property).

Anyway, I don't feel particularly strongly about this, and I'm happy with the library as it is, but since you asked these are my 2ct :)

**Comment by benfortuna** [comment]
Good points, although I think the explicit cast of the entire set doesn't work (I get following error):

`Inconvertible types; cannot cast 'java.util.Set<net.fortuna.ical4j.model.Period<java.time.temporal.Temporal>>' to 'java.util.Set<net.fortuna.ical4j.model.Period<java.time.LocalDate>>'`

Still, I might change it anyway.
