### ISSUE TITLE
Unnecessary WARN in the log

### ISSUE THREAD

**Issue by xak2000** [ical4j/ical4j#694]
**Describe the bug**

Befor the commit 7295f03 there were no WARNs in the log on the application startup.
Now there is WARN level log when `TimeZoneRegistryImpl` class is loading:
```
WARN [   scheduling-1] n.f.ical4j.model.TimeZoneRegistryImpl    : Error loading timezone aliases: inStream parameter is null
```

**To Reproduce**

1. Configure log level to show at least WARN messages.
2. Do something to make `TimeZoneRegistryImpl` class to be loaded. E.g. `TimeZoneRegistryFactory.getInstance().createRegistry()`.
3. See the WARN message in the logs.

**Expected behavior**

The log message is related to the file `tz.alias` in the classpath root, that is absent. Previously as you can see in the commit diff, the log message was saying "Error loading **custom** timezone aliases" and this specific message was logged at the DEBUG level.

I think this message should not be logged at the WARN level for the custom `tz.alias` file as this file is purely optional. The absense of this file is not a warning. It's normal.

Also, I think it would be good to show the exact resource path/name in the log message, because "Error loading timezone aliases: inStream parameter is null" message is not really helpful. Why `inStream` parameter is null? What file has been trying to be read? Only a debug session will answer these questions.

**Environment:**

 - OS: Windows/Linux
 - Java Version: 21
 - iCal4j Version: 3.2.18

**Additional context**

There was no problem before the commit 7295f03 was added. E.g. 3.2.14 didn't have this problem.

It's not a big problem, of course. Just a log message. But it causes people to find the reason of the message, as it looks like something wrong with the configuration, while actually the configuration is fine as the custom `tz.alias` file is optional.

I mean, if the file was present, but cannot be read, then this situation would totally deserve the WARN, but if a custom optional file is absent, then the WARN is unjustified.

Also, some organizations could have a 0 WARN messages policy, that could be violated by this WARN.

**Comment by benfortuna** [comment]
Thanks for the feedback, I have now separated loading of included aliases from optional custom aliases, and reduced log severity to DEBUG for the latter. Will be in the next release.
