### ISSUE TITLE
Release ical4j 2.0

### ISSUE THREAD

**Issue by benfortuna** [ical4j/ical4j#70]
Issue to track progress on the 2.0 beta/final releases.

**Comment by artheus** [comment]
Please add this and also other issues etc to the 2.0 release milestone.

**Comment by benfortuna** [comment]
Release complete.

**Comment by scopendo** [comment]
Congratulations on release 2.0 – sorry if I've overlooked the obvious, but are there release notes for   v2.0 – the change log doesn't appear to have been updated.

**Comment by benfortuna** [comment]
Hi Scott,

Apologies for that, I've updated the release notes and API docs now:

http://ical4j.github.io/docs/ical4j/release-notes

regards,
ben
