### ISSUE TITLE
TimeZoneRegistryImpl attempts to load classpath resources from non-existent locations

### ISSUE THREAD

**Issue by jamesnetherton** [ical4j/ical4j#703]
Apache Camel has a ical4j component and the project recently upgraded ical4j to the 4.0.0 release. On startup of my application I see:

```
WARN  [net.for.ica.mod.TimeZoneRegistryImpl] (main) Error loading timezone aliases: inStream parameter is null
WARN  [net.for.ica.mod.TimeZoneRegistryImpl] (main) Error loading timezone aliases: inStream parameter is null
```

I think it's coming from `TimeZoneRegistryImpl` trying to load these resources:

https://github.com/ical4j/ical4j/blob/6c93ef1953142d4ff4062b941f04e8f75efff63e/src/main/java/net/fortuna/ical4j/model/TimeZoneRegistryImpl.java#L75-L76

The correct location for those two files I believe is at `net/fortuna/ical4j/transform/property`.

**Comment by benfortuna** [comment]
Actually this message is from trying to load any custom aliases you may provide, but as reported earlier the logging should not be so severe: #694

There will be a fix in the next release to reduce the severity.
