### ISSUE TITLE
NPE occured when share event with NFC.in ResourceLoader

### ISSUE THREAD

**Issue by XiaochunLiu** [ical4j/ical4j#71]
When share event with NFC.
during get timezone info. **Thread.currentThread().getContextClassLoader()** context class loader return null. (always issue in Samsung devices)

public static URL getResource(String name) {
        URL resource = null;
        try {
            //NPE
            **resource = Thread.currentThread().getContextClassLoader().getResource(name);**
        } catch (SecurityException e) {
            LOG.info("Unable to access context classloader, using default. " + e.getMessage());
        }
        if (resource == null) {
            resource = ResourceLoader.class.getResource("/" + name);
        }
        return resource;
    }

**Comment by benfortuna** [comment]
As I don't own a samsung device I can't tell if the null pointer is from the currentThread() or the getContextClassLoader(), however I'll assume it's the latter. I've added some null checking here, if you are able to try this branch to see if it fixes the problem that would be appreciated:

https://github.com/ical4j/ical4j/tree/bugfix/71-nullptr-samsung-devices

**Comment by XiaochunLiu** [comment]
Sorry to check so late.
I can't access this branch
https://github.com/ical4j/ical4j/tree/bugfix/71-nullptr-samsung-devices

**Comment by benfortuna** [comment]
It's ok, I merged the change already to master as I don't think it will have a negative impact. If you can test master branch that would be appreciated - snapshot builds are here also:

https://oss.sonatype.org/content/repositories/snapshots/org/mnode/ical4j/ical4j/2.0.0-SNAPSHOT/

regards,
ben
