### ISSUE TITLE
Error loading timezone aliases - these dont exist in the locations specified in the code

### ISSUE THREAD

**Issue by asifRaeesIqbal** [ical4j/ical4j#712]
https://github.com/ical4j/ical4j/blob/0ad88042428d68eef7ebd2fe005217ff5519a7bc/src/main/java/net/fortuna/ical4j/model/TimeZoneRegistryImpl.java#L75

the following files are under resources but under compliance folder

msTimezoneNames
msTimezoneIds

**Comment by benfortuna** [comment]
Fixed, thx for the feedback
