### ISSUE TITLE
Incorrect Event Time Handling During DST Transition

### ISSUE THREAD

**Issue by prakashujjwal1010** [ical4j/ical4j#754]
**Describe the bug**
For the string RRULE:FREQ=DAILY;COUNT=10;INTERVAL=1

When the start date is 2025-03-05T05:00-08:00[America/Los_Angeles]:

* 2025-03-05T05:00-08:00[America/Los_Angeles]
* 2025-03-06T05:00-08:00[America/Los_Angeles]
* 2025-03-07T05:00-08:00[America/Los_Angeles]
* 2025-03-08T05:00-08:00[America/Los_Angeles]
* 
* 2025-03-09T05:00-07:00[America/Los_Angeles] (DST applied)
* 
* 2025-03-10T05:00-07:00[America/Los_Angeles]
* 2025-03-11T05:00-07:00[America/Los_Angeles]
* 2025-03-12T05:00-07:00[America/Los_Angeles]
* 2025-03-13T05:00-07:00[America/Los_Angeles]
* 2025-03-14T05:00-07:00[America/Los_Angeles]

In the above, DST is handled because, even though the DST clock is ahead by 1 hour, the event time remains the same.

When the start date is 2025-03-05T02:00-08:00[America/Los_Angeles]:

* 2025-03-05T02:00-08:00[America/Los_Angeles]
* 2025-03-06T02:00-08:00[America/Los_Angeles]
* 2025-03-07T02:00-08:00[America/Los_Angeles]
* 2025-03-08T02:00-08:00[America/Los_Angeles]
* 
* 2025-03-09T03:00-07:00[America/Los_Angeles] (DST applied)
* 
* 2025-03-10T03:00-07:00[America/Los_Angeles]
* 2025-03-11T03:00-07:00[America/Los_Angeles]
* 2025-03-12T03:00-07:00[America/Los_Angeles]
* 2025-03-13T03:00-07:00[America/Los_Angeles]
* 2025-03-14T03:00-07:00[America/Los_Angeles]

In the above, DST is handled on 2025-03-09 at 2 AM by shifting the clock 1 hour ahead from 2 to 3. This means 2:00-2:59 does not exist, so the event is scheduled at 3:00 GMT-7:00. However, on the later days, 2:00 exists on the clock, so it should return 2025-03-10T02:00-07:00, not 2025-03-10T03:00-07:00.

**To Reproduce**
1. generate dates for RRULE:FREQ=DAILY;COUNT=10;INTERVAL=1 using recur.getDates(startDateTime, startDateTime, endDateTime)

**Expected behavior**
when DST is applied, an event that was occuring on hh:mm GMT-8 should occur at hh:mm GMT-7. from UTC perspective time will change.

**Environment (please complete the following information):**
 - ical4j java version: 4.0.4
 - java version:  java 17.0.11

**Additional context**
We are trying to use recurrence capability of ical4j 

@benfortuna do you have any idea regarding this?

**Comment by sks1995** [comment]
Hi @benfortuna, I am also facing similar issue. Can you please help in checking if this is expected behaviour ?

**Comment by benfortuna** [comment]
I've made a change to recurrence calculation that should fix this issue. Available in the latest release (4.0.6).

**Comment by prakashujjwal1010** [comment]
thanks @benfortuna. the issue is resolved at my end.
