### ISSUE TITLE
Library skips all valid occurrences in current week/month/year if `count is null` and `seed is before the start` in nextDate()

### ISSUE THREAD

**Issue by prakashujjwal1010** [ical4j/ical4j#759]
**Describe the bug**
For WEEKLY recurrence if we have multiple valid occurrences in 1 week and `count is null` and `seed is before the start` then it skips all valid occurrences in current week and starts from next week because of [this](https://github.com/ical4j/ical4j/blob/eb7fab4d6d2038965de0125beceb8079b0fd6fc2/src/main/java/net/fortuna/ical4j/model/Recur.java#L758).
Same thing exists for all other recurrences i.e MONTHLY, YEARLY, DAILY etc.

**To Reproduce**
1. Calculate nextDate() for `RRULE:FREQ=WEEKLY;UNTIL=20260714T063000;INTERVAL=1;BYDAY=FR,SA` using  `seed=2025-03-23T11:15:00` and `start=2025-03-25T11:15:00`
2. It will return `2025-04-04T11:15` while expected is `2025-03-28T11:15`

**Expected behavior**
It should not skip any valid occurrences in current week/month/year, currently because it is.

- ical4j java version: 4.0.6
 - java version:  java 17.0.11

**Additional context**
We are trying to use recurrence capability of ical4j 

cc: @benfortuna

**Comment by benfortuna** [comment]
Fix applied to the optimization logic to allow for different frequency/intervals. Will be in the next release

**Comment by prakashujjwal1010** [comment]
Okay, Thanks @benfortuna

**Comment by prakashujjwal1010** [comment]
@benfortuna when will be the next release?

**Comment by benfortuna** [comment]
Just want to fix a duplicate classes issue in the build then will release. If it's urgent I can release as is.

**Comment by prakashujjwal1010** [comment]
Yes its urgent, would appreciate it if you can release recurrence fixes little earlier if possible ;)

**Comment by benfortuna** [comment]
This is now available in the 4.0.7 release.

**Comment by prakashujjwal1010** [comment]
Thanks @benfortuna !
