### ISSUE TITLE
Missing CalScale.GREGORIAN and Version.VERSION_2_0 properties in 4.0.6 version.

### ISSUE THREAD

**Issue by alejsanc** [ical4j/ical4j#760]
Missing CalScale.GREGORIAN and Version.VERSION_2_0 properties in 4.0.6 version.

**Comment by benfortuna** [comment]
These have moved to [ImmutableCalscale](https://github.com/ical4j/ical4j/blob/eb7fab4d6d2038965de0125beceb8079b0fd6fc2/src/main/java/net/fortuna/ical4j/model/property/immutable/ImmutableCalScale.java#L49) and [ImmutableVersion](https://github.com/ical4j/ical4j/blob/eb7fab4d6d2038965de0125beceb8079b0fd6fc2/src/main/java/net/fortuna/ical4j/model/property/immutable/ImmutableVersion.java#L50)

**Comment by alejsanc** [comment]
OK thanks. In the version [Version](https://github.com/ical4j/ical4j/blob/eb7fab4d6d2038965de0125beceb8079b0fd6fc2/src/main/java/net/fortuna/ical4j/model/property/Version.java) class it would be convenient to remove the following text:

There is actually a constant defined in the Version class for this. e.g:
Calendar calendar = new Calendar();
calendar.add(Version.VERSION_2_0);

**Comment by benfortuna** [comment]
I'll fix that, thanks
