### ISSUE TITLE
Does iCal4j need to backport library?

### ISSUE THREAD

**Issue by dongmin-shin** [ical4j/ical4j#97]
Does iCal4j need to backport library?

because, ical4j library in android studio 2.1.2
I meet some warning during compile

warning is..

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(edu.emory.mathcs.backport.java.util.AbstractMap$2) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.

again... certainly, iCal4j need to backport?
thank you.

**Comment by benfortuna** [comment]
The backport library was a dependency on the maintenance branch of ical4j, however for use with Android I would suggest trying the latest from the master branch (ie. 2.0.x).

I haven't tested with Android recently so I can't really comment further on the error just now.

**Comment by benfortuna** [comment]
java.utils backport no longer used since version 2. Closing issue.
